// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Footer/Contact.vue
<template>
  <div class="footer" :class="{'has-bg': bg}">
    <v-container class="max-lg">
      <v-row :class="{ 'column-reverse': isMobile }" align="center">
        <v-col cols="12" md="5" class="px-12">
          <logo type="portrait" size="big" />
          <p class="use-text-subtitle2">
            Donec sit amet nulla sed arcu pulvinar ultricies commodo id ligula.
          </p>
          <div class="socmed">
            <v-btn icon variant="text" class="margin">
              <i class="ion-logo-facebook" />
            </v-btn>
            <v-btn icon variant="text" class="margin">
              <i class="ion-logo-linkedin" />
            </v-btn>
            <v-btn icon variant="text" class="margin">
              <i class="ion-logo-twitter" />
            </v-btn>
            <v-btn icon variant="text" class="margin">
              <i class="ion-logo-instagram" />
            </v-btn>
          </div>
          <div class="contact">
            <p class="use-text-paragraph">
              {{ $t('common.blog_phone') }}
              <br>
              +12 345 678 90
            </p>
            <v-divider class="divider my-3" />
            <p class="use-text-paragraph">
              Skype
              <br>
              company.skype
            </p>
          </div>
          <p class="body-2 mt-15 text-center">
            &copy;&nbsp;
            {{ brand.crypto.footerText }}
          </p>
        </v-col>
        <v-col cols="12" md="7">
          <div class="form-wrap">
            <v-snackbar
              v-model="openNotif"
              :timeout="4000"
              top
              right
            >
              Message Sent
            </v-snackbar>
            <v-card class="form-box">
              <v-row>
                <v-col lg="5" cols="12">
                  <h3 class="title-main use-text-title">
                    {{ $t('common.contact_title2') }}
                  </h3>
                </v-col>
                <v-col lg="7" cols="12">
                  <div class="form">
                    <v-form ref="form" v-model="valid">
                      <v-row class="spacing6">
                        <v-col cols="12" sm="12" class="px-6 py-0">
                          <v-text-field
                            v-model="name"
                            :rules="nameRules"
                            :label="$t('common.form_name')"
                            class="input"
                            color="secondary"
                            required
                            variant="filled"
                          />
                        </v-col>
                        <v-col cols="12" sm="12" class="px-6 py-0">
                          <v-text-field
                            v-model="email"
                            :rules="emailRules"
                            :label="$t('common.form_email')"
                            class="input"
                            color="secondary"
                            variant="filled"
                            required
                          />
                        </v-col>
                        <v-col cols="12" class="px-6 py-0">
                          <v-textarea
                            v-model="message"
                            rows="6"
                            class="input"
                            color="secondary"
                            variant="filled"
                            hide-details
                            :label="$t('common.form_message')"
                          />
                        </v-col>
                      </v-row>
                      <div class="btn-area">
                        <v-btn
                          color="primary"
                          size="large"
                          block
                          @click="validate"
                        >
                          {{ $t('common.form_send') }}
                        </v-btn>
                      </div>
                    </v-form>
                  </div>
                </v-col>
              </v-row>
            </v-card>
          </div>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped lang="scss">
@import './footer-contact';
</style>

<script>
import Logo from '../Logo';
import brand from '@/assets/text/brand';

export default {
  components: {
    Logo,
  },
  props: {
    bg: {
      type: Boolean,
      default: false,
    },
  },
  data: () => ({
    brand,
    openNotif: false,
    valid: true,
    name: '',
    nameRules: [v => !!v || 'Name is required'],
    email: '',
    emailRules: [
      v => !!v || 'E-mail is required',
      v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
    ],
    message: '',
  }),
  computed: {
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  methods: {
    validate() {
      if (this.$refs.form.validate()) {
        this.openNotif = true;
      }
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Footer/Contact.js
import React, { useState } from 'react';
import Container from '@mui/material/Container';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Button from '@mui/material/Button';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Divider from '@mui/material/Divider';
import Snackbar from '@mui/material/Snackbar';
import { ValidatorForm, TextValidator } from 'react-material-ui-form-validator';
import { useTranslation } from 'next-i18next';
import brand from '~/public/text/brand';
import { useText, useTextAlign } from '~/theme/common';
import Logo from '../Logo';
import useStyles from './contact-style';

function Contact() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const { t } = useTranslation('common');
  const [values, setValues] = useState({
    name: '',
    email: '',
    phone: '',
    company: '',
    message: ''
  });

  const [openNotif, setNotif] = useState(false);

  const handleChange = name => event => {
    setValues({ ...values, [name]: event.target.value });
  };

  const handleSubmit = () => {
    setNotif(true);
  };

  const handleClose = () => {
    setNotif(false);
  };

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  return (
    <footer className={classes.footer}>
      <Container className={classes.root} maxWidth="lg">
        <Grid container spacing={3} direction={isMobile ? 'column-reverse' : 'row'}>
          <Grid item xs={12} md={5}>
            <Box mx={{ sm: 5 }} mt={5}>
              <div className={classes.logo}>
                <Logo type="only" size="large" />
              </div>
              <Typography>
                {t('crypto-landing.banner_subtitle')}
              </Typography>
              <div className={classes.socmed}>
                <IconButton aria-label="Delete" className={classes.margin} size="small">
                  <i className="ion-social-facebook" />
                </IconButton>
                <IconButton aria-label="Delete" className={classes.margin} size="small">
                  <i className="ion-social-instagram" />
                </IconButton>
                <IconButton aria-label="Delete" className={classes.margin} size="small">
                  <i className="ion-social-twitter" />
                </IconButton>
                <IconButton aria-label="Delete" className={classes.margin} size="small">
                  <i className="ion-social-linkedin" />
                </IconButton>
              </div>
              <div className={classes.contact}>
                <Typography className={text.paragraph}>
                  {t('blog_phone')}
                  <br />
                  +12 345 678 90
                </Typography>
                <Divider className={classes.divider} />
                <Typography className={text.paragraph}>
                  Skype
                  <br />
                  jenadoe.skype
                </Typography>
                <Box mt={8}>
                  <Typography variant="subtitle2" className={align.textCenter}>
                    &copy;&nbsp;
                    {brand.crypto.footerText}
                  </Typography>
                </Box>
              </div>
            </Box>
          </Grid>
          <Grid item xs={12} md={7}>
            <div className={classes.formWrap}>
              <Snackbar
                anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
                key="top right"
                open={openNotif}
                autoHideDuration={4000}
                onClose={handleClose}
                ContentProps={{
                  'aria-describedby': 'message-id',
                }}
                message={<span id="message-id">Message Sent</span>}
              />
              <Paper className={classes.formBox}>
                <Grid container spacing={3}>
                  <Grid item lg={5} xs={12}>
                    <h3 className={cx(classes.title, text.title)}>
                      {t('contact_title2')}
                    </h3>
                  </Grid>
                  <Grid item lg={7} xs={12}>
                    <div className={classes.form}>
                      <ValidatorForm
                        onSubmit={handleSubmit}
                        onError={errors => console.log(errors)}
                      >
                        <TextValidator
                          className={classes.input}
                          label={t('form_name')}
                          onChange={handleChange('name')}
                          name="Name"
                          variant="filled"
                          value={values.name}
                          validators={['required']}
                          errorMessages={['this field is required']}
                        />
                        <TextValidator
                          className={classes.input}
                          label={t('form_email')}
                          onChange={handleChange('email')}
                          name="Email"
                          variant="filled"
                          value={values.email}
                          validators={['required', 'isEmail']}
                          errorMessages={['this field is required', 'email is not valid']}
                        />
                        <TextValidator
                          multiline
                          rows="6"
                          variant="filled"
                          className={classes.input}
                          label={t('form_message')}
                          onChange={handleChange('message')}
                          name="Message"
                          value={values.message}
                        />
                        <div className={classes.btnArea}>
                          <Button variant="contained" type="submit" fullWidth color="primary" size="large">
                            {t('form_send')}
                          </Button>
                        </div>
                      </ValidatorForm>
                    </div>
                  </Grid>
                </Grid>
              </Paper>
            </div>
          </Grid>
        </Grid>
      </Container>
    </footer>
  );
}

export default Contact;
