// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/marketing-theme/pages/collection/index.vue
<template>
  <div class="main-wrap">
    <main-header />
    <div class="container-wrap">
      <search v-model="keyword" />
      <div class="search-content">
        <v-container>
          <v-row align="start" justify="center">
            <v-col lg="9" md="8" cols="12">
              <div id="profile_portrait" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Profile Cards Portrait
                </h4>
                <v-row>
                  <v-col v-for="index in 2" :key="index" sm="6" cols="12">
                    <profile-card
                      :connection="100"
                      :favorites="10"
                      :albums="12"
                      :cover="imgAPI.photo[41]"
                      :avatar="imgAPI.avatar[2]"
                      name="Jihan Doe"
                      title="Web Designer"
                      type="full"
                      orientation="portrait"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="profile_l" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Profile Cards Landscape
                </h4>
                <v-row>
                  <v-col md="12">
                    <template v-for="index in 3" :key="index">
                      <profile-card
                        :connection="100"
                        :favorites="10"
                        :albums="12"
                        :cover="imgAPI.photo[43]"
                        :avatar="imgAPI.avatar[5]"
                        name="John Dalton"
                        title="Web Designer"
                        type="full"
                        orientation="landscape"
                      />
                      <br><br>
                    </template>
                  </v-col>
                </v-row>
              </div>
              <div id="product_p" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Product Cards Portrait
                </h4>
                <v-row>
                  <v-col v-for="index in 3" :key="index" sm="4" cols="12">
                    <product-card
                      :rating="3"
                      :price="20"
                      :img="imgAPI.photo[29]"
                      title="Sed lacinia velit"
                      desc="Proin pretium arcu eget metus porta consecteturc"
                      orientation="portrait"
                      type="full"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="product_l" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Product Cards Landscape
                </h4>
                <template v-for="index in 3" :key="index">
                  <product-card
                    :rating="3"
                    :price="20"
                    :img="imgAPI.photo[25]"
                    title="Sed lacinia velit"
                    desc="Proin pretium arcu eget metus porta consecteturc"
                    orientation="landscape"
                    type="full"
                  />
                  <br><br>
                </template>
              </div>
              <div id="media_video" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Video Cards
                </h4>
                <v-row>
                  <v-col v-for="index in 2" :key="index" sm="6" cols="12">
                    <media-card
                      :thumb="imgAPI.photo[9]"
                      title="Sed lacinia velit, ut malesuada eros interdum a"
                      orientation="portrait"
                      type="video"
                      href="#"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="media_photo" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Image Cards
                </h4>
                <v-row>
                  <v-col v-for="index in 2" :key="index" sm="6" cols="12">
                    <media-card
                      :thumb="imgAPI.photo[10]"
                      title="Sed lacinia velit, ut malesuada eros interdum a"
                      orientation="portrait"
                      type="photo"
                      href="#"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="news_p" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  News Cards Portrait
                </h4>
                <v-row>
                  <v-col v-for="index in 3" :key="index" sm="4" cols="12">
                    <news-card
                      :img="imgAPI.photo[34]"
                      title="Ut sed eros finibus, placerat orci id, dapibus mauris. Vestibulum consequat hendrerit lacus."
                      headline="news"
                      orientation="portrait"
                      type="full"
                      href="#"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="news_l" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  News Cards Landscape
                </h4>
                <v-row>
                  <v-col md="12">
                    <template v-for="index in 3" :key="index">
                      <news-card
                        :img="imgAPI.photo[37]"
                        title="Ut sed eros finibus, placerat orci id, dapibus mauris. Vestibulum consequat hendrerit lacus."
                        headline="news"
                        orientation="landscape"
                        type="full"
                        href="#"
                      />
                      <br><br>
                    </template>
                  </v-col>
                </v-row>
              </div>
              <div id="post_p" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Post Cards Portrait
                </h4>
                <v-row>
                  <v-col v-for="index in 3" :key="index" sm="4" cols="12">
                    <post-card
                      :img="imgAPI.photo[36]"
                      title="Maecenas rutrum dolor sed nisi"
                      desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                      date="12 Nov 2020"
                      orientation="portrait"
                      type="full"
                      href="#"
                    />
                  </v-col>
                </v-row>
              </div>
              <div id="post_l" class="space-top-short">
                <h4 class="use-text-subtitle mb-3">
                  Post Cards Landscape
                </h4>
                <v-row>
                  <v-col md="12">
                    <template v-for="index in 3" :key="index">
                      <post-card
                        :img="imgAPI.photo[32]"
                        title="Maecenas rutrum dolor sed nisi"
                        desc="Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula, eget suscipit orci. Suspendisse potenti. Proin pretium arcu eget metus porta consectetur Pellentesque habitant. Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula, eget suscipit orci. Suspendisse potenti. Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                        date="12 Nov 2020"
                        orientation="landscape"
                        type="full"
                        href="#"
                      />
                    </template>
                  </v-col>
                </v-row>
              </div>
            </v-col>
            <v-col lg="3" md="4" cols="12">
              <sidebar />
            </v-col>
          </v-row>
        </v-container>
      </div>
    </div>
    <main-footer />
  </div>
</template>

<style scoped lang="scss">
@import '@/assets/scss/pages';
</style>

<script>
import brand from '@/assets/text/brand';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Search from '@/components/Filter/Search';
import PostCard from '@/components/Cards/PostCard';
import NewsCard from '@/components/Cards/NewsCard';
import MediaCard from '@/components/Cards/MediaCard';
import ProductCard from '@/components/Cards/ProductCard';
import ProfileCard from '@/components/Cards/ProfileCard';
import Sidebar from '@/components/List/Sidebar';
import imgAPI from '@/assets/images/imgAPI';
import { defineNuxtComponent } from '#app';

export default defineNuxtComponent({
  data() {
    return {
      imgAPI,
      keyword: '',
    };
  },
  components: {
    'main-header': Header,
    'main-footer': Footer,
    Search,
    PostCard,
    NewsCard,
    MediaCard,
    ProductCard,
    ProfileCard,
    Sidebar,
  },
  head() {
    return {
      title: brand.marketing.name + ' - Card Collection',
    };
  },
});
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/medical-theme/pages/collection/index.js
import React, { useState, Fragment } from 'react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
// Use this below for Server Side Render/Translation (SSR)
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// Use this below for Static Site Generation (SSG)
// import { getStaticPaths, makeStaticProps } from '~/lib/getStatic';
import ProfileCards from '~/components/Cards/ProfileCard';
import ProductCards from '~/components/Cards/ProductCard';
import MediaCard from '~/components/Cards/MediaCard';
import NewsCard from '~/components/Cards/NewsCard';
import PostCard from '~/components/Cards/PostCard';
import brand from '~/public/text/brand';
import { useSpacing, useText } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Header from '~/components/Header';
import Footer from '~/components/Footer';
import Search from '~/components/Filter/Search';
import Sidebar from '~/components/List/Sidebar';

function Collection(props) {
  const { classes, cx } = useSpacing();
  const { classes: text } = useText();
  const { onToggleDark, onToggleDir } = props;
  const [keyword, setKeyword] = useState('');

  return (
    <Fragment>
      <Head>
        <title>
          { brand.medical.name + ' - Card Collection' }
        </title>
      </Head>
      <CssBaseline />
      <div className={classes.mainWrap}>
        <Header
          onToggleDark={onToggleDark}
          onToggleDir={onToggleDir}
        />
        <Search value={keyword} updateValue={setKeyword} />
        <section className={cx(classes.containerWrap, classes.containerFront)}>
          <div className={classes.searchContent}>
            <Container>
              <Grid container alignItems="flex-start" justifyContent="center" spacing={3}>
                <Grid item md={8} xs={12}>
                  <div id="profile_p" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Profile Cards Portrait
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(2)].map((e, index) => (
                        <Grid key={index.toString()} item sm={6} xs={12}>
                          <ProfileCards
                            connection={100}
                            favorites={10}
                            albums={12}
                            cover={imgAPI.photo[41]}
                            avatar={imgAPI.avatar[2]}
                            name="John Doe"
                            title="Web Designer"
                            type="full"
                            orientation="portrait"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="profile_l" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Profile Cards Landscape
                      </h4>
                    </Box>
                    <Grid container>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item md={12} xs={12}>
                          <ProfileCards
                            connection={100}
                            favorites={10}
                            albums={12}
                            cover={imgAPI.photo[43]}
                            avatar={imgAPI.avatar[5]}
                            name="John Dalton"
                            title="Web Designer"
                            type="full"
                            orientation="landscape"
                          />
                          <br />
                          <br />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="product_p" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Product Cards Portrait
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item sm={4} xs={12}>
                          <ProductCards
                            rating={3}
                            price={20}
                            img={imgAPI.photo[29]}
                            title="Sed lacinia velit"
                            desc="Proin pretium arcu eget metus porta consecteturc"
                            orientation="portrait"
                            type="full"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="product_l" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Product Cards Landscape
                      </h4>
                    </Box>
                    <Grid container>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item md={12} xs={12}>
                          <Box mb={3}>
                            <ProductCards
                              rating={3}
                              price={20}
                              img={imgAPI.photo[25]}
                              title="Sed lacinia velit"
                              desc="Proin pretium arcu eget metus porta consecteturc"
                              orientation="landscape"
                              type="full"
                            />
                          </Box>
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="media_video" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Video Cards
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(2)].map((e, index) => (
                        <Grid key={index.toString()} item sm={6} xs={12}>
                          <MediaCard
                            title="Sed lacinia velit, ut malesuada eros interdum a"
                            orientation="portrait"
                            type="video"
                            duration="10:01"
                            thumb={imgAPI.photo[9]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="media_photo" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Image Cards
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(2)].map((e, index) => (
                        <Grid key={index.toString()} item sm={6} xs={12}>
                          <MediaCard
                            title="Sed lacinia velit, ut malesuada eros interdum a"
                            orientation="portrait"
                            type="photo"
                            duration="23:15"
                            thumb={imgAPI.photo[10]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="news_p" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        News Cards Portrait
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item sm={4} xs={12}>
                          <NewsCard
                            title="Ut sed eros finibus, placerat orci id, dapibus mauris. Vestibulum consequat hendrerit lacus."
                            headline="news"
                            orientation="portrait"
                            type="full"
                            img={imgAPI.photo[34]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="news_l" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        News Cards Landscape
                      </h4>
                    </Box>
                    <Grid container>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item md={12} xs={12}>
                          <NewsCard
                            title="Ut sed eros finibus, placerat orci id, dapibus mauris. Vestibulum consequat hendrerit lacus."
                            headline="news"
                            orientation="landscape"
                            type="full"
                            img={imgAPI.photo[37]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="post_p" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Post Cards Portrait
                      </h4>
                    </Box>
                    <Grid container spacing={3}>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item sm={4} xs={12}>
                          <PostCard
                            title="Maecenas rutrum dolor sed nisi"
                            date="12 Nov 2021"
                            desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                            orientation="portrait"
                            type="full"
                            img={imgAPI.photo[36]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                  <div id="post_l" className={classes.spaceTopShort}>
                    <Box mb={3}>
                      <h4 className={text.subtitle}>
                        Post Cards Landscape
                      </h4>
                    </Box>
                    <Grid container>
                      {[...Array(3)].map((e, index) => (
                        <Grid key={index.toString()} item md={12} xs={12}>
                          <PostCard
                            title="Maecenas rutrum dolor sed nisi"
                            date="12 Nov 2021"
                            desc="Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula, eget suscipit orci. Suspendisse potenti. Proin pretium arcu eget metus porta consectetur Pellentesque habitant. Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula, eget suscipit orci. Suspendisse potenti. Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                            orientation="landscape"
                            type="full"
                            img={imgAPI.photo[32]}
                            href="#"
                          />
                        </Grid>
                      ))}
                    </Grid>
                  </div>
                </Grid>
                <Grid item lg={3} md={4} xs={12}>
                  <Sidebar />
                </Grid>
              </Grid>
            </Container>
          </div>
        </section>
        <Footer toggleDir={onToggleDir} />
      </div>
    </Fragment>
  );
}

Collection.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

// Use this below for Server Side Render/Translation (SSR)
export const getStaticProps = async ({ locale }) => ({ props: { ...await serverSideTranslations(locale, ['common']) } });

// Use this below for Static Site Generation (SSG)
// const getStaticProps = makeStaticProps(['common']);
// export { getStaticPaths, getStaticProps };

export default Collection;
