// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Cards/PostCard.vue
<template>
  <v-card
    :class="[orientation, type]"
    class="post-card mx-auto"
    max-width="1000"
  >
    <div class="figure">
      <v-img
        :src="img"
        cover
        class="white--text"
        height="200px"
      />
    </div>
    <div class="properties">
      <strong class="use-text-subtitle text-truncate">
        <span>
          {{ title }}
        </span>
      </strong>
      <v-card-subtitle>
        {{ date }}
      </v-card-subtitle>
      <v-card-text class="desc">
        <span class="text-body-1">
          <span>{{ desc }}</span>
        </span>
      </v-card-text>
      <v-card-actions>
        <v-btn
          :href="href"
          size="small"
          variant="outlined"
          class="action-btn"
          color="primary"
        >
          Read more
        </v-btn>
      </v-card-actions>
    </div>
  </v-card>
</template>

<style scoped lang="scss">
@import './post-news-card';
</style>

<script>
export default {
  props: {
    img: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    date: {
      type: String,
      required: true,
    },
    desc: {
      type: String,
      required: true,
    },
    orientation: {
      type: String,
      default: 'portrait',
    },
    type: {
      type: String,
      default: 'full', // available props: full, rounded, over, oval
    },
    href: {
      type: String,
      default: '#',
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/cloud-theme/components/Cards/PostCard.js
import React from 'react';
import PropTypes from 'prop-types';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import CardMedia from '@mui/material/CardMedia';
import Box from '@mui/material/Box';
import { useTranslation } from 'next-i18next';
import useStyles from './post-card-style';

function PostCard(props) {
  const { classes, cx } = useStyles();
  const { t } = useTranslation('common');
  const {
    date,
    title,
    desc,
    img,
    orientation,
    type,
    href,
  } = props;

  return (
    <Card className={cx(classes.postCard, classes[orientation], classes[type])}>
      <div className={classes.figure}>
        <CardMedia className={classes.media} image={img} title="thumb" />
      </div>
      <div className={classes.properties}>
        <CardContent>
          <div className={classes.text}>
            <Typography display="block" noWrap variant="h6" className={classes.title}>
              <Box component="span" display="block" textOverflow="ellipsis" overflow="hidden">
                {title}
              </Box>
            </Typography>
            <Typography variant="caption" className={classes.caption}>{date}</Typography>
            <Typography display="block" className={classes.desc}>
              <span>
                {desc}
              </span>
            </Typography>
          </div>
        </CardContent>
        <CardActions className={classes.action}>
          <Button variant="outlined" color="primary" href={href} className={classes.btn}>
            {t('btn_read_more')}
          </Button>
        </CardActions>
      </div>
    </Card>
  );
}

PostCard.propTypes = {
  date: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  desc: PropTypes.string.isRequired,
  img: PropTypes.string.isRequired,
  orientation: PropTypes.string,
  type: PropTypes.string,
  href: PropTypes.string,
};

PostCard.defaultProps = {
  orientation: 'portrait',
  href: '#!',
  type: 'full', // available props: full, rounded, over, oval
};

export default PostCard;
