// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/cloud-theme/components/Home/Benefit/Benefit.js
import React, { useRef } from 'react';
import Container from '@mui/material/Container';
import Carousel from 'react-slick';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import { useText } from '~/theme/common';
import Title from '../../Title';
import useStyles from './benefit-style';

function Benefit() {
  const { classes } = useStyles();
  const { classes: text } = useText();
  const slider = useRef(null);
  const { t } = useTranslation('common');

  const imgSlider = [
    imgAPI.cloud[32],
    imgAPI.cloud[33],
    imgAPI.cloud[34],
    imgAPI.cloud[35],
    imgAPI.cloud[36],
    imgAPI.cloud[37]
  ];

  const slickOptions = {
    dots: true,
    arrows: false,
    speed: 800,
    slidesToShow: 1,
    infinite: true,
    autoplay: true,
    fade: true,
    autoplaySpeed: 10000
  };

  return (
    <div className={classes.root}>
      <div className={classes.illustrationBg}>
        <img
          className="img-2d3d"
          src={imgAPI.cloud[11]}
          data-2d={imgAPI.cloud[10]}
          data-3d={imgAPI.cloud[11]}
          alt="feature"
        />
      </div>
      <Container maxWidth="md" fixed>
        <div className={classes.wrapper}>
          <div className={classes.desc}>
            <Title
              caption={t('cloud-landing.benefit_headtitle')}
              text={t('cloud-landing.benefit_title')}
              align="center"
              dark
            />
            <p className={text.subtitle2}>
              {t('cloud-landing.banner_subtitle')}
            </p>
            <div className={classes.carousel}>
              <div className={classes.nav}>
                <a
                  href="#!"
                  className={classes.prev}
                  onClick={() => slider.current.slickPrev()}
                >
                  <ArrowForwardIosIcon />
                </a>
                <a
                  href="#!"
                  className={classes.next}
                  onClick={() => slider.current.slickNext()}
                >
                  <ArrowForwardIosIcon />
                </a>
              </div>
              <Carousel
                {...slickOptions}
                className={classes.slider}
                ref={slider}
              >
                {imgSlider.map((item, index) => (
                  <div className={classes.slide} key={index.toString()}>
                    <div className={classes.border}>
                      <figure>
                        <img src={item} alt="screen" />
                      </figure>
                    </div>
                  </div>
                ))}
              </Carousel>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
}

Benefit.propTypes = {

};

export default Benefit;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Benefit/Benefit.vue
<template>
  <div class="root">
    <div class="illustration-bg">
      <img
        class="img-2d3d"
        :src="imgAPI.cloud[11]"
        :data-2d="imgAPI.cloud[10]"
        :data-3d="imgAPI.cloud[11]"
        alt="feature"
      >
    </div>
    <v-container class="max-md fixed-width">
      <div class="wrapper">
        <div class="desc">
          <main-title
            :caption="$t('cloud.benefit_headtitle')"
            :text="$t('cloud.benefit_title')"
            align="center"
            dark
          />
          <p class="use-text-subtitle2">
            {{ $t('cloud.banner_subtitle') }}
          </p>
          <div v-if="loaded" class="carousel">
            <div class="nav">
              <a
                href="javascript:void(0)"
                class="prev"
                @click="prev"
              >
                <v-icon>mdi-chevron-left</v-icon>
              </a>
              <a
                href="javascript:void(0)"
                class="next"
                @click="next"
              >
                <v-icon>mdi-chevron-right</v-icon>
              </a>
            </div>
            <splide
              ref="slider"
              class="slider"
              :options="slickOptions"
            >
              <splide-slide v-for="(item, index) in imgSlider" :key="index">
                <div class="slide">
                  <div class="border">
                    <figure>
                      <img :src="item" alt="screen">
                    </figure>
                  </div>
                </div>
              </splide-slide>
            </splide>
          </div>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './benefit-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import Title from '../../Title';
import imgAPI from '@/assets/images/imgAPI';

export default {
  components: {
    'main-title': Title,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      imgAPI,
      loaded: false,
      imgSlider: [
        imgAPI.cloud[32],
        imgAPI.cloud[33],
        imgAPI.cloud[34],
        imgAPI.cloud[35],
        imgAPI.cloud[36],
        imgAPI.cloud[37],
      ],
      slickOptions: {
        pagination: true,
        arrows: false,
        speed: 800,
        perPage: 1,
        type: 'fade',
        autoplay: true,
        interval: 10000,
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
      },
    };
  },
  mounted() {
    this.loaded = true;
  },
  methods: {
    next() {
      this.$refs.slider.go('>');
    },
    prev() {
      this.$refs.slider.go('<');
    },
  },
};
</script>
