// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Integration/Integration.vue
<template>
  <div class="root">
    <v-container>
      <div>
        <v-row>
          <div class="dashed-divider" />
          <v-col cols="12" md="6">
            <div
              data-aos="fade-down"
              data-aos-delay="500"
              data-aos-offset="100"
              data-aos-duration="500"
            >
              <div>
                <figure class="illustration">
                  <svg class="droplet secondary-color">
                    <use xlink:href="/images/cloud/droplet.svg#main" />
                  </svg>
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[21]"
                    :data-2d="imgAPI.cloud[20]"
                    :data-3d="imgAPI.cloud[21]"
                    alt="background"
                  >
                </figure>
                <main-title
                  :caption="$t('cloud.mainfeature_titleitem2')"
                  :text="$t('cloud.mainfeature_titleitem1')"
                  align="center"
                />
              </div>
            </div>
          </v-col>
          <v-col cols="12" md="6">
            <div
              data-aos="fade-down"
              data-aos-delay="800"
              data-aos-offset="100"
              data-aos-duration="500"
            >
              <div>
                <figure class="illustration">
                  <svg class="droplet primary-color">
                    <use xlink:href="/images/cloud/droplet.svg#main" />
                  </svg>
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[23]"
                    :data-2d="imgAPI.cloud[22]"
                    :data-3d="imgAPI.cloud[23]"
                    alt="background"
                  >
                </figure>
                <main-title
                  :caption="$t('cloud.morefeature_headtitle2')"
                  :text="$t('cloud.benefit_title')"
                  align="center"
                />
              </div>
            </div>
          </v-col>
        </v-row>
      </div>
      <div class="timeline">
        <div class="solid-divider" />
        <div>
          <v-row>
            <v-col sm="6" cols="12" class="px-lg-10">
              <ul class="left-side">
                <li
                  v-for="(item, index) in integration1"
                  :key="index"
                  :class="'type-' + item.color"
                >
                  <div
                    data-aos="fade-left"
                    :data-aos-delay="(200 + (100 * index))"
                    data-aos-offset="100"
                    data-aos-duration="500"
                  >
                    <div class="item">
                      <div class="text">
                        <strong class="use-text-subtitle2">{{ item.title }}</strong>
                        <p>{{ item.subtitle }}</p>
                      </div>
                      <div class="icon">
                        <i :class="item.icon" />
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </v-col>
            <v-col sm="6" cols="12" class="px-lg-10">
              <ul class="right-side">
                <li
                  v-for="(item, index) in integration2"
                  :key="index"
                  :class="'type-' + item.color"
                >
                  <div
                    data-aos="fade-right"
                    :data-aos-delay="(200 + (200 * index))"
                    data-aos-offset="100"
                    data-aos-duration="500"
                  >
                    <div class="item">
                      <div class="icon">
                        <i :class="item.icon" />
                      </div>
                      <div class="text">
                        <strong class="use-text-subtitle2">{{ item.title }}</strong>
                        <p>{{ item.subtitle }}</p>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </v-col>
          </v-row>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import 'integration-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';

export default {
  components: {
    'main-title': Title,
  },
  data() {
    return {
      imgAPI,
      integration1: [
        {
          color: 'secondary',
          icon: 'ion-ios-flash',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'secondary',
          icon: 'ion-ios-folder-open',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'secondary',
          icon: 'ion-ios-lock',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
      ],
      integration2: [
        {
          color: 'primary',
          icon: 'ion-md-git-merge',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'primary',
          icon: 'ion-logo-buffer',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'primary',
          icon: 'ion-md-cloud-upload',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
      ],
    };
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Home/Integration/Integration.js
import React from 'react';
import Container from '@mui/material/Container';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import useStyle from './integration-style';
import { useText } from '~/theme/common';
import Title from '../../Title';

const integration1 = [
  {
    color: 'Secondary',
    icon: 'ion-flash',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Secondary',
    icon: 'ion-folder',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Secondary',
    icon: 'ion-locked',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  }
];

const integration2 = [
  {
    color: 'Primary',
    icon: 'ion-merge',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Primary',
    icon: 'ion-soup-can',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Primary',
    icon: 'ion-upload',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  }
];

function Integration() {
  const { classes, cx } = useStyle();
  const { t } = useTranslation('common');
  const { classes: text } = useText();

  return (
    <div className={classes.root}>
      <Container>
        <Grid container className={classes.decoWrap}>
          <div className={classes.dashedDivider} />
          <Grid item md={6} xs={12}>
            <ScrollAnimation
              animateOnce
              animateIn="fadeInUpShort"
              delay={500}
              duration={0.5}
            >
              <div>
                <figure className={classes.illustration}>
                  <svg className={cx(classes.droplet, classes.secondaryColor)}>
                    <use xlinkHref="/images/cloud/droplet.svg#main" />
                  </svg>
                  <img
                    className="img-2d3d"
                    src={imgAPI.cloud[21]}
                    data-2d={imgAPI.cloud[20]}
                    data-3d={imgAPI.cloud[21]}
                    alt="background"
                  />
                </figure>
                <Title
                  caption={t('cloud-landing.mainfeature_titleitem2')}
                  text={t('cloud-landing.mainfeature_titleitem1')}
                  align="center"
                />
              </div>
            </ScrollAnimation>
          </Grid>
          <Grid item md={6} xs={12}>
            <Box px={{ sm: 10 }}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInUpShort"
                delay={800}
                duration={0.5}
              >
                <div>
                  <figure className={classes.illustration}>
                    <svg className={cx(classes.droplet, classes.primaryColor)}>
                      <use xlinkHref="/images/cloud/droplet.svg#main" />
                    </svg>
                    <img
                      className="img-2d3d"
                      src={imgAPI.cloud[23]}
                      data-2d={imgAPI.cloud[22]}
                      data-3d={imgAPI.cloud[23]}
                      alt="background"
                    />
                  </figure>
                  <Title
                    caption={t('cloud-landing.morefeature_headtitle2')}
                    text={t('cloud-landing.benefit_title')}
                    align="center"
                  />
                </div>
              </ScrollAnimation>
            </Box>
          </Grid>
        </Grid>
      </Container>
      <Container>
        <div className={classes.timeline}>
          <div className={classes.solidDivider} />
          <Grid container>
            <Grid item sm={6} xs={12}>
              <Box px={{ lg: 5 }}>
                <ul className={classes.leftSide}>
                  {integration1.map((item, index) => (
                    <li
                      key={index.toString()}
                      className={classes['type' + item.color]}
                    >
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInRightShort"
                        offset={-100}
                        delay={(200 + (100 * index))}
                        duration={0.5}
                      >
                        <div className={classes.item}>
                          <div className={classes.text}>
                            <strong className={text.subtitle2}>{item.title}</strong>
                            <p>{item.subtitle}</p>
                          </div>
                          <div className={classes.icon}>
                            <i className={item.icon} />
                          </div>
                        </div>
                      </ScrollAnimation>
                    </li>
                  ))}
                </ul>
              </Box>
            </Grid>
            <Grid item sm={6} xs={12}>
              <Box px={{ lg: 5 }}>
                <ul className={classes.rightSide}>
                  {integration2.map((item, index) => (
                    <li
                      key={index.toString()}
                      className={classes['type' + item.color]}
                    >
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInLeftShort"
                        offset={-100}
                        delay={(200 + (200 * index))}
                        duration={0.5}
                      >
                        <div className={classes.item}>
                          <div className={classes.icon}>
                            <i className={item.icon} />
                          </div>
                          <div className={classes.text}>
                            <strong className={text.subtitle2}>{item.title}</strong>
                            <p>{item.subtitle}</p>
                          </div>
                        </div>
                      </ScrollAnimation>
                    </li>
                  ))}
                </ul>
              </Box>
            </Grid>
          </Grid>
        </div>
      </Container>
    </div>
  );
}

Integration.propTypes = {

};

export default Integration;
