// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Decoration/CloudDeco.vue
<template>
  <div class="cloud-deco">
    <div class="left-deco">
      <svg class="cloud big">
        <use xlink:href="/images/cloud/cloud_deco.svg#main" />
      </svg>
      <svg class="cloud small">
        <use xlink:href="/images/cloud/cloud_deco.svg#main" />
      </svg>
    </div>
    <div class="right-deco">
      <svg class="cloud big">
        <use xlink:href="/images/cloud/cloud_deco.svg#main" />
      </svg>
      <svg class="cloud small">
        <use xlink:href="/images/cloud/cloud_deco.svg#main" />
      </svg>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './decoration-style.scss';
</style>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Decoration/CloudDeco.js
import React from 'react';
import useStyles from './decoration-style';

export default function FormDeco() {
  const { classes, cx } = useStyles();
  return (
    <div className={classes.cloudDeco}>
      <div className={classes.leftDeco}>
        <svg className={cx(classes.cloud, classes.big)}>
          <use xlinkHref="/images/cloud/cloud_deco.svg#main" />
        </svg>
        <svg className={cx(classes.cloud, classes.small)}>
          <use xlinkHref="/images/cloud/cloud_deco.svg#main" />
        </svg>
      </div>
      <div className={classes.rightDeco}>
        <svg className={cx(classes.cloud, classes.big)}>
          <use xlinkHref="/images/cloud/cloud_deco.svg#main" />
        </svg>
        <svg className={cx(classes.cloud, classes.small)}>
          <use xlinkHref="/images/cloud/cloud_deco.svg#main" />
        </svg>
      </div>
    </div>
  );
}
