// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Home/DownloadBanner/DownloadBanner.js
import React from 'react';
import Container from '@mui/material/Container';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import useStyles from './download-style';

function CallAction() {
  // Translation Function
  const { t } = useTranslation('common');
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('sm'));
  const { classes } = useStyles();
  return (
    <Container maxWidth="md">
      <ScrollAnimation animateOnce animateIn="fadeInUpShort" offset={40} delay={300} duration={0.5}>
        <div className={classes.root}>
          {isDesktop && (
            <figure>
              <img src={imgAPI.crypto[35]} alt="mobile" />
            </figure>
          )}
          <div>
            <h3>{t('crypto-landing.download_mobile')}</h3>
            <div className={classes.btnArea}>
              <a href="#">
                <img src="/images/crypto/app-store.png" alt="app store" />
              </a>
              <a href="#">
                <img src="/images/crypto/play-store.png" alt="play store" />
              </a>
            </div>
          </div>
        </div>
      </ScrollAnimation>
    </Container>
  );
}

export default CallAction;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Home/DownloadBanner/DownloadBanner.vue
<template>
  <v-container class="max-md">
    <div
      data-aos="fade-up"
      data-aos-offset="40"
      data-aos-delay="300"
      data-aos-duration="500"
    >
      <div class="root">
        <figure v-if="isDesktop">
          <img :src="imgAPI.crypto[35]" alt="mobile">
        </figure>
        <div>
          <h3>{{ $t('crypto.download_mobile') }}</h3>
          <div class="btn-area">
            <nuxt-link to="/">
              <img src="/images/crypto/app-store.png" alt="app store">
            </nuxt-link>
            <nuxt-link to="/">
              <img src="/images/crypto/play-store.png" alt="play store">
            </nuxt-link>
          </div>
        </div>
      </div>
    </div>
  </v-container>
</template>

<style lang="scss" scoped>
@import './download-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';

export default {
  data() {
    return {
      imgAPI,
    };
  },
  computed: {
    isDesktop() {
      const smUp = this.$vuetify.display.smAndUp;
      return smUp;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>
