// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Home/Testimonials/Testimonials.vue
<template>
  <div class="root">
    <v-container :class="{ fixed: isDesktop }">
      <title-main
        :text="$t('crypto.testi_title')"
        align="center"
      />
      <p class="use-text-subtitle2 text-center">
        {{ $t('crypto.testi_subtitle') }}
      </p>
      <v-row class="spacing6" justify="center">
        <v-col md="10" cols="12">
          <div class="slider-wrap">
            <div v-if="loaded" class="carousel">
              <v-btn
                color="primary"
                icon
                variant="text"
                class="nav prev"
                @click="slickPrev()"
              >
                <i class="ion-ios-arrow-back" />
              </v-btn>
              <splide
                ref="slider"
                :options="slickOptions"
                @splide:active="handleAfterChange"
              >
                <splide-slide
                  v-for="(item, index) in testiContent"
                  :key="index"
                >
                  <div class="item">
                    <div class="testi-content">
                      <testi-card
                        :text="item.text"
                        :name="item.name"
                        :title="item.title"
                        :avatar="item.avatar"
                        :active="index === active"
                      />
                    </div>
                  </div>
                </splide-slide>
              </splide>
              <v-btn
                color="primary"
                icon
                variant="text"
                class="nav next"
                @click="slickNext()"
              >
                <i class="ion-ios-arrow-forward" />
              </v-btn>
            </div>
          </div>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './testi-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';
import TestiCard from '../../Cards/TestiStackCard';

const testiContent = [
  {
    text:
      'Vivamus sit amet interdum elit. Proin lacinia erat ac velit tempus auctor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam nec ex aliquet, aliquam neque non.',
    name: 'John Doe',
    avatar: imgAPI.avatar[6],
    title: 'Chief Digital Officer',
  },
  {
    text:
      'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jean Doe',
    avatar: imgAPI.avatar[7],
    title: 'Chief Digital Officer',
  },
  {
    text:
      'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jena Doe',
    avatar: imgAPI.avatar[1],
    title: 'Graphic Designer',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel.',
    name: 'Jovelin Doe',
    avatar: imgAPI.avatar[2],
    title: 'Senior Graphic Designer',
  },
  {
    text:
      'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jihan Doe',
    avatar: imgAPI.avatar[3],
    title: 'CEO Software House',
  },
  {
    text:
      'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'John Doe',
    avatar: imgAPI.avatar[9],
    title: 'Senior Graphic Designer',
  },
];

export default {
  components: {
    'title-main': Title,
    TestiCard,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      active: 0,
      testiContent,
      slickOptions: {
        type: 'fade',
        pagination: false,
        speed: 500,
        arrows: false,
        autoplay: true,
        interval: 7000,
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
        breakpoints: {
          600: {
            pagination: true,
          },
        },
      },
    };
  },
  computed: {
    isDesktop() {
      const lgUp = this.$vuetify.display.lgAndUp;
      return lgUp;
    },
  },
  mounted() {
    this.loaded = true;
  },
  methods: {
    slickNext() {
      this.$refs.slider.go('>');
    },
    slickPrev() {
      this.$refs.slider.go('<');
    },
    handleGoTo(slide) {
      this.$refs.slider.go(slide);
    },
    handleAfterChange(slide) {
      this.active = slide.index;
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/components/Home/Testimonials/Testimonials.js
import React, { useState, useRef } from 'react';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import Carousel from 'react-slick';
import { useTranslation } from 'next-i18next';
import imgApi from '~/public/images/imgAPI';
import { useText } from '~/theme/common';
import Title from '../../Title';
import TestiCard from '../../Cards/TestimonialCard';
import useStyle from './testi-style';

const testiContent = [
  {
    text: 'Vivamus sit amet interdum elit. Proin lacinia erat ac velit tempus auctor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam nec ex aliquet, aliquam neque non.',
    name: 'John Doe',
    avatar: imgApi.avatar[6],
    title: 'Chief Digital Officer',
  },
  {
    text: 'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jean Doe',
    avatar: imgApi.avatar[7],
    title: 'Chief Digital Officer',
  },
  {
    text: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jena Doe',
    avatar: imgApi.avatar[1],
    title: 'Graphic Designer',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel.',
    name: 'Jovelin Doe',
    avatar: imgApi.avatar[2],
    title: 'Senior Graphic Designer',
  },
  {
    text: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jihan Doe',
    avatar: imgApi.avatar[3],
    title: 'CEO Software House',
  },
  {
    text: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'John Doe',
    avatar: imgApi.avatar[9],
    title: 'Senior Graphic Designer',
  },
];

function Testimonials() {
  const slider = useRef(null);
  const { classes, cx } = useStyle();
  const { classes: text } = useText();
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('lg'));
  const { t } = useTranslation('common');
  const [active, setActive] = useState(0);
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    fade: true,
    autoplay: true,
    autoplaySpeed: 7000,
    arrows: false,
    afterChange: (current) => setActive(current),
    responsive: [
      {
        breakpoint: 699,
        settings: {
          dots: true,
        }
      }
    ]
  };
  return (
    <div className={classes.root}>
      <Container fixed={isDesktop}>
        <Title text={t('crypto-landing.testi_title')} align="center" />
        <Typography className={text.subtitle2} align="center">
          {t('crypto-landing.testi_subtitle')}
        </Typography>
        <Grid container spacing={6}>
          <Grid item md={1} xs={12} />
          <Grid item md={10} xs={12}>
            <div className={classes.sliderWrap}>
              <div className={classes.carousel}>
                <button
                  type="button"
                  className={cx(classes.nav, classes.prev)}
                  onClick={() => slider.current.slickPrev()}
                >
                  <i className="ion-ios-arrow-back" />
                </button>
                <Carousel ref={slider} {...settings}>
                  {testiContent.map((item, index) => (
                    <div key={index.toString()} className={classes.item}>
                      <div className={classes.slideContent}>
                        <TestiCard
                          text={item.text}
                          name={item.name}
                          title={item.title}
                          avatar={item.avatar}
                          active={index === active}
                        />
                      </div>
                    </div>
                  ))}
                </Carousel>
                <button
                  type="button"
                  className={cx(classes.nav, classes.next)}
                  onClick={() => slider.current.slickNext()}
                >
                  <i className="ion-ios-arrow-forward" />
                </button>
              </div>
            </div>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

export default Testimonials;
