// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/pages/about/index.vue
<template>
  <div class="main-wrap">
    <main-header />
    <div class="container-front">
      <banner>
        <img
          :src="imgAPI.cloudInner[1]"
          :data-2d="imgAPI.cloudInner[0]"
          :data-3d="imgAPI.cloudInner[1]"
          class="img-2d3d"
          alt="services 3d"
        >
      </banner>
      <div class="space-top-short container-front">
        <company-logo />
      </div>
      <div class="space-top-short">
        <counter />
      </div>
      <div class="space-top-short">
        <v-container>
          <v-row justify="center">
            <v-col md="6" cols="12">
              <about-video />
            </v-col>
            <v-col md="6" sm="8" cols="12" class="px-md-12">
              <about-progress />
            </v-col>
          </v-row>
        </v-container>
      </div>
      <div class="space-top-short">
        <team-slider />
      </div>
      <div class="space-top-short">
        <photo-slider />
      </div>
    </div>
    <footer-extend with-counter>
      <main-footer />
    </footer-extend>
  </div>
</template>

<style lang="scss" scoped>
@import '@/assets/scss/pages';
</style>

<script>
import brand from '@/assets/text/brand';
import imgAPI from '@/assets/images/imgAPI';
import Header from '@/components/Header';
import Banner from '@/components/About/Banner';
import CompanyLogo from '@/components/CompanyLogo';
import Counter from '@/components/Counter';
import Video from '@/components/About/Video';
import Progress from '@/components/About/Progress';
import TeamSlider from '@/components/About/TeamSlider';
import PhotoSlider from '@/components/About/PhotoSlider';
import FooterExtend from '@/components/Footer/FooterExtend';
import Footer from '@/components/Footer';
import { defineNuxtComponent } from '#app';

export default defineNuxtComponent({
  components: {
    'main-header': Header,
    'main-footer': Footer,
    Banner,
    CompanyLogo,
    Counter,
    'about-progress': Progress,
    'about-video': Video,
    TeamSlider,
    PhotoSlider,
    FooterExtend,
  },
  data() {
    return {
      imgAPI,
    };
  },
  head() {
    return {
      title: 'About | ' + brand.cloud.desc,
    };
  },
});
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/cloud-theme/pages/about/index.js
import React, { Fragment } from 'react';
import PropTypes from 'prop-types';
import CssBaseline from '@mui/material/CssBaseline';
import Head from 'next/head';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
// Use this below for Server Side Render/Translation (SSR)
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// Use this below for Static Site Generation (SSG)
// import { getStaticPaths, makeStaticProps } from '~/lib/getStatic';
import imgAPI from '~/public/images/imgAPI';
import { useSpacing } from '~/theme/common';
import Header from '~/components/Header';
import Counter from '~/components/Counter';
import Banner from '~/components/About/Banner';
import PhotoSlider from '~/components/About/PhotoSlider';
import TeamSlider from '~/components/About/TeamSlider';
import AboutVideo from '~/components/About/Video';
import AboutProgress from '~/components/About/Progress';
import CompanyLogo from '~/components/CompanyLogo';
import Footer from '~/components/Footer';
import FooterExtend from '~/components/Footer/FooterExtend';
import brand from '~/public/text/brand';

function About(props) {
  const { classes } = useSpacing();
  const { onToggleDark, onToggleDir } = props;
  return (
    <Fragment>
      <Head>
        <title>
          { brand.cloud.name + ' - About' }
        </title>
      </Head>
      <CssBaseline />
      <section id="home" />
      <div className={classes.mainWrap}>
        <Header
          onToggleDark={onToggleDark}
          onToggleDir={onToggleDir}
        />
        <Banner>
          <img
            src={imgAPI.cloudInner[1]}
            data-2d={imgAPI.cloudInner[0]}
            data-3d={imgAPI.cloudInner[1]}
            className="img-2d3d"
            alt="services 3d"
          />
        </Banner>
        <CompanyLogo />
        <div className={classes.spaceTopShort}>
          <Counter />
        </div>
        <div className={classes.spaceTopShort}>
          <Container>
            <Grid container justifyContent="center" spacing={6}>
              <Grid item md={6} xs={12}>
                <AboutVideo />
              </Grid>
              <Grid item md={6} sm={8} xs={12}>
                <AboutProgress />
              </Grid>
            </Grid>
          </Container>
        </div>
        <div className={classes.spaceTopShort}>
          <TeamSlider />
        </div>
        <div className={classes.spaceTopShort}>
          <PhotoSlider />
        </div>
        <FooterExtend withCounter>
          <Footer toggleDir={onToggleDir} />
        </FooterExtend>
      </div>
    </Fragment>
  );
}

About.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

export default About;

// Use this below for Server Side Render/Translation (SSR)
export const getStaticProps = async ({ locale }) => ({ props: { ...await serverSideTranslations(locale, ['common']) } });

// Use this below for Static Site Generation (SSG)
// const getStaticProps = makeStaticProps(['common']);
// export { getStaticPaths, getStaticProps };
