// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/medical-theme/components/Home/AskDoctors/AskDoctors.vue
<template>
  <div class="root">
    <v-container>
      <div class="deco">
        <img
          :src="imgAPI.medical[17]"
          :data-3d="imgAPI.medical[16]"
          :data-2d="imgAPI.medical[17]"
          class="img-2d3d"
          alt="speciality 3d"
        >
      </div>
      <div>
        <v-row>
          <v-col cols="12" md="3" class="px-sm-6">
            <div
              data-aos-offset="-100"
              data-aos="fade-left"
              data-aos-delay="200"
              data-aos-duration="300"
            >
              <div class="side-filter">
                <h4 class="use-text-title">
                  {{ $t('medical.ask_doctors') }}
                </h4>
                <v-list class="nav" item-value="All">
                  <div>
                    <v-list-item
                      v-for="(item, index) in categories"
                      :key="index"
                      :class="{'v-list-item--active': item === value }"
                      class="filter"
                      @click="value = item"
                    >
                      <v-list-item-title>
                        {{ item }}
                      </v-list-item-title>
                    </v-list-item>
                  </div>
                </v-list>
              </div>
            </div>
          </v-col>
          <v-col cols="12" md="9" lg="8" class="px-6">
            <div class="massonry">
              <v-row>
                <v-col
                  v-for="(item, index) in doctorsData"
                  :key="index"
                  cols="12"
                  sm="6"
                  class="px-lg-8 px-3 py-3"
                >
                  <div
                    data-aos-delay="200 * index"
                    data-aos-duration="400"
                    data-aos="fade-up"
                  >
                    <div>
                      <profile-card
                        :avatar="item.avatar"
                        :name="item.name"
                        :title="item.title"
                        :rating="item.rating"
                        :exp="item.exp"
                      />
                    </div>
                  </div>
                </v-col>
              </v-row>
            </div>
          </v-col>
        </v-row>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './ask-doctors-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import ProfileCard from '../../Cards/ProfileCard2';

export default {
  components: {
    ProfileCard,
  },
  data() {
    return {
      item: 0,
      imgAPI,
      loaded: false,
      value: 'All',
      categories: [
        'All',
        'Orthopedic',
        'Nutritionist',
        'Pediatric',
        'Anaesthestic',
      ],
      doctorsData: [
        {
          avatar: imgAPI.medical[31],
          name: 'Jena Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
        {
          avatar: imgAPI.medical[32],
          name: 'John Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
        {
          avatar: imgAPI.medical[33],
          name: 'Jihan Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
        {
          avatar: imgAPI.medical[34],
          name: 'James Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
        {
          avatar: imgAPI.medical[35],
          name: 'Jim Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
        {
          avatar: imgAPI.medical[36],
          name: 'Jessy Doe',
          title: 'Pediatric Surgeon',
          rating: 95,
          exp: 4,
        },
      ],
    };
  },
  mounted() {
    this.loaded = true;
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/medical-theme/components/Home/AskDoctors/AskDoctors.js
import React, { useState } from 'react';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';
import Container from '@mui/material/Container';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import { useText } from '~/theme/common';
import DoctorCard from '../../Cards/DoctorCard';
import useStyles from './ask-doctors-style';

const categories = [
  'all',
  'Orthopedic',
  'Nutritionist',
  'Pediatric',
  'Anaesthestic'
];

const doctorsData = [
  {
    avatar: imgAPI.medical[31],
    name: 'Jena Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  },
  {
    avatar: imgAPI.medical[32],
    name: 'John Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  },
  {
    avatar: imgAPI.medical[33],
    name: 'Jihan Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  },
  {
    avatar: imgAPI.medical[34],
    name: 'James Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  },
  {
    avatar: imgAPI.medical[35],
    name: 'Jim Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  },
  {
    avatar: imgAPI.medical[36],
    name: 'Jessy Doe',
    title: 'Pediatric Surgeon',
    rating: 95,
    exp: 4
  }
];

function AskDoctors() {
  // Theme breakpoints
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('md'));

  // Translation Function
  const { t } = useTranslation('common');

  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const [selectedIndex, setSelectedIndex] = useState('all');

  function handleListItemClick(event, index) {
    setSelectedIndex(index);
  }

  const renderCard = (item, index) => (
    <DoctorCard
      key={index.toString()}
      name={item.name}
      title={item.title}
      avatar={item.avatar}
      rating={item.rating}
      exp={item.exp}
    />
  );

  return (
    <div className={classes.root}>
      <Container>
        <div className={classes.deco}>
          <img
            src={imgAPI.medical[17]}
            data-3d={imgAPI.medical[16]}
            data-2d={imgAPI.medical[17]}
            className="img-2d3d"
            alt="speciality 3d"
          />
        </div>
        <Grid spacing={2} container>
          <Grid item md={3} xs={12}>
            <Box px={{ lg: 6 }}>
              <ScrollAnimation animateOnce animateIn="fadeInLeftShort" offset={-100} delay={300} duration={0.3}>
                <div className={classes.sideFilter}>
                  <h4 className={text.title}>
                    {t('medical-landing.ask_doctors')}
                  </h4>
                  <List component="nav">
                    {categories.map((item, index) => (
                      <ListItem
                        button
                        key={index.toString()}
                        className={cx(classes.filter, selectedIndex === item && classes.active)}
                        onClick={event => handleListItemClick(event, item)}
                      >
                        <ListItemText primary={item} />
                      </ListItem>
                    ))}
                  </List>
                </div>
              </ScrollAnimation>
            </Box>
          </Grid>
          <Grid item lg={8} md={9} xs={12}>
            <div className={classes.massonry}>
              <Grid container spacing={isDesktop ? 6 : 4}>
                {doctorsData.map((item, index) => (
                  <Grid item sm={6} xs={12} key={index.toString()}>
                    <ScrollAnimation animateOnce animateIn="fadeInUpShort" offset={-100} delay={(index * 200)} duration={0.4}>
                      <div>
                        {renderCard(item, index)}
                      </div>
                    </ScrollAnimation>
                  </Grid>
                ))}
              </Grid>
            </div>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

export default AskDoctors;
