// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/Home/NewsEvent/NewsEvent.vue
<template>
  <div class="root">
    <title-main align="center">
      {{ $t('retail.news_title') }}
    </title-main>
    <p class="use-text-subtitle2 text-center">
      {{ $t('retail.news_desc') }}
    </p>
    <div class="blog-wrap">
      <v-container class="fixed-width">
        <v-row class="spacing6 list-news">
          <v-col md="5" cols="12" class="pa-6 pa-sm-10">
            <news-card
              :img="imgAPI.photo[21]"
              title="Sed imperdiet enim ligula, vitae viverra justo."
              headline="headline"
              orientation="portrait"
              type="over"
              href="#"
            />
          </v-col>
          <v-col md="7" cols="12" class="pa-6 pa-sm-10">
            <div class="mb-6">
              <news-card
                :img="imgAPI.photo[22]"
                :orientation="isMobile ? 'portrait' : 'landscape'"
                title="Vestibulum dignissim orci vitae eros rutrum euismod."
                headline="news"
                type="over"
                href="#"
              />
            </div>
            <div class="mb-6" :class="{'mt-15': isMobile}">
              <news-card
                :img="imgAPI.photo[37]"
                :orientation="isMobile ? 'portrait' : 'landscape'"
                title="Cras convallis lacus orci, tristique tincidunt magna consequat in."
                headline="news"
                type="over"
                href="#"
              />
            </div>
          </v-col>
        </v-row>
      </v-container>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './news-event-style.scss';
</style>

<script>
import imgAPI from '@/assets/images/imgAPI';
import NewsCard from '../../Cards/NewsCard';
import Title from '../../Title';

export default {
  components: {
    NewsCard,
    'title-main': Title,
  },
  data: () => ({
    imgAPI,
  }),
  computed: {
    isMobile() {
      const xsDown = this.$vuetify.display.xs;
      return xsDown;
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/retail-theme/components/Home/NewsEvent/NewsEvent.js
import React from 'react';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Title from '../../Title';
import NewsCard from '../../Cards/NewsCard';
import useStyles from './news-event-style';

function NewsEvent() {
  const { classes } = useStyles();
  const { classes: text } = useText();
  const { t } = useTranslation('common');

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <div className={classes.root}>
      <Title align="center">
        {t('retail-landing.news_title')}
      </Title>
      <Typography align="center" className={text.subtitle2}>
        {t('retail-landing.news_desc')}
      </Typography>
      <div className={classes.blogWrap}>
        <Container fixed>
          <Grid container spacing={6} className={classes.listNews}>
            <Grid item md={5} xs={12}>
              <Box p={{ md: 3 }}>
                <NewsCard
                  img={imgAPI.photo[21]}
                  title="Sed imperdiet enim ligula, vitae viverra justo."
                  headline="headline"
                  orientation="portrait"
                  type="over"
                  href="#"
                />
              </Box>
            </Grid>
            <Grid item md={7} xs={12}>
              <Box mb={6}>
                <NewsCard
                  img={imgAPI.photo[22]}
                  orientation={isMobile ? 'portrait' : 'landscape'}
                  title="Vestibulum dignissim orci vitae eros rutrum euismod."
                  headline="news"
                  type="over"
                  href="#"
                />
                <NewsCard
                  img={imgAPI.photo[37]}
                  orientation={isMobile ? 'portrait' : 'landscape'}
                  title="Vestibulum dignissim orci vitae eros rutrum euismod."
                  headline="news"
                  type="over"
                  href="#"
                />
              </Box>
            </Grid>
          </Grid>
        </Container>
      </div>
    </div>
  );
}

export default NewsEvent;
