// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/fintech-theme/components/Forms/Contact.vue
<template>
  <div class="page-wrap">
    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
      top
      right
      class="notification"
    >
      <div class="action">
        Message Sent
      </div>
      <v-btn
        text
        icon
        @click="snackbar = false"
      >
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-snackbar>
    <v-container class="inner-wrap max-md">
      <div class="full-form-wrap">
        <div class="text-center">
          <h3 class="use-text-title use-text-primary pb-3 text-center">
            {{ $t('common.contact_title2') }}
          </h3>
          <p class="desc use-text-subtitle2 text-center">
            {{ $t('common.contact_subtitle') }}
          </p>
        </div>
        <div class="form">
          <v-form
            ref="form"
            v-model="valid"
          >
            <v-row class="spacing6">
              <v-col cols="12" sm="6" class="px-6">
                <v-text-field
                  v-model="name"
                  :rules="nameRules"
                  :label="$t('common.form_name')"
                  color="white"
                  variant="filled"
                  required
                />
              </v-col>
              <v-col cols="12" sm="6" class="px-6">
                <v-text-field
                  v-model="email"
                  :rules="emailRules"
                  :label="$t('common.form_email')"
                  color="white"
                  variant="filled"
                  required
                />
              </v-col>
              <v-col cols="12" sm="6" class="px-6">
                <v-text-field
                  v-model="phone"
                  :label="$t('common.form_phone')"
                  color="white"
                  variant="filled"
                />
              </v-col>
              <v-col cols="12" sm="6" class="px-6">
                <v-text-field
                  v-model="company"
                  :label="$t('common.form_company')"
                  color="white"
                  variant="filled"
                />
              </v-col>
              <v-col cols="12" class="px-6">
                <v-textarea
                  v-model="message"
                  rows="6"
                  color="white"
                  variant="filled"
                  :label="$t('common.form_message')"
                />
              </v-col>
            </v-row>
            <div class="btn-area">
              <div class="form-control-label">
                <v-checkbox
                  v-model="checkbox"
                  color="primary"
                  :rules="[v => !!v || 'You must agree to continue!']"
                  :label="$t('common.form_terms')"
                  required
                  hide-details
                />
                <span class="ps-2">
                  <a href="#" class="link">
                    {{ $t('common.form_privacy') }}
                  </a>
                </span>
              </div>
              <v-btn
                :block="isMobile"
                color="primary"
                size="large"
                @click="validate"
              >
                {{ $t('common.form_send') }}
              </v-btn>
            </div>
          </v-form>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './form-style.scss';
</style>

<script>
import link from '@/assets/text/link';

export default {
  data() {
    return {
      valid: true,
      snackbar: false,
      name: '',
      nameRules: [v => !!v || 'Name is required'],
      email: '',
      emailRules: [
        v => !!v || 'E-mail is required',
        v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
      ],
      phone: '',
      company: '',
      message: '',
      checkbox: false,
      routeLink: link,
    };
  },
  computed: {
    isMobile() {
      const xsDown = this.$vuetify.display.xs;
      return xsDown;
    },
  },
  methods: {
    validate() {
      if (this.$refs.form.validate()) {
        this.snackbar = true;
      }
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas2-theme/components/Forms/Contact.js
import React, { useState, useEffect } from 'react';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import IconButton from '@mui/material/IconButton';
import FormControlLabel from '@mui/material/FormControlLabel';
import Grid from '@mui/material/Grid';
import Snackbar from '@mui/material/Snackbar';
import CloseIcon from '@mui/icons-material/Close';
import { ValidatorForm, TextValidator } from 'react-material-ui-form-validator';
import { useTranslation } from 'next-i18next';
import { useText, useTextAlign } from '~/theme/common';
import Checkbox from './Checkbox';
import useStyles from './form-style';

function Contact() {
  const { t } = useTranslation('common');
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();

  const [values, setValues] = useState({
    name: '',
    email: '',
    phone: '',
    company: '',
    message: ''
  });

  useEffect(() => {
    ValidatorForm.addValidationRule('isTruthy', value => value);
  });

  const [openNotif, setNotif] = useState(false);

  const [check, setCheck] = useState(false);

  const handleChange = name => event => {
    setValues({ ...values, [name]: event.target.value });
  };

  const handleCheck = event => {
    setCheck(event.target.checked);
  };

  const handleSubmit = () => {
    setNotif(true);
  };

  const handleClose = () => {
    setNotif(false);
  };

  return (
    <div className={classes.fullFormWrap}>
      <Snackbar
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        key="top right"
        open={openNotif}
        autoHideDuration={4000}
        onClose={handleClose}
        classes={{
          anchorOriginTopRight: classes.notif
        }}
        action={(
          <IconButton onClick={handleClose} color="inherit" size="small">
            <CloseIcon />
          </IconButton>
        )}
        ContentProps={{
          'aria-describedby': 'message-id',
        }}
        message={<span id="message-id">Message Sent</span>}
      />
      <h3 className={cx(text.title, text.textPrimary, align.textCenter)}>
        {t('contact_title2')}
      </h3>
      <p className={cx(classes.desc, text.subtitle2, align.textCenter)}>
        {t('contact_subtitle')}
      </p>
      <Box mt={{ sm: 8 }} px={{ sm: 6 }}>
        <ValidatorForm
          onSubmit={handleSubmit}
          onError={errors => console.log(errors)}
        >
          <Grid container spacing={3}>
            <Grid item sm={6} xs={12}>
              <TextValidator
                fullWidth
                className={classes.input}
                label={t('form_name')}
                onChange={handleChange('name')}
                name="Name"
                variant="filled"
                value={values.name}
                validators={['required']}
                errorMessages={['this field is required']}
              />
            </Grid>
            <Grid item sm={6} xs={12}>
              <TextValidator
                fullWidth
                className={classes.input}
                label={t('form_email')}
                onChange={handleChange('email')}
                name="Email"
                variant="filled"
                value={values.email}
                validators={['required', 'isEmail']}
                errorMessages={['this field is required', 'email is not valid']}
              />
            </Grid>
            <Grid item sm={6} xs={12}>
              <TextValidator
                fullWidth
                className={classes.input}
                label={t('form_phone')}
                onChange={handleChange('phone')}
                name="Phone"
                variant="filled"
                value={values.phone}
              />
            </Grid>
            <Grid item sm={6} xs={12}>
              <TextValidator
                fullWidth
                className={classes.input}
                label={t('form_company')}
                onChange={handleChange('company')}
                name="Company"
                variant="filled"
                value={values.company}
              />
            </Grid>
            <Grid item xs={12}>
              <TextValidator
                multiline
                fullWidth
                rows="6"
                variant="filled"
                className={classes.input}
                label={t('form_message')}
                onChange={handleChange('message')}
                name="Message"
                value={values.message}
              />
            </Grid>
          </Grid>
          <div className={cx(classes.btnArea, classes.flex)}>
            <FormControlLabel
              control={(
                <Checkbox
                  validators={['isTruthy']}
                  errorMessages="This field is required"
                  checked={check}
                  value={check}
                  onChange={(e) => handleCheck(e)}
                  color="primary"
                />
              )}
              label={(
                <span>
                  {t('form_terms')}
                  <br />
                  <a href="#" className={classes.link}>
                    {t('form_privacy')}
                  </a>
                </span>
              )}
            />
            <Button variant="contained" type="submit" color="primary" size="large">
              {t('form_send')}
            </Button>
          </div>
        </ValidatorForm>
      </Box>
    </div>
  );
}

Contact.propTypes = {

};

export default Contact;
