// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/About/PhotoSlider.vue
<template>
  <vue-easy-lightbox
    v-if="loaded"
    :visible="visible"
    :imgs="imgs"
    :index="index"
    @hide="handleHide"
  />
  <v-container>
    <div class="gallery-root">
      <title-main
        :text="$t('common.about_gallery')"
        :align="isMobile ? 'center' : 'left'"
      />
      <p class="use-text-subtitle2">
        Vestibulum faucibus eget erat eget pretium. Donec commodo convallis eget suscipit orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </p>
      <div v-if="loaded" class="carousel">
        <v-btn
          icon
          size="small"
          variant="text"
          class="nav prev"
          @click="slickPrev()"
        >
          <v-icon>mdi-arrow-left</v-icon>
        </v-btn>
        <splide
          ref="slider"
          :options="slickOptions"
        >
          <splide-slide
            v-for="(index) in 6"
            :key="index"
          >
            <div
              class="item px-3"
              @click="() => showImg(index-1)"
              @keydown.enter="() => showImg(index)"
            >
              <media-card
                title="Sed lacinia velit, ut malesuada eros interdum a"
                orientation="portrait"
                type="photo"
                :thumb="imgAPI.photo[10 + index]"
              />
            </div>
          </splide-slide>
        </splide>
        <v-btn
          icon
          variant="text"
          size="small"
          class="nav next"
          @click="slickNext()"
        >
          <v-icon>mdi-arrow-right</v-icon>
        </v-btn>
      </div>
    </div>
  </v-container>
</template>

<style scoped lang="scss">
@import './about-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import MediaCard from '../Cards/MediaCard';
import Title from '../Title';
import imgAPI from '@/assets/images/imgAPI';

export default {
  components: {
    'title-main': Title,
    MediaCard,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      visible: false,
      index: 0,
      item: 0,
      imgAPI,
      loaded: false,
      imgs: [
        imgAPI.photo[11],
        imgAPI.photo[12],
        imgAPI.photo[13],
        imgAPI.photo[14],
        imgAPI.photo[15],
        imgAPI.photo[16],
      ],
      slickOptions: {
        pagination: false,
        arrows: false,
        perPage: 3,
        perMove: 1,
        type: 'loop',
        direction: 'ltr',
        reducedMotion: {
          autoplay: true,
          speed: 500,
          rewindSpeed: 1000,
        },
        breakpoints: {
          800: {
            perPage: 2,
          },
          600: {
            perPage: 1,
          },
        },
      },
    };
  },
  computed: {
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
      }
    }, 100);
  },
  methods: {
    slickNext() {
      this.$refs.slider.go('>');
    },
    slickPrev() {
      this.$refs.slider.go('<');
    },
    showImg(index) {
      this.index = index;
      this.visible = true;
    },
    handleHide() {
      this.visible = false;
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/About/PhotoSlider.js
import React, { useState, useEffect, useRef } from 'react';
import Box from '@mui/material/Box';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Container from '@mui/material/Container';
import Lightbox from 'react-18-image-lightbox';
import IconButton from '@mui/material/IconButton';
import ButtonBase from '@mui/material/ButtonBase';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import Carousel from 'react-slick';
import { useTranslation } from 'next-i18next';
import { useText, useTextAlign } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Title from '../Title';
import MediaCard from '../Cards/MediaCard';
import useStyles from './about-style';

function PhotoSlider() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  const { t } = useTranslation('common');

  // Image Lightbox
  const [photoIndex, setPhotoIndex] = useState(0);
  const [open, setOpen] = useState(false);
  const imgData = [
    imgAPI.photo[11],
    imgAPI.photo[12],
    imgAPI.photo[13],
    imgAPI.photo[14],
    imgAPI.photo[15],
    imgAPI.photo[16]
  ];

  // Slider Carousel
  const slider = useRef(null);
  const [loaded, setLoaded] = useState(false);
  const settings = {
    dots: false,
    arrows: false,
    slidesToShow: 3,
    infinite: true,
    autoplay: false,
    responsive: [
      {
        breakpoint: 800,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1
        }
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1
        }
      }
    ]
  };

  useEffect(() => {
    setLoaded(true);
  }, []);

  const handleNext = () => {
    slider.current.slickNext();
  };

  const handlePrev = () => {
    slider.current.slickPrev();
  };

  function showPopup(index) {
    setOpen(true);
    setPhotoIndex(index);
  }

  function onMovePrevRequest() {
    setPhotoIndex((photoIndex + imgData.length - 1) % imgData.length);
  }

  function onMoveNextRequest() {
    setPhotoIndex((photoIndex + imgData.length + 1) % imgData.length);
  }

  return (
    <div>
      {open && (
        <Lightbox
          mainSrc={imgData[photoIndex]}
          nextSrc={imgData[(photoIndex + 1) % imgData.length]}
          prevSrc={imgData[(photoIndex + 1) % imgData.length]}
          onCloseRequest={() => setOpen(false)}
          onMovePrevRequest={onMovePrevRequest}
          onMoveNextRequest={onMoveNextRequest}
        />
      )}
      <Container>
        <Box mb={3}>
          <Title text={t('about_gallery')} align={isMobile ? 'center' : 'left'} />
        </Box>
        <p className={cx(text.subtitle2, isMobile ? align.textCenter : '')}>
          Vestibulum faucibus eget erat eget pretium. Donec commodo convallis eget suscipit orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>
        {loaded && (
          <div className={classes.carousel}>
            <IconButton
              onClick={() => handlePrev()}
              className={cx(classes.nav, classes.prev)}
              size="large"
            >
              <ArrowBackIcon />
            </IconButton>
            <Carousel ref={slider} {...settings}>
              {imgData.map((item, index) => (
                <ButtonBase
                  key={index.toString()}
                  className={classes.item}
                  onClick={() => showPopup(index)}
                >
                  <Box px={1}>
                    <MediaCard
                      title="Sed lacinia velit, ut malesuada eros interdum a"
                      orientation="portrait"
                      type="photo"
                      thumb={item}
                      href="#!"
                    />
                  </Box>
                </ButtonBase>
              ))}
            </Carousel>
            <IconButton
              onClick={() => handleNext()}
              className={cx(classes.nav, classes.next)}
              size="large"
            >
              <ArrowForwardIcon />
            </IconButton>
          </div>
        )}
      </Container>
    </div>
  );
}

export default PhotoSlider;
