// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Home/Benefit/Benefit.js
import React from 'react';
import Container from '@mui/material/Container';
import Carousel from 'react-slick';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import { useText } from '~/theme/common';
import Title from '../../Title';
import useStyles from './benefit-style';

function Benefit() {
  const { classes } = useStyles();
  const { classes: text } = useText();
  const { t } = useTranslation('common');

  const imgSlider = [
    imgAPI.crypto[28],
    imgAPI.crypto[29],
    imgAPI.crypto[30],
    imgAPI.crypto[31],
    imgAPI.crypto[32],
    imgAPI.crypto[33]
  ];

  const slickOptions = {
    dots: true,
    arrows: false,
    speed: 800,
    slidesToShow: 1,
    autoplay: true,
    fade: true,
    autoplaySpeed: 10000
  };

  return (
    <div className={classes.root}>
      <div className={classes.decoBg}>
        <svg>
          <use xlinkHref="/images/crypto/deco-benefit.svg#main" />
        </svg>
      </div>
      <Container maxWidth="md" fixed>
        <div className={classes.wrapper}>
          <div className={classes.desc}>
            <Title
              text={t('crypto-landing.benefit_title')}
              align="center"
            />
            <p className={text.subtitle2}>
              {t('crypto-landing.banner_subtitle')}
            </p>
            <div className={classes.carousel}>
              <Carousel
                {...slickOptions}
                className={classes.slider}
              >
                {imgSlider.map((item, index) => (
                  <div className={classes.slide} key={index.toString()}>
                    <div className={classes.border}>
                      <figure>
                        <img src={item} alt="screen" />
                      </figure>
                    </div>
                  </div>
                ))}
              </Carousel>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
}

export default Benefit;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Home/Benefit/Benefit.vue
<template>
  <div class="root">
    <div class="deco-bg">
      <svg>
        <use xlink:href="/images/crypto/deco-benefit.svg#main" />
      </svg>
    </div>
    <v-container class="max-md fixed-width">
      <div class="wrapper">
        <div class="desc">
          <title-main
            :text="$t('crypto.benefit_title')"
            align="center"
          />
          <p class="use-text-subtitle2">
            {{ $t('crypto.banner_subtitle') }}
          </p>
          <div v-if="loaded" class="carousel">
            <splide
              ref="slider"
              class="slider"
              :options="slickOptions"
            >
              <splide-slide v-for="(item, index) in imgSlider" :key="index">
                <div class="slide">
                  <div class="border">
                    <figure>
                      <img :src="item" alt="screen">
                    </figure>
                  </div>
                </div>
              </splide-slide>
            </splide>
          </div>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './benefit-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';

export default {
  components: {
    Splide,
    SplideSlide,
    'title-main': Title,
  },
  data() {
    return {
      imgAPI,
      loaded: false,
      imgSlider: [
        imgAPI.crypto[28],
        imgAPI.crypto[29],
        imgAPI.crypto[30],
        imgAPI.crypto[31],
        imgAPI.crypto[32],
        imgAPI.crypto[33],
      ],
      slickOptions: {
        type: 'fade',
        pagination: true,
        arrows: false,
        speed: 800,
        perPage: 1,
        autoplay: false,
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
      },
    };
  },
  mounted() {
    this.loaded = true;
  },
};
</script>
