// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/retail-theme/components/Home/Feature/Feature.js
import React, { useState } from 'react';
import Container from '@mui/material/Container';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import YouTube from 'react-youtube';
import CloseIcon from '@mui/icons-material/Close';
import Dialog from '@mui/material/Dialog';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Zoom from '@mui/material/Zoom';
import IconButton from '@mui/material/IconButton';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import { useText, useTextAlign } from '~/theme/common';
import yt from '~/youtube';
import TitleSecondary from '../../Title/TitleSecondary';
import Title from '../../Title';
import useStyles from './feature-style';

const Transition = React.forwardRef(function Transition(props, ref) { // eslint-disable-line
  return <Zoom ref={ref} {...props} />;
});

function Feature() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const { t } = useTranslation('common');

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const isDesktop = useMediaQuery(theme.breakpoints.up('lg'));

  const [player, setPlayer] = useState([]);
  const [openPopup, setOpenPopup] = useState(false);

  const handleClickOpen = () => {
    if (yt.use) {
      setOpenPopup(true);
      player[0].playVideo();
    }
  };

  const handleClose = () => {
    setOpenPopup(false);
    player[0].pauseVideo();
  };

  const _onReady = event => {
    player.push(event.target);
    setPlayer(player);
  };

  const opts = {
    height: '360',
    width: '640',
    playerVars: { // https://developers.google.com/youtube/player_parameters
      autoplay: 0,
      controls: 1,
      rel: 0,
      showinfo: 1,
      mute: 0,
      origin: 'http://localhost:3007'
    }
  };

  return (
    <div className={classes.root}>
      <Dialog
        open={openPopup}
        TransitionComponent={Transition}
        keepMounted
        classes={{ paper: classes.videoPopup }}
        onClose={handleClose}
      >
        <DialogTitle id="alert-dialog-slide-title">
          {t('retail-landing.banner_title')}
          <IconButton onClick={handleClose} className={classes.closeBtn} size="large">
            <CloseIcon className={classes.icon} />
          </IconButton>
        </DialogTitle>
        <DialogContent>
          {yt.use && (
            <YouTube
              videoId="MltGO66gTbo"
              onReady={_onReady}
              opts={opts}
            />
          )}
        </DialogContent>
      </Dialog>
      <Container fixed={isDesktop}>
        <Title align="center">
          {t('retail-landing.feature_title')}
        </Title>
        <div className={classes.item}>
          <Grid container alignItems="center" justifyContent="center" direction={isMobile ? 'column-reverse' : 'row'}>
            <Grid item md={4} xs={12}>
              <Box px={4}>
                <ScrollAnimation
                  animateOnce
                  offset={-200}
                  animateIn="fadeInLeftShort"
                  duration={0.5}
                >
                  <div className={classes.illustration}>
                    <div className={cx(classes.bg, classes.pipe1)} />
                    <figure className={cx(classes.screen1, classes.mobileScreen)}>
                      <img src={imgAPI.retail[25]} alt="screen" />
                    </figure>
                    <figure className={cx(classes.graphic, classes.artwork1)}>
                      <img
                        src={imgAPI.retail[10]}
                        data-2d={imgAPI.retail[9]}
                        data-3d={imgAPI.retail[10]}
                        className="img-2d3d"
                        alt="illustration"
                      />
                    </figure>
                  </div>
                </ScrollAnimation>
              </Box>
            </Grid>
            <Grid item md={6} xs={12}>
              <Box px={4}>
                <div className={classes.desc}>
                  <TitleSecondary align={isMobile ? 'center' : 'left'} text={t('retail-landing.feature_title1')} />
                  <p className={cx(text.subtitle2, isMobile ? align.textCenter : align.textLeft)}>
                    {t('retail-landing.feature_desc1')}
                  </p>
                </div>
              </Box>
            </Grid>
          </Grid>
        </div>
        <div className={classes.item}>
          <Grid container alignItems="center">
            <Grid item md={6} xs={12}>
              <Box px={4}>
                <div className={classes.desc}>
                  <TitleSecondary align={isMobile ? 'center' : 'right'} text={t('retail-landing.feature_title2')} />
                  <p className={cx(text.subtitle2, isMobile ? align.textCenter : align.textRight)}>
                    {t('retail-landing.feature_desc2')}
                  </p>
                </div>
              </Box>
            </Grid>
            <Grid item md={6} xs={12}>
              <Box px={{ sm: 8 }}>
                <ScrollAnimation
                  animateOnce
                  offset={-200}
                  animateIn="fadeInRightShort"
                  duration={0.5}
                  delay={500}
                >
                  <div className={classes.illustration}>
                    <div className={cx(classes.bg, classes.pipe2)} />
                    <figure className={cx(classes.screen1, classes.desktopScreen)}>
                      <img src={imgAPI.retail[26]} alt="screen" />
                    </figure>
                    <figure className={cx(classes.graphic, classes.artwork2)}>
                      <img
                        src={imgAPI.retail[12]}
                        data-2d={imgAPI.retail[11]}
                        data-3d={imgAPI.retail[12]}
                        className="img-2d3d"
                        alt="illustration"
                      />
                    </figure>
                  </div>
                </ScrollAnimation>
              </Box>
            </Grid>
          </Grid>
        </div>
        <div className={cx(classes.item, classes.last)}>
          <Container className={classes.container}>
            <Grid container justifyContent="center">
              <Grid item md={8} xs={12} className={classes.videoContainer}>
                <div className={cx(classes.bg, classes.pipe3)} />
                <div className={cx(classes.bg, classes.pipe4)} />
                <TitleSecondary align="center" text={t('retail-landing.feature_title3')} />
                <p className={text.subtitle2}>
                  {t('retail-landing.feature_desc3')}
                </p>
                <ScrollAnimation
                  animateOnce
                  offset={100}
                  animateIn="fadeInUpShort"
                  duration={0.5}
                  delay={500}
                >
                  <Paper className={classes.video}>
                    <img src={imgAPI.retail[27]} alt="screen" />
                    <IconButton className={classes.button} onClick={handleClickOpen} size="large">
                      <i className="ion-play" />
                    </IconButton>
                  </Paper>
                </ScrollAnimation>
              </Grid>
            </Grid>
          </Container>
        </div>
      </Container>
    </div>
  );
}

export default Feature;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/Home/Feature/Feature.vue
<template>
  <div class="root">
    <v-dialog
      v-model="dialog"
      max-width="690"
    >
      <v-card class="video-popup">
        <v-card-title class="headline mb-3 d-flex justify-space-between">
          <h4 class="use-text-subtitle">
            {{ $t('retail.banner_title') }}
          </h4>
          <v-btn icon @click="handleVideoClose()">
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </v-card-title>
        <div v-if="yt.use" class="text-center">
          <YouTube
            ref="youtube"
            :src="videoId"
            :vars="playerVars"
            :width="640"
            :height="360"
            class="youtube"
            @ready="onReady"
          />
        </div>
      </v-card>
    </v-dialog>
    <v-container :class="{ fixed: isDesktop }">
      <title-main align="center">
        {{ $t('retail.feature_title') }}
      </title-main>
      <div>
        <div class="item">
          <v-row align="center" justify="center" :class="[isMobile ? 'column-reverse' : 'row']">
            <v-col cols="12" md="4" class="px-8">
              <div
                data-aos="fade-left"
                data-aos-offset="400"
                data-aos-duration="500"
              >
                <div class="illustration">
                  <div class="bg pipe1" />
                  <figure class="screen1 mobile-screen">
                    <img
                      :src="imgAPI.retail[25]"
                      alt="screen"
                    >
                  </figure>
                  <figure class="graphic artwork1">
                    <img
                      :src="imgAPI.retail[10]"
                      :data-2d="imgAPI.retail[9]"
                      :data-3d="imgAPI.retail[10]"
                      class="img-2d3d"
                      alt="illustration"
                    >
                  </figure>
                </div>
              </div>
            </v-col>
            <v-col md="6" cols="12" class="px-8">
              <div class="desc">
                <title-secondary
                  :text="$t('retail.feature_title1')"
                  :align="isMobile ? 'center' : 'left'"
                />
                <p class="use-text-subtitle2" :class="[isMobile ? 'text-center' : 'text-start']">
                  {{ $t('retail.feature_desc1') }}
                </p>
              </div>
            </v-col>
          </v-row>
        </div>
        <div class="item">
          <v-row align="center">
            <v-col md="6" cols="12" class="px-8">
              <div class="desc">
                <title-secondary
                  :text="$t('retail.feature_title2')"
                  :align="isMobile ? 'center' : 'right'"
                />
                <p class="use-text-subtitle2" :class="[isMobile ? 'text-center' : 'text-end']">
                  {{ $t('retail.feature_desc2') }}
                </p>
              </div>
            </v-col>
            <v-col md="6" cols="12" class="px-sm-15">
              <div
                data-aos="fade-right"
                data-aos-offset="200"
                data-aos-delay="500"
                data-aos-duration="500"
              >
                <div class="illustration">
                  <div class="bg pipe2" />
                  <figure class="screen2 desktop-screen">
                    <img
                      :src="imgAPI.retail[26]"
                      alt="screen"
                    >
                  </figure>
                  <figure class="graphic artwork2">
                    <img
                      :src="imgAPI.retail[12]"
                      :data-2d="imgAPI.retail[11]"
                      :data-3d="imgAPI.retail[12]"
                      class="img-2d3d"
                      alt="illustration"
                    >
                  </figure>
                </div>
              </div>
            </v-col>
          </v-row>
        </div>
        <div class="item last">
          <v-container>
            <v-row justify="center">
              <v-col md="8" cols="12" class="video-container">
                <div class="bg pipe3" />
                <div class="bg pipe4" />
                <title-secondary
                  :text="$t('retail.feature_title3')"
                  align="center"
                />
                <p class="use-text-subtitle2 text-center">
                  {{ $t('retail.feature_desc3') }}
                </p>
                <div
                  data-aos-offset="100"
                  data-aos="fade-up"
                  data-aos-delay="500"
                  data-aos-duration="500"
                >
                  <v-card class="video">
                    <img :src="imgAPI.retail[27]" alt="screen">
                    <v-btn icon :size="isMobile ? 'small' : 'large'" color="primary" class="button" @click="handleVideoOpen()">
                      <i class="ion-md-play" />
                    </v-btn>
                  </v-card>
                </div>
              </v-col>
            </v-row>
          </v-container>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './feature-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import youtube from '@/config/youtube';
import Title from '../../Title';
import TitleSecondary from '../../Title/TitleSecondary';

export default {
  components: {
    TitleSecondary,
    'title-main': Title,
  },
  data() {
    return {
      videoId: 'MltGO66gTbo',
      imgAPI,
      dialog: false,
      player: null,
      playerVars: {
        autoplay: 0,
        controls: 1,
        rel: 0,
        showinfo: 1,
        mute: 0,
        origin: 'https://localhost:8006',
      },
      yt: youtube,
    };
  },
  computed: {
    isDesktop() {
      const lgUp = this.$vuetify.display.lgAndUp;
      return lgUp;
    },
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
  methods: {
    handleVideoOpen() {
      if (this.yt.use) {
        this.dialog = true;
      }
    },
    onReady() {
      this.$refs.youtube.playVideo();
    },
    handleVideoClose() {
      this.dialog = false;
      this.$refs.youtube.pauseVideo();
    },
  },
};
</script>
