// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/CallAction/CallAction.vue
<template>
  <v-container class="root max-md" :class="{ 'fixed-width': mdUp, 'home': home }">
    <div
      data-aos="fade-up"
      data-aos-offset="-100"
      data-aos-delay="500"
      data-aosduration="500"
    >
      <v-card class="paper">
        <div class="deco" />
        <h4 class="use-text-title2 mb-10">
          {{ $t('cloud.footer_waiting') }}
        </h4>
        <v-btn
          :href="link.cloud.contact"
          size="large"
          color="secondary"
          class="button"
        >
          {{ $t('cloud.getstarted') }}
        </v-btn>
      </v-card>
    </div>
  </v-container>
</template>

<style lang="scss" scoped>
@import './action-style.scss';
</style>

<script>
import AOS from 'aos';
import link from '@/assets/text/link';

export default {
  props: {
    home: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      link,
    };
  },
  computed: {
    mdUp() {
      const mdUp = this.$vuetify.display.mdAndUp;
      return mdUp;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/saas-theme/components/CallAction/CallAction.js
import React from 'react';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import { useTheme } from '@mui/material/styles';
import useMediaQuery from '@mui/material/useMediaQuery';
import Container from '@mui/material/Container';
import Paper from '@mui/material/Paper';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import { useTranslation } from 'next-i18next';
import link from '~/public/text/link';
import useStyles from './action-style';

function CallAction() {
  // Translation Function
  const { t } = useTranslation('common');
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('md'));

  const { classes } = useStyles();
  return (
    <Container maxWidth="md" fixed={isDesktop}>
      <div className={classes.root}>
        <ScrollAnimation animateOnce animateIn="fadeInUpShort" offset={-100} delay={500} duration={0.5}>
          <Paper className={classes.paper}>
            <div className={classes.deco} />
            <Box mb={5}>
              <Typography variant="h4" gutterBottom display="block">
                {t('saas-landing.footer_waiting')}
              </Typography>
            </Box>
            <Button size="large" variant="contained" color="secondary" href={link.saas.contact} className={classes.button}>
              {t('saas-landing.getstarted')}
            </Button>
          </Paper>
        </ScrollAnimation>
      </div>
    </Container>
  );
}

export default CallAction;
