// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Footer/FooterExtend.js
import React from 'react';
import PropTypes from 'prop-types';
import Button from '@mui/material/Button';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import Counter from '../CounterSingle';
import useStyles from './footer-extend-style';

function FooterExtend(props) {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { withCounter, children } = props;
  const { t } = useTranslation('common');
  return (
    <div className={cx(classes.footerCounter, withCounter ? classes.extend : '')}>
      <span className={classes.deco} />
      {withCounter && (
        <div>
          <Counter />
          <div className={classes.action}>
            <h4 className={text.title2}>
              {t('about_ready')}
            </h4>
            <Button color="secondary" size="large" variant="contained">
              {t('crypto-landing.getstarted')}
            </Button>
          </div>
        </div>
      )}
      {children}
    </div>
  );
}

FooterExtend.propTypes = {
  withCounter: PropTypes.bool,
  children: PropTypes.node.isRequired,

};

FooterExtend.defaultProps = {
  withCounter: false
};

export default FooterExtend;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Footer/FooterExtend.vue
<template>
  <div class="footer-counter" :class="{ extend: withCounter }">
    <span class="deco" />
    <div v-if="withCounter">
      <counter />
      <div class="action">
        <h4 class="use-text-title2">
          {{ $t('common.about_ready') }}
        </h4>
        <v-btn color="secondary" size="large">
          {{ $t('crypto.getstarted') }}
        </v-btn>
      </div>
    </div>
    <slot />
  </div>
</template>

<style lang="scss" scoped>
@import './footer-extend.scss';
</style>

<script>
import imgAPI from '@/assets/images/imgAPI';
import Counter from '../CounterSingle';

export default {
  components: {
    Counter,
  },
  props: {
    withCounter: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      imgAPI,
    };
  },
};
</script>
