// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Home/BannerSlider/BannerSlider.vue
<template>
  <div class="banner-wrap">
    <div class="root">
      <div class="banner-wrap">
        <div v-if="loaded" class="carousel">
          <splide
            ref="sliderBanner"
            class="slider"
            :options="slickOptions"
            @splide:active="handleAfterChange"
          >
            <splide-slide>
              <div id="slide1" class="slide">
                <div class="inner">
                  <div class="img background-banner">
                    <img
                      class="img-2d3d"
                      :src="imgAPI.crypto[3]"
                      :data-2d="imgAPI.crypto[2]"
                      :data-3d="imgAPI.crypto[3]"
                      alt="background"
                    >
                  </div>
                  <v-container>
                    <v-row>
                      <v-col md="6" cols="12" class="px-6 d-flex align-center">
                        <div class="text">
                          <div class="title title-left">
                            <h4 class="use-text-title2">
                              {{ $t('crypto.banner_title') }}
                            </h4>
                          </div>
                          <h5 class="use-text-subtitle2">
                            {{ $t('crypto.banner_subtitle') }}
                          </h5>
                          <div class="btn-area">
                            <v-btn
                              size="large"
                              color="primary"
                              :href="link.crypto.contact"
                              class="button"
                            >
                              {{ $t('common.btn_get') }}
                            </v-btn>
                            <v-btn
                              v-smooth-scroll
                              size="large"
                              color="primary"
                              variant="outlined"
                              href="#view-market"
                              class="button anchor-link scrollactive-item"
                            >
                              {{ $t('crypto.banner_viewmarket') }}
                            </v-btn>
                          </div>
                        </div>
                      </v-col>
                      <v-col md="6" cols="12">
                        <div class="img">
                          <img
                            class="img-2d3d img-slide1"
                            :src="imgAPI.crypto[5]"
                            :data-2d="imgAPI.crypto[4]"
                            :data-3d="imgAPI.crypto[5]"
                            alt="banner 1 3D"
                          >
                        </div>
                      </v-col>
                    </v-row>
                  </v-container>
                </div>
              </div>
            </splide-slide>
            <splide-slide>
              <div id="slide2" class="slide">
                <div class="inner">
                  <v-container>
                    <v-row justify="end" :class="[isMobile ? 'column-reverse' : 'row']">
                      <v-col md="6" cols="12" class="px-6">
                        <div class="img">
                          <img
                            class="img-2d3d img-slide2"
                            :src="imgAPI.crypto[7]"
                            :data-2d="imgAPI.crypto[6]"
                            :data-3d="imgAPI.crypto[7]"
                            alt="banner 2 3D"
                          >
                        </div>
                      </v-col>
                      <v-col md="6" cols="12" class="px-6 d-flex align-center">
                        <div class="text">
                          <div class="title title-left">
                            <h4 class="use-text-title2">
                              {{ $t('crypto.banner_title') }}
                            </h4>
                          </div>
                          <h5 class="use-text-subtitle2">
                            {{ $t('crypto.banner_subtitle') }}
                          </h5>
                          <div class="btn-area">
                            <v-btn
                              size="large"
                              color="primary"
                              :href="link.crypto.contact"
                              class="button"
                            >
                              {{ $t('common.btn_get') }}
                            </v-btn>
                            <v-btn
                              v-smooth-scroll
                              size="large"
                              color="primary"
                              variant="outlined"
                              href="#view-market"
                              class="button anchor-link scrollactive-item"
                            >
                              {{ $t('crypto.banner_viewmarket') }}
                            </v-btn>
                          </div>
                        </div>
                      </v-col>
                    </v-row>
                  </v-container>
                </div>
              </div>
            </splide-slide>
            <splide-slide>
              <div id="slide3" class="slide center-content">
                <div class="inner">
                  <v-container>
                    <v-row justify="end">
                      <v-col cols="12" class="px-sm-12">
                        <div class="text text-center">
                          <div class="title-wrap">
                            <div class="title title-center">
                              <h4 class="use-text-title2">
                                {{ $t('crypto.banner_title') }}
                              </h4>
                            </div>
                          </div>
                          <h5 class="use-text-subtitle2">
                            {{ $t('crypto.banner_subtitle') }}
                          </h5>
                          <div class="btn-area">
                            <v-btn
                              size="large"
                              color="primary"
                              :href="link.crypto.contact"
                              class="button"
                            >
                              {{ $t('common.btn_get') }}
                            </v-btn>
                            <v-btn
                              v-smooth-scroll
                              size="large"
                              color="primary"
                              variant="outlined"
                              href="#view-market"
                              class="button anchor-link scrollactive-item"
                            >
                              {{ $t('crypto.banner_viewmarket') }}
                            </v-btn>
                          </div>
                        </div>
                      </v-col>
                      <v-col cols="12">
                        <div class="img h-banner">
                          <img
                            class="img-2d3d"
                            :src="imgAPI.crypto[9]"
                            :data-2d="imgAPI.crypto[8]"
                            :data-3d="imgAPI.crypto[9]"
                            alt="banner 3 3D"
                          >
                        </div>
                      </v-col>
                    </v-row>
                  </v-container>
                </div>
              </div>
            </splide-slide>
          </splide>
        </div>
        <hidden point="smDown">
          <div class="slide-nav-group">
            <v-container>
              <nav class="slide-nav">
                <v-btn
                  :class="{ active: currentSlide === 0 }"
                  variant="text"
                  @click="gotoSlide(0)"
                >
                  <strong>First Slide</strong>
                  Interdum et malesuada fames ac ante
                </v-btn>
                <v-divider class="divider" vertical inset />
                <v-btn
                  :class="{ active: currentSlide === 1 }"
                  variant="text"
                  @click="gotoSlide(1)"
                >
                  <strong>Second Slide</strong>
                  Interdum et malesuada fames ac ante
                </v-btn>
                <v-divider class="divider" vertical inset />
                <v-btn
                  :class="{ active: currentSlide === 2 }"
                  variant="text"
                  @click="gotoSlide(2)"
                >
                  <strong>Third Slide</strong>
                  Interdum et malesuada fames ac ante
                </v-btn>
              </nav>
            </v-container>
          </div>
        </hidden>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './banner-styles';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import Hidden from '../../Hidden';
import link from '@/assets/text/link';
import imgAPI from '@/assets/images/imgAPI';

export default {
  components: {
    Hidden,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      currentSlide: 0,
      link,
      imgAPI,
      slickOptions: {
        pagination: false,
        arrows: false,
        speed: 800,
        perPage: 1,
        type: 'loop',
        autoplay: false,
        easing: 'ease',
        direction: 'ltr',
        reducedMotion: {
          speed: 1000,
          rewindSpeed: 1000,
        },
        breakpoints: {
          960: {
            pagination: true,
          },
        },
      },
    };
  },
  computed: {
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
      }
    }, 100);
  },
  methods: {
    handleAfterChange(slide) {
      this.currentSlide = slide.index;
    },
    gotoSlide(index) {
      this.$refs.sliderBanner.go(index);
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Home/BannerSlider/BannerSlider.js
import React, { useRef, useState } from 'react';
import AnchorLink from 'react-anchor-link-smooth-scroll';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Hidden from '@mui/material/Hidden';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import ButtonBase from '@mui/material/ButtonBase';
import Divider from '@mui/material/Divider';
import Carousel from 'react-slick';
import { useTranslation } from 'next-i18next';
import link from '~/public/text/link';
import imgAPI from '~/public/images/imgAPI';
import { useText, useTextAlign } from '~/theme/common';
import useStyles from './slider-style';

const LinkBtn = React.forwardRef(function LinkBtn(props, ref) { // eslint-disable-line
  return <AnchorLink to={props.to} {...props} />; // eslint-disable-line
});

function BannerSlider() {
  // Theme breakpoints
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const { t } = useTranslation('common');
  const slider = useRef(null);

  const [curSlide, setCurSlide] = useState(0);

  const slickOptions = {
    dots: false,
    arrows: false,
    speed: 800,
    slidesToShow: 1,
    infinite: true,
    autoplay: false,
    cssEase: 'ease-out',
    fade: isMobile,
    responsive: [
      {
        breakpoint: 960,
        settings: {
          dots: true,
        }
      }
    ]
  };

  const handleAfterChange = currentSlide => {
    setCurSlide(currentSlide);
  };

  const gotoSlide = slide => {
    slider.current.slickGoTo(slide);
  };

  return (
    <div className={classes.bannerWrap}>
      <div className={classes.root}>
        <div className={classes.bannerWrap}>
          <div className={classes.carousel}>
            <Carousel
              {...slickOptions}
              className={classes.slider}
              afterChange={handleAfterChange}
              ref={slider}
            >
              <div className={classes.slide}>
                <div className={classes.inner}>
                  <div className={cx(classes.img, classes.backgroundBanner)}>
                    <img
                      className="img-2d3d"
                      src={imgAPI.crypto[3]}
                      data-2d={imgAPI.crypto[2]}
                      data-3d={imgAPI.crypto[3]}
                      alt="background"
                    />
                  </div>
                  <Container>
                    <Grid container spacing={2} alignItems="center">
                      <Grid item md={6} lg={6} xs={12}>
                        <Box px={{ lg: 3 }} alignItems="center">
                          <div className={classes.text}>
                            <div className={classes.title}>
                              <h4 className={text.title2}>
                                {t('crypto-landing.banner_title')}
                              </h4>
                            </div>
                            <h5 className={text.subtitle2}>
                              {t('crypto-landing.banner_subtitle')}
                            </h5>
                            <div className={classes.btnArea}>
                              <Button size="large" variant="contained" color="primary" href={link.crypto.register} className={classes.button}>
                                {t('btn_get')}
                              </Button>
                              <Button size="large" variant="outlined" component={LinkBtn} color="primary" href="#view-market" className={classes.button}>
                                {t('crypto-landing.banner_viewmarket')}
                              </Button>
                            </div>
                          </div>
                        </Box>
                      </Grid>
                      <Grid item md={6} xs={12}>
                        <Box px={{ sm: 3 }}>
                          <div className={classes.img}>
                            <img
                              className={cx('img-2d3d', classes.imgSlide1)}
                              src={imgAPI.crypto[5]}
                              data-2d={imgAPI.crypto[4]}
                              data-3d={imgAPI.crypto[5]}
                              alt="banner 1 3D"
                            />
                          </div>
                        </Box>
                      </Grid>
                    </Grid>
                  </Container>
                </div>
              </div>
              <div className={classes.slide}>
                <div className={classes.inner}>
                  <Container>
                    <Grid container justifyContent="flex-end" alignItems="center" direction={isMobile ? 'column-reverse' : 'row'}>
                      <Grid item md={6} xs={12}>
                        <Box px={{ sm: 3 }}>
                          <div className={classes.img}>
                            <img
                              className={cx('img-2d3d', classes.imgSlide2)}
                              src={imgAPI.crypto[7]}
                              data-2d={imgAPI.crypto[6]}
                              data-3d={imgAPI.crypto[7]}
                              alt="banner 1 3D"
                            />
                          </div>
                        </Box>
                      </Grid>
                      <Grid item md={6} xs={12}>
                        <Box px={{ lg: 3 }} alignItems="center">
                          <div className={classes.text}>
                            <div className={classes.title}>
                              <h4 className={text.title2}>
                                {t('crypto-landing.banner_title')}
                              </h4>
                            </div>
                            <h5 className={text.subtitle2}>
                              {t('crypto-landing.banner_subtitle')}
                            </h5>
                            <div className={classes.btnArea}>
                              <Button size="large" variant="contained" color="primary" href={link.crypto.register} className={classes.button}>
                                {t('btn_get')}
                              </Button>
                              <Button size="large" variant="outlined" component={LinkBtn} color="primary" href="#view-market" className={classes.button}>
                                {t('crypto-landing.banner_viewmarket')}
                              </Button>
                            </div>
                          </div>
                        </Box>
                      </Grid>
                    </Grid>
                  </Container>
                </div>
              </div>
              <div className={cx(classes.slide, classes.centerContent)}>
                <div className={classes.inner}>
                  <Container>
                    <Grid container justifyContent="flex-end">
                      <Grid item md={12} xs={12}>
                        <Box px={{ sm: 12, xs: 0 }}>
                          <div className={cx(classes.text, align.textCenter)}>
                            <div className={classes.title}>
                              <h4 className={text.title2}>
                                {t('crypto-landing.banner_title')}
                              </h4>
                            </div>
                            <h5 className={text.subtitle2}>
                              {t('crypto-landing.banner_subtitle')}
                            </h5>
                            <div className={classes.btnArea}>
                              <Button size="large" variant="contained" color="primary" href={link.crypto.register} className={classes.button}>
                                {t('btn_get')}
                              </Button>
                              <Button size="large" variant="outlined" component={LinkBtn} color="primary" href="#view-market" className={classes.button}>
                                {t('crypto-landing.banner_viewmarket')}
                              </Button>
                            </div>
                          </div>
                        </Box>
                      </Grid>
                      <Grid item md={12} xs={12}>
                        <div className={cx(classes.img, classes.hBanner)}>
                          <img
                            className="img-2d3d"
                            src={imgAPI.crypto[9]}
                            data-2d={imgAPI.crypto[8]}
                            data-3d={imgAPI.crypto[9]}
                            alt="banner 3 3D"
                          />
                        </div>
                      </Grid>
                    </Grid>
                  </Container>
                </div>
              </div>
            </Carousel>
          </div>
        </div>
        <div className={classes.slideNavGroup}>
          <Hidden mdDown>
            <Container>
              <nav className={classes.slideNav}>
                <ButtonBase
                  className={cx(classes.btnNav, curSlide === 0 ? classes.active : '')}
                  onClick={() => gotoSlide(0)}
                >
                  <strong>First Slide</strong>
                  Interdum et malesuada fames ac ante
                </ButtonBase>
                <Divider className={classes.divider} orientation="vertical" flexItem />
                <ButtonBase
                  className={cx(classes.btnNav, curSlide === 1 ? classes.active : '')}
                  onClick={() => gotoSlide(1)}
                >
                  <strong>Second Slide</strong>
                  Interdum et malesuada fames ac ante
                </ButtonBase>
                <Divider className={classes.divider} orientation="vertical" flexItem />
                <ButtonBase
                  className={cx(classes.btnNav, curSlide === 2 ? classes.active : '')}
                  onClick={() => gotoSlide(2)}
                >
                  <strong>Third Slide</strong>
                  Interdum et malesuada fames ac ante
                </ButtonBase>
              </nav>
            </Container>
          </Hidden>
        </div>
      </div>
    </div>
  );
}

export default BannerSlider;
