// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Home/Feature/Feature.vue
<template>
  <div class="root">
    <div class="decoration-bg">
      <svg class="wave">
        <use xlink:href="/images/saas2/deco-bg.svg#main" />
      </svg>
    </div>
    <v-container :class="{ fixed: isDesktop }">
      <div>
        <div class="item">
          <v-row :class="[isMobile ? 'column-reverse' : 'row']">
            <v-col cols="12" md="6" class="px-md-5 px-lg-15">
              <div
                data-aos="fade-left"
                data-aos-offset="250"
                data-aos-duration="500"
              >
                <div class="screen-wrap">
                  <img
                    class="plant1 img-2d3d"
                    :src="imgAPI.saas2[10]"
                    :data-2d="imgAPI.saas2[9]"
                    :data-3d="imgAPI.saas2[10]"
                    alt="plant"
                  >
                  <div class="illustration">
                    <figure>
                      <img :src="imgAPI.saas2[19]" alt="screen">
                    </figure>
                  </div>
                </div>
              </div>
            </v-col>
            <v-col md="6" cols="12" class="px-md-5 px-lg-15">
              <div class="desc">
                <title-main :align="isMobile ? 'center' : 'left'">
                  <span>
                    {{ $t('saas2.feature_title1') }}
                    <strong>
                      {{ $t('saas2.feature_titlestrong1') }}
                    </strong>
                  </span>
                </title-main>
                <h6 class="use-text-subtitle2" :class="[isMobile ? 'text-center' : 'text-start']">
                  {{ $t('saas2.feature_desc1') }}
                </h6>
                <v-btn color="secondary" size="large" class="btn">
                  {{ $t('saas2.see_detail') }}
                </v-btn>
              </div>
            </v-col>
          </v-row>
        </div>
        <div class="item">
          <v-row>
            <v-col md="6" cols="12" class="px-md-5 px-lg-15">
              <div class="desc">
                <title-main :align="isMobile ? 'center' : 'right'">
                  <span>
                    {{ $t('saas2.feature_title1') }}
                    <strong>
                      {{ $t('saas2.feature_titlestrong2') }}
                    </strong>
                  </span>
                </title-main>
                <h6 class="use-text-subtitle2" :class="[isMobile ? 'text-center' : 'text-end']">
                  {{ $t('saas2.feature_desc2') }}
                </h6>
                <div :class="[isMobile ? 'text-center' : 'text-end']">
                  <v-btn color="secondary" size="large" class="btn">
                    {{ $t('saas2.see_detail') }}
                  </v-btn>
                </div>
              </div>
            </v-col>
            <v-col md="6" cols="12" class="px-md-5 px-lg-15">
              <div
                data-aos="fade-right"
                data-aos-offset="200"
                data-aos-duration="500"
              >
                <div class="screen-wrap">
                  <img
                    class="plant2 img-2d3d"
                    :src="imgAPI.saas2[12]"
                    :data-2d="imgAPI.saas2[11]"
                    :data-3d="imgAPI.saas2[12]"
                    alt="plant"
                  >
                  <div class="illustration">
                    <figure>
                      <img :src="imgAPI.saas2[20]" alt="screen">
                    </figure>
                  </div>
                </div>
              </div>
            </v-col>
          </v-row>
        </div>
        <div class="item last">
          <title-main align="center">
            <span>
              {{ $t('saas2.feature_title3') }}
              <strong>
                {{ $t('saas2.feature_titlestrong3') }}
              </strong>
            </span>
          </title-main>
          <v-row class="spacing6" justify="center">
            <v-col md="10" cols="12" class="pa-6">
              <h6 class="text-center use-text-subtitle2">
                {{ $t('saas2.feature_desc3') }}
              </h6>
              <div
                data-aos="fade-up"
                data-aos-offset="10"
                data-aos-duration="500"
              >
                <div class="screen-wrap">
                  <img
                    class="plant3 img-2d3d"
                    :src="imgAPI.saas2[14]"
                    :data-2d="imgAPI.saas2[13]"
                    :data-3d="imgAPI.saas2[14]"
                    alt="plant"
                  >
                  <div class="illustration screen-center">
                    <figure>
                      <img :src="imgAPI.saas2[21]" alt="screen">
                    </figure>
                  </div>
                </div>
              </div>
            </v-col>
          </v-row>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './feature-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';

export default {
  components: {
    'title-main': Title,
  },
  data() {
    return {
      imgAPI,
    };
  },
  computed: {
    isDesktop() {
      const lgUp = this.$vuetify.display.lgAndUp;
      return lgUp;
    },
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/saas-theme/components/Home/Feature/Feature.js
import React from 'react';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Button from '@mui/material/Button';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import { useTextAlign, useText } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Title from '../../Title';
import useStyles from './feature-style';

function Feature() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const theme = useTheme();

  const { t } = useTranslation('common');
  const isDesktop = useMediaQuery(theme.breakpoints.up('lg'));
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  return (
    <div className={classes.root}>
      <div className={classes.decoration}>
        <svg className={classes.wave}>
          <use xlinkHref="/images/saas/deco-bg.svg#main" />
        </svg>
      </div>
      <Container fixed={isDesktop}>
        <div className={classes.item}>
          <Grid container spacing={2} direction={isMobile ? 'column-reverse' : 'row'}>
            <Grid item md={6} xs={12}>
              <Box px={{ sm: 8 }}>
                <ScrollAnimation
                  animateOnce
                  animateIn="fadeInLeftShort"
                  offset={100}
                  delay={500}
                  duration={0.5}
                >
                  <div className={classes.illustrationLeft}>
                    <figure className={cx(classes.figure, classes.graphic)}>
                      <img
                        src={imgAPI.saas[10]}
                        data-2d={imgAPI.saas[9]}
                        data-3d={imgAPI.saas[10]}
                        className="img-2d3d"
                        alt="illustration"
                      />
                    </figure>
                  </div>
                </ScrollAnimation>
              </Box>
            </Grid>
            <Grid item md={6} xs={12}>
              <div className={classes.desc}>
                <Title align={isMobile ? 'center' : 'left'}>
                  <span>
                    {t('saas-landing.feature_title1')}
                    &nbsp;
                    <strong>
                      {t('saas-landing.feature_titlestrong1')}
                    </strong>
                  </span>
                </Title>
                <h6 className={cx(text.subtitle2, isMobile ? align.textCenter : align.textLeft)}>
                  {t('saas-landing.feature_desc1')}
                </h6>
                <Button variant="contained" color="secondary" size="large" className={classes.btn}>
                  {t('saas-landing.see_detail')}
                </Button>
              </div>
            </Grid>
          </Grid>
        </div>
        <div className={classes.item}>
          <Grid container spacing={2}>
            <Grid item md={6} xs={12}>
              <div>
                <Title align={isMobile ? 'center' : 'right'}>
                  <span>
                    {t('saas-landing.feature_title1')}
                    &nbsp;
                    <strong>
                      {t('saas-landing.feature_titlestrong2')}
                    </strong>
                  </span>
                </Title>
                <h6 className={cx(text.subtitle2, isMobile ? align.textCenter : align.textRight)}>
                  {t('saas-landing.feature_desc2')}
                </h6>
                <div className={isMobile ? align.textCenter : align.textRight}>
                  <Button variant="contained" color="secondary" size="large" className={classes.btn}>
                    {t('saas-landing.see_detail')}
                  </Button>
                </div>
              </div>
            </Grid>
            <Grid item md={6} xs={12}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInRightShort"
                offset={200}
                delay={500}
                duration={0.5}
              >
                <div className={classes.illustrationRight}>
                  <figure className={cx(classes.figure, classes.graphic)}>
                    <img
                      src={imgAPI.saas[12]}
                      data-2d={imgAPI.saas[11]}
                      data-3d={imgAPI.saas[12]}
                      className="img-2d3d"
                      alt="illustration"
                    />
                  </figure>
                </div>
              </ScrollAnimation>
            </Grid>
          </Grid>
        </div>
        <div className={cx(classes.item, classes.last)}>
          <Title align="center">
            {t('saas-landing.feature_title3')}
            &nbsp;
            <strong>
              {t('saas-landing.feature_titlestrong3')}
            </strong>
          </Title>
          <div className={classes.tab}>
            <Grid container justifyContent="center" spacing={6}>
              <Grid item md={10} xs={12}>
                <Box p={{ md: 6 }}>
                  <h6 className={cx(align.textCenter, text.subtitle2)}>
                    {t('saas-landing.feature_desc3')}
                  </h6>
                  <ScrollAnimation
                    animateOnce
                    animateIn="fadeInUpShort"
                    offset={10}
                    delay={500}
                    duration={0.5}
                  >
                    <div className={classes.illustrationCenter}>
                      <figure className={classes.graphic}>
                        <img
                          src={imgAPI.saas[14]}
                          data-2d={imgAPI.saas[13]}
                          data-3d={imgAPI.saas[14]}
                          className="img-2d3d"
                          alt="illustration"
                        />
                      </figure>
                    </div>
                  </ScrollAnimation>
                </Box>
              </Grid>
            </Grid>
          </div>
        </div>
      </Container>
    </div>
  );
}

export default Feature;
