// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/cloud-theme/components/Home/Promotion/Promotion.js
import React, { useRef } from 'react';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Carousel from 'react-slick';
import ButtonBase from '@mui/material/ButtonBase';
import Typography from '@mui/material/Typography';
import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import useStyles from './promotion-style';

const sliderData = [
  {
    icon: 'ion-cube',
    title: 'Wordpress Hosting start from $2/mo',
    desc:
      'Sed imperdiet enim ligula vitae viverra. Vivamus sit amet interdum elit.',
    date: '12 Jul - 10 Aug'
  },
  {
    icon: 'ion-ios-toggle',
    title: 'Dedicated VPS start from $5/mo',
    desc:
      'Sed imperdiet enim ligula vitae viverra. Vivamus sit amet interdum elit.',
    date: '12 Jul - 10 Aug'
  },
  {
    icon: 'ion-filing',
    title: '.COM + Hosting Only $15/mo',
    desc:
      'Sed imperdiet enim ligula vitae viverra. Vivamus sit amet interdum elit.',
    date: '12 Jul - 10 Aug'
  }
];

function Promotion() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { t } = useTranslation('common');
  const slider = useRef(null);

  const slickOptions = {
    dots: false,
    arrows: false,
    speed: 800,
    slidesToShow: 1,
    infinite: true,
    autoplay: true,
    autoplaySpeed: 10000,
    cssEase: 'ease-out',
    responsive: [
      {
        breakpoint: 800,
        settings: {
          dots: true
        }
      }
    ]
  };

  const prev = () => {
    slider.current.slickNext();
  };

  const next = () => {
    slider.current.slickPrev();
  };

  return (
    <div className={classes.root}>
      <div className={classes.nav}>
        <a
          href="#!"
          className={classes.prev}
          onClick={() => prev()}
        >
          <ArrowBackIosIcon />
        </a>
        <a
          href="#!"
          className={classes.next}
          onClick={() => next()}
        >
          <ArrowForwardIosIcon />
        </a>
      </div>
      <div className={classes.sliderWrap}>
        <Carousel
          {...slickOptions}
          className={cx(classes.slider, classes.slideContent)}
          ref={slider}
        >
          {sliderData.map((item, index) => (
            <div className={cx(classes.inner, classes.item)} key={index.toString()}>
              <Container>
                <Grid container spacing={2} justifyContent="center">
                  <Grid item md={3} sm={4} xs={12} className={classes.promoImage}>
                    <section>
                      <div className={classes.image}>
                        <span className={cx(classes.icon, item.icon)} />
                      </div>
                    </section>
                  </Grid>
                  <Grid item md={7} sm={8} xs={12}>
                    <div className={classes.text}>
                      <Typography variant="h1">
                        <ButtonBase>
                          {item.title}
                        </ButtonBase>
                      </Typography>
                      <p className={text.subtitle2}>
                        {item.desc}
                      </p>
                      <section className={classes.time}>
                        <Typography component="h6" className={text.caption}>
                          <span>
                            {t('cloud-landing.promo_periode')}
                            :&nbsp;
                            {item.date}
                          </span>
                        </Typography>
                      </section>
                    </div>
                  </Grid>
                </Grid>
              </Container>
            </div>
          ))}
        </Carousel>
      </div>
      <div className={classes.cloudTop}>
        <svg>
          <use xlinkHref="/images/cloud/cloud_top.svg#main" />
        </svg>
      </div>
      <div className={classes.cloudTopCover}>
        <svg>
          <use xlinkHref="/images/cloud/cloud_top.svg#main" />
        </svg>
      </div>
    </div>
  );
}

export default Promotion;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Promotion/Promotion.vue
<template>
  <div class="root">
    <div class="nav">
      <a
        href="javascript:void(0)"
        class="prev"
        @click="prev"
      >
        <v-icon>mdi-chevron-left</v-icon>
      </a>
      <a
        href="javascript:void(0)"
        class="next"
        @click="next"
      >
        <v-icon>mdi-chevron-right</v-icon>
      </a>
    </div>
    <div v-if="loaded" class="slider-wrap">
      <splide
        ref="slider"
        class="slide slider-content"
        :options="slickOptions"
      >
        <splide-slide
          v-for="(item, index) in contents"
          :key="index"
        >
          <div class="inner item">
            <v-container>
              <v-row justify="center">
                <v-col md="3" sm="4" cols="12" class="promo-image">
                  <section>
                    <div class="image">
                      <span class="icon" :class="item.icon" />
                    </div>
                  </section>
                </v-col>
                <v-col md="7" sm="8" cols="12">
                  <div class="text">
                    <h1>
                      <v-btn variant="text">
                        {{ item.title }}
                      </v-btn>
                    </h1>
                    <p class="use-text-subtitle2">
                      {{ item.desc }}
                    </p>
                    <section class="time">
                      <h6 class="use-text-caption">
                        <span>
                          {{ $t('cloud.promo_periode') }}
                          :&nbsp;
                          {{ item.date }}
                        </span>
                      </h6>
                    </section>
                  </div>
                </v-col>
              </v-row>
            </v-container>
          </div>
        </splide-slide>
      </splide>
    </div>
    <div class="cloud-top">
      <svg>
        <use xlink:href="/images/cloud/cloud_top.svg#main" />
      </svg>
    </div>
    <div class="cloud-top-cover">
      <svg>
        <use xlink:href="/images/cloud/cloud_top.svg#main" />
      </svg>
      <svg>
        <use xlink:href="/images/cloud/cloud_top.svg#main" />
      </svg>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './promotion-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';

const sliderData = [
  {
    icon: 'ion-md-cube',
    title: 'Wordpress Hosting start from $2/mo',
    desc:
      'Our managed WordPress hosting comes with ready-to-use features, so you can start building your website right away.',
    date: '12 Jul - 10 Aug',
  },
  {
    icon: 'ion-ios-switch',
    title: 'Dedicated VPS start from $5/mo',
    desc:
      'Get the power, flexibility and speed you need with our virtual private server hosting.',
    date: '12 Jul - 10 Aug',
  },
  {
    icon: 'ion-ios-folder-open',
    title: '.COM + Hosting Only $15/mo',
    desc:
      'Use our advanced domain name generator to get your ideal choice right away.',
    date: '12 Jul - 10 Aug',
  },
];

export default {
  components: {
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      contents: sliderData,
      slickOptions: {
        pagination: false,
        arrows: false,
        speed: 800,
        slidesToShow: 1,
        type: 'loop',
        autoplay: true,
        interval: 10000,
        easing: 'ease-out',
        direction: 'ltr',
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
        breakpoints: {
          800: {
            pagination: true,
          },
        },
      },
    };
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
      }
    }, 100);
  },
  methods: {
    next() {
      this.$refs.slider.go('>');
    },
    prev() {
      this.$refs.slider.go('<');
    },
  },
};
</script>
