// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/pages/[locale]/collection/products.js
import React, { Fragment, useState } from 'react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import Grid from '@mui/material/Grid';
import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import useMediaQuery from '@mui/material/useMediaQuery';
import AppBar from '@mui/material/AppBar';
import Dialog from '@mui/material/Dialog';
import Button from '@mui/material/Button';
import Toolbar from '@mui/material/Toolbar';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import CloseIcon from '@mui/icons-material/Close';
import Slide from '@mui/material/Slide';
// Use this below for Server Side Render/Translation (SSR)
// import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// Use this below for Static Site Generation (SSG)
import { getStaticPaths, makeStaticProps } from '~/lib/getStatic';
import products from '~/public/api/products';
import ProductCards from '~/components/Cards/ProductCard';
import Filter from '~/components/Filter/Filter';
import Sorter from '~/components/Filter/Sorter';
import Search from '~/components/Filter/Search';
import brand from '~/public/text/brand';
import { useSpacing } from '~/theme/common';
import link from '~/public/text/link';
import Header from '~/components/Header';
import Footer from '~/components/Footer';

const checkAll = [
  'check-a',
  'check-b',
  'check-c',
  'check-d',
  'check-e',
  'check-f'
];

const Transition = React.forwardRef(function Transition(props, ref) { // eslint-disable-line
  return <Slide direction="up" ref={ref} {...props} />;
});

function Products(props) {
  const { onToggleDark, onToggleDir } = props;

  const { classes, cx } = useSpacing();
  
  const isDesktop = useMediaQuery(theme => theme.breakpoints.up('md'));

  const [openFilter, setOpenFilter] = useState(false);

  const [toggleView, setView] = useState('grid');
  const [keyword, setKeyword] = useState('');
  const [category, setCategory] = useState('all');
  const [rating, setRating] = useState(0);
  const [radio, setRadio] = useState('all');
  const [check, setCheck] = useState(checkAll);
  const [range, setRange] = useState({
    from: 0,
    to: 100
  });
  const [tag, setTag] = useState(['tag-one', 'tag-two', 'tag-three', 'tag-four']);
  const [sortBySelected, setBySelected] = useState('');
  const [sortBy, setSortBy] = useState('');
  const [sortFrom, setFrom] = useState(-1);
  const [sortTo, setTo] = useState(1);

  const handleFilterOpen = () => {
    setOpenFilter(true);
  };

  const handleFilterClose = () => {
    setOpenFilter(false);
  };

  const handleGetRange = val => {
    setRange(val);
  };

  const handleSortBy = val => {
    setBySelected(val);
    switch (val) {
      case 'title-asc':
        setSortBy('title');
        setFrom(1);
        setTo(-1);
        break;
      case 'title-desc':
        setSortBy('title');
        setFrom(-1);
        setTo(1);
        break;
      case 'price-asc':
        setSortBy('price');
        setFrom(-1);
        setTo(1);
        break;
      default:
        setSortBy('price');
        setFrom(1);
        setTo(-1);
    }
  };

  const filteredItems = () => {
    // Compare same tag
    const intersection = (firstArray, secondArray) => firstArray
      .filter(element => secondArray.includes(element));

    // Check is all categories checked
    const checkFilter = (item, filterData) => {
      if (filterData !== 'all') {
        return item === filterData;
      }
      return true;
    };

    return products
      .filter(cardItem => checkFilter(cardItem.category, category)
        && checkFilter(cardItem.radio, radio)
        && cardItem.price >= range.from
        && cardItem.price <= range.to
        && cardItem.rating >= rating
        && check.indexOf(cardItem.check) > -1
        && intersection(tag, cardItem.tag).length > 0
      )
      .sort(
        (a, b) => {
          if (a[sortBy] > b[sortBy]) {
            return sortFrom;
          }
          return sortTo;
        }
      );
  };

  return (
    <Fragment>
      <Head>
        <title>
          { brand.crypto.name + ' - Product List' }
        </title>
      </Head>
      <CssBaseline />
      <Dialog fullScreen open={openFilter} onClose={handleFilterClose} TransitionComponent={Transition}>
        <AppBar>
          <Toolbar>
            <IconButton
              edge="start"
              color="inherit"
              onClick={handleFilterClose}
              aria-label="close"
              size="large"
            >
              <CloseIcon />
            </IconButton>
            <Typography variant="h6" sx={{ flex: 1 }}>
              Filter
            </Typography>
            <Button autoFocus color="inherit" onClick={handleFilterClose}>
              Done
            </Button>
          </Toolbar>
        </AppBar>
        <Container maxWidth="sm">
          <Box pt={10}>
            <Filter
              filterCategory={category}
              changeCategory={setCategory}
              filterRating={rating}
              changeRating={setRating}
              filterRadio={radio}
              changeRadio={setRadio}
              filterCheck={check}
              changeCheck={setCheck}
              checkAll={() => setCheck(checkAll)}
              changeRange={handleGetRange}
              filterTag={tag}
              changeTag={setTag}
            />
          </Box>
        </Container>
      </Dialog>
      <div className={classes.mainWrap}>
        <Header
          onToggleDark={onToggleDark}
          onToggleDir={onToggleDir}
        />
        <Search value={keyword} updateValue={setKeyword} />
        <div className={cx(classes.containerWrap, classes.containerFront)}>
          <section>
            <Container>
              <Sorter
                view={toggleView}
                resultLength={filteredItems().length}
                sortBySelected={sortBySelected}
                sortBy={handleSortBy}
                switchView={setView}
                openFilter={handleFilterOpen}
              />
            </Container>
            <Box my={2} mx={{ sm: 2 }}>
              <Grid container spacing={isDesktop ? 3 : 0}>
                {isDesktop && (
                  <Grid item md={3} lg={2}>
                    <Filter
                      filterCategory={category}
                      changeCategory={setCategory}
                      filterRating={rating}
                      changeRating={setRating}
                      filterRadio={radio}
                      changeRadio={setRadio}
                      filterCheck={check}
                      changeCheck={setCheck}
                      checkAll={() => setCheck(checkAll)}
                      changeRange={handleGetRange}
                      filterTag={tag}
                      changeTag={setTag}
                    />
                  </Grid>
                )}
                <Grid item lg={10} md={9}>
                  <Grid container justifyContent="center">
                    {filteredItems().length < 1 && (
                      <Grid item sm={12}>
                        <h3>Not found</h3>
                      </Grid>
                    )}
                    {filteredItems()
                      .map((item, index) => item.title.toLowerCase()
                        .indexOf(keyword) > -1 && (
                          <Grid
                            item
                            key={index.toString()}
                            lg={toggleView === 'grid' ? 4 : 12}
                            sm={toggleView === 'grid' ? 6 : 12}
                          >
                            <Box
                              display={toggleView === 'grid' ? 'flex' : 'block'}
                              justifyContent={toggleView === 'grid' ? 'center' : 'flex-start'}
                              mb={4}
                              px={2}
                            >
                              <ProductCards
                                rating={item.rating}
                                price={item.price}
                                title={item.title}
                                desc={`Category: ${item.category} ~ Tag: ${item.tag} ~ Check: ${item.check} ~ Radio: ${item.radio}`}
                                orientation={toggleView === 'grid' ? 'portrait' : 'landscape'}
                                img={item.img}
                                type="round"
                                href={link.crypto.productDetail}
                              />
                            </Box>
                          </Grid>
                      )
                    )}
                  </Grid>
                </Grid>
              </Grid>
            </Box>
          </section>
        </div>
        <Footer toggleDir={onToggleDir} />
      </div>
    </Fragment>
  );
}

Products.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

export default Products;

// Use this below for Server Side Render/Translation (SSR)
// export const getStaticProps = async ({ locale }) => ({ props: { ...await serverSideTranslations(locale, ['common']) } });

// Use this below for Static Site Generation (SSG)
const getStaticProps = makeStaticProps(['common']);
export { getStaticPaths, getStaticProps };

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/pages/collection/products.vue
<template>
  <div class="main-wrap">
    <main-header />
    <div class="container-wrap">
      <search v-model="keyword" @input="onInput" />
      <div class="search-content mt-15">
        <v-container>
          <sorter
            :view="toggleView"
            :sort-by-selected="sortBySelected"
            :result-length="filteredItems.length"
            @switch-view="handleToggleView"
            @sort-by="handleSortBy"
            @open-filter="handleOpenFilter"
          />
          <v-dialog
            v-model="dialog"
            fullscreen
            hide-overlay
            transition="dialog-bottom-transition"
          >
            <v-card>
              <v-toolbar
                dark
                color="primary"
                flat
                class="header-filter"
              >
                <v-btn
                  icon
                  dark
                  @click="dialog = false"
                >
                  <v-icon>mdi-close</v-icon>
                </v-btn>
                <v-toolbar-title>Filter</v-toolbar-title>
                <v-spacer />
                <v-toolbar-items>
                  <v-btn
                    dark
                    text
                    @click="dialog = false"
                  >
                    Done
                  </v-btn>
                </v-toolbar-items>
              </v-toolbar>
              <div class="pt-3">
                <filter-side
                  :filter-rating="filterRating"
                  :filter-category="filterCategory"
                  :filter-radio="filterRadio"
                  :filter-check="filterCheck"
                  :filter-tag="filterTag"
                  :handle-check-all="handleCheckAll"
                  @change-rating="handleRating"
                  @change-category="handleCategory"
                  @change-radio="handleRadio"
                  @change-check="handleCheck"
                  @change-range="handleRangeFilter"
                  @collect-tag="handleCollectTag"
                />
              </div>
            </v-card>
          </v-dialog>
          <v-row align="start" justify="start">
            <v-col class="pa-0 pa-md-3" lg="2" md="3" cols="12">
              <hidden point="smDown">
                <filter-side
                  :filter-rating="filterRating"
                  :filter-category="filterCategory"
                  :filter-radio="filterRadio"
                  :filter-check="filterCheck"
                  :filter-tag="filterTag"
                  :handle-check-all="handleCheckAll"
                  @change-rating="handleRating"
                  @change-category="handleCategory"
                  @change-radio="handleRadio"
                  @change-check="handleCheck"
                  @change-range="handleRangeFilter"
                  @collect-tag="handleCollectTag"
                />
              </hidden>
            </v-col>
            <v-col lg="10" md="9" cols="12">
              <v-row>
                <v-col v-if="filteredItems.length < 1" sm="12">
                  <h3>Not found</h3>
                </v-col>
                <template v-for="(item, index) in filteredItems" :key="index">
                  <v-col
                    v-if="item.title.toLowerCase().indexOf(keyword) > -1"
                    :sm="toggleView === 0 ? 4 : 12"
                    cols="12"
                    class="mb-5"
                  >
                    <div class="d-flex justify-center">
                      <card-products
                        :rating="item.rating"
                        :price="item.price"
                        :title="item.title"
                        :desc="'Category: '+item.category+' ~ '+'Tag: '+item.tag+' ~ '+'Check: '+item.check+' ~ '+'Radio: '+item.radio"
                        :orientation="toggleView === 0 ? 'portrait' : 'landscape'"
                        :img="item.img"
                        type="round"
                        :href="link.crypto.productDetail"
                      />
                    </div>
                  </v-col>
                </template>
              </v-row>
            </v-col>
          </v-row>
        </v-container>
      </div>
    </div>
    <main-footer />
  </div>
</template>

<style scoped lang="scss">
@import '@/assets/scss/pages';
</style>

<script>
import { ref } from 'vue';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Hidden from '@/components/Hidden';
import CardProducts from '@/components/Cards/ProductCard';
import Search from '@/components/Filter/Search';
import Sorter from '@/components/Filter/Sorter';
import Filter from '@/components/Filter/Filter';
import brand from '@/assets/text/brand';
import link from '@/assets/text/link';
import products from '@/assets/api/products';
import { defineNuxtComponent } from '#app';

const checkItems = [
  'check-a',
  'check-b',
  'check-c',
  'check-d',
  'check-e',
  'check-f',
];

export default defineNuxtComponent({
  setup() {
    const keyword = ref('');
    const onInput = event => {
      keyword.value = event.target.value;
    };

    return {
      keyword,
      onInput,
    };
  },
  components: {
    'main-header': Header,
    CardProducts,
    Search,
    Sorter,
    Hidden,
    'filter-side': Filter,
    'main-footer': Footer,
  },
  data() {
    return {
      link,
      dialog: false,
      sortBy: 'price',
      sortFrom: -1,
      sortTo: 1,
      toggleView: 0,
      filterRating: 0,
      filterCategory: 'all',
      filterRadio: 'all',
      filterCheck: checkItems,
      range: {
        from: 0,
        to: 100,
      },
      sortBySelected: {
        title: 'Highest Price',
        value: 'price-asc',
      },
      filterTag: ['tag-one', 'tag-two', 'tag-three', 'tag-four'],
      cardItems: products,
    };
  },
  methods: {
    handleOpenFilter() {
      this.dialog = true;
    },
    handleRating(val) {
      this.filterRating = val;
    },
    handleCategory(val) {
      this.filterCategory = val;
    },
    handleRadio(val) {
      this.filterRadio = val;
    },
    handleCheck(val) {
      this.filterCheck = val;
    },
    handleCheckAll() {
      this.filterCheck = checkItems;
    },
    handleRangeFilter(val) {
      this.range.from = val.from;
      this.range.to = val.to;
    },
    handleCollectTag(val) {
      this.filterTag = val;
    },
    handleToggleView(val) {
      this.toggleView = val;
    },
    handleSortBy(e) {
      switch (e.value) {
        case 'title-asc':
          this.sortBy = 'title';
          this.sortFrom = 1;
          this.sortTo = -1;
          break;
        case 'title-desc':
          this.sortBy = 'title';
          this.sortFrom = -1;
          this.sortTo = 1;
          break;
        case 'price-asc':
          this.sortBy = 'price';
          this.sortFrom = -1;
          this.sortTo = 1;
          break;
        default:
          this.sortBy = 'price';
          this.sortFrom = 1;
          this.sortTo = -1;
      }
    },
  },
  computed: {
    filteredItems() {
      // Compare same tag
      const intersection = (firstArray, secondArray) => firstArray.filter(element => secondArray.includes(element));

      // Check is all categories checked
      const checkFilter = (item, filterData) => {
        if (filterData !== 'all') {
          return item === filterData;
        }
        return true;
      };

      return this.cardItems
        .filter(cardItem => (
          checkFilter(cardItem.category, this.filterCategory)
            && checkFilter(cardItem.radio, this.filterRadio)
            && cardItem.price >= this.range.from
            && cardItem.price <= this.range.to
            && cardItem.rating >= this.filterRating
            && this.filterCheck.indexOf(cardItem.check) > -1
            && intersection(this.filterTag, cardItem.tag).length > 0
        ))
        .sort(
          (a, b) => (a[this.sortBy] > b[this.sortBy] ? this.sortFrom : this.sortTo),
        );
    },
  },
  head() {
    return {
      title: brand.crypto.name + ' - Product List',
    };
  },
});
</script>
