// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/saas2-theme/components/Home/NewsEvent/NewsEvent.js
import React, { useRef } from 'react';
import Carousel from 'react-slick';
import NewsCard from '../../Cards/NewsEventCard';
import imgAPI from '~/public/images/imgAPI';
import useStyles from './news-event-style';

const newsContent = [
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[1],
    type: 'caption_news',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[2],
    type: 'caption_news',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[3],
    type: 'caption_event',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[4],
    type: 'caption_news',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[5],
    type: 'caption_event',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[6],
    type: 'caption_news',
  },
];

const settings = {
  dots: true,
  infinite: true,
  speed: 500,
  slidesToShow: 2,
  arrows: false,
  autoplay: true,
  autoplaySpeed: 5000,
  slidesToScroll: 1,
  responsive: [{
    breakpoint: 700,
    settings: {
      slidesToShow: 1,
      slidesToScroll: 1
    }
  }]
};

function NewsEvent() {
  const slider = useRef(null);
  const { classes } = useStyles();
  return (
    <div className={classes.root}>
      <div className={classes.carousel}>
        <Carousel ref={slider} {...settings}>
          {newsContent.map((item, index) => (
            <div key={index.toString()}>
              <div className={classes.item}>
                <NewsCard
                  img={item.img}
                  text={item.text}
                  type={item.type}
                />
              </div>
            </div>
          ))}
        </Carousel>
      </div>
    </div>
  );
}

export default NewsEvent;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Home/NewsEvent/NewsEvent.vue
<template>
  <div class="root">
    <div v-if="loaded" class="carousel">
      <splide :options="settings">
        <splide-slide
          v-for="(item, index) in newsContent"
          :key="index"
        >
          <div class="item">
            <news-card
              :img="item.img"
              :text="item.text"
              :type="item.type"
            />
          </div>
        </splide-slide>
      </splide>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './news-event-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import imgAPI from '@/assets/images/imgAPI';
import NewsCard from '../../Cards/NewsEventCard';

const newsContent = [
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[1],
    type: 'caption_news',
  },
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[2],
    type: 'caption_news',
  },
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[3],
    type: 'caption_event',
  },
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[4],
    type: 'caption_news',
  },
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[5],
    type: 'caption_event',
  },
  {
    text:
      'Sed imperdiet enim ligula, vitae viverra justo porta vel. Duis eget felis bibendum, pretium mi sed, placerat ante.',
    img: imgAPI.photo[6],
    type: 'caption_news',
  },
];

export default {
  components: {
    NewsCard,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      newsContent,
      settings: {
        pagination: true,
        type: 'loop',
        speed: 500,
        perPage: 2,
        arrows: false,
        autoplay: true,
        interval: 5000,
        direction: 'ltr',
        perMove: 1,
        reducedMotion: {
          autoplay: true,
          speed: 1000,
          rewindSpeed: 1000,
        },
        breakpoints: {
          700: {
            perPage: 1,
            perMove: 1,
          },
        },
      },
    };
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.settings.direction = 'rtl';
      } else {
        this.settings.direction = 'ltr';
      }
    }, 100);
  },
};
</script>
