// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas2-theme/components/Home/Integration/Integration.js
import React from 'react';
import Container from '@mui/material/Container';
import Icon from '@mui/material/Icon';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import { useText, useTextAlign } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import useStyles from './integration-style';
import Title from '../../Title';

const integration1 = [
  {
    icon: 'search',
    title: 'Vestibulum a massa'
  },
  {
    icon: 'shuffle',
    title: 'Interdum et malesuada'
  },
  {
    icon: 'layers',
    title: 'Cras convallis lacus orci'
  },
  {
    icon: 'rss_feed',
    title: 'Nulla vehicula'
  },
  {
    icon: 'speed',
    title: 'Interdum et malesuada'
  },
  {
    icon: 'thumb_up',
    title: 'Cras convallis lacus orci'
  },
  {
    icon: 'cloud_upload',
    title: 'Donec sit amet nulla'
  },
  {
    icon: 'build',
    title: 'Donec sit amet nulla'
  }
];

const integration2 = [
  {
    icon: 'router',
    title: 'Vestibulum a massa'
  },
  {
    icon: 'shuffle',
    title: 'Interdum et malesuada'
  },
  {
    icon: 'equalizer',
    title: 'Cras convallis lacus orci'
  },
  {
    icon: 'add_circle',
    title: 'Nulla vehicula'
  },
  {
    icon: 'pie_chart',
    title: 'Interdum et malesuada'
  },
  {
    icon: 'supervisor_account',
    title: 'Cras convallis lacus orci'
  },
  {
    icon: 'merge_type',
    title: 'Donec sit amet nulla'
  },
  {
    icon: 'sync',
    title: 'Donec sit amet nulla'
  }
];

function Intergration() {
  const { classes, cx } = useStyles();
  const { t } = useTranslation('common');

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const isDesktop = useMediaQuery(theme.breakpoints.up('sm'));

  const { classes: text } = useText();
  const { classes: align } = useTextAlign();

  return (
    <div className={classes.root}>
      <div className={classes.decorationBg}>
        <svg className={classes.wave}>
          <use xlinkHref="/images/saas2/deco-bg2.svg#main" />
        </svg>
      </div>
      <Container>
        <Grid container className={classes.row} spacing={6} justifyContent="center">
          <Grid item lg={9} xs={12}>
            <Box py={{ lg: 6 }} px={{ sm: 6 }}>
              <Title align="center">
                <span>
                  {t('saas2-landing.feature_title1')}
                  <strong>
                    {t('saas2-landing.feature_titlestrong1')}
                  </strong>
                </span>
              </Title>
              <h6 className={cx(align.textCenter, text.subtitle2)}>
                {t('saas2-landing.feature_desc3')}
              </h6>
              <div className={classes.list}>
                <Box mb={{ xs: 0, md: 15 }}>
                  <Grid container spacing={3} className={classes.row}>
                    <Grid item sm={6} xs={12}>
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInUpShort"
                        offset={-100}
                        delay={500}
                        duration={0.5}
                      >
                        <div className={isDesktop ? align.textRight : align.textCenter}>
                          <figure className={cx(classes.illustration, classes.left)}>
                            <img
                              className="img-2d3d"
                              src={imgAPI.saas2[16]}
                              data-2d={imgAPI.saas2[15]}
                              data-3d={imgAPI.saas2[16]}
                              alt="background"
                            />
                          </figure>
                          <h3 className={cx(text.textPrimary, text.subtitle)}>
                            Ut sed eros finibus
                          </h3>
                          <p className={text.subtitle2}>
                            Quisque a consequat ante, at volutpat enim. Aenean sit amet magna vel magna fringilla fermentum.
                          </p>
                        </div>
                      </ScrollAnimation>
                    </Grid>
                    <Grid item sm={6} xs={12}>
                      <Box px={{ sm: 4 }}>
                        <ScrollAnimation
                          animateOnce
                          animateIn="fadeInUpShort"
                          offset={-100}
                          delay={800}
                          duration={0.5}
                        >
                          <div>
                            <ul className={classes.listPrimary}>
                              {integration1.map((item, index) => (
                                <li key={index.toString()}>
                                  <Icon className={classes.icon}>{item.icon}</Icon>
                                  {item.title}
                                </li>
                              ))}
                            </ul>
                          </div>
                        </ScrollAnimation>
                      </Box>
                    </Grid>
                  </Grid>
                </Box>
                <Grid container className={classes.row} direction={isMobile ? 'column-reverse' : 'row'}>
                  <Grid item sm={6} xs={12}>
                    <Box px={{ sm: 4 }}>
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInUpShort"
                        offset={-100}
                        delay={800}
                        duration={0.5}
                      >
                        <div>
                          <ul className={classes.listSecondary}>
                            {integration2.map((item, index) => (
                              <li key={index.toString()}>
                                {item.title}
                                <Icon className={classes.icon}>{item.icon}</Icon>
                              </li>
                            ))}
                          </ul>
                        </div>
                      </ScrollAnimation>
                    </Box>
                  </Grid>
                  <Grid item sm={6} xs={12}>
                    <Box px={{ sm: 4 }}>
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInUpShort"
                        offset={-100}
                        delay={500}
                        duration={0.5}
                      >
                        <div className={isDesktop ? align.textLeft : align.textCenter}>
                          <figure className={classes.illustration}>
                            <img
                              className="img-2d3d"
                              src={imgAPI.saas2[18]}
                              data-2d={imgAPI.saas2[17]}
                              data-3d={imgAPI.saas2[18]}
                              alt="background"
                            />
                          </figure>
                          <h3 className={cx(text.textSecondary, text.subtitle)}>
                            Ut sed eros finibus
                          </h3>
                          <p className={text.subtitle2}>
                            Quisque a consequat ante, at volutpat enim. Aenean sit amet magna vel magna fringilla fermentum.
                          </p>
                        </div>
                      </ScrollAnimation>
                    </Box>
                  </Grid>
                </Grid>
              </div>
            </Box>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

Intergration.propTypes = {

};

export default Intergration;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Home/Integration/Integration.vue
<template>
  <div class="root">
    <div class="decoration-bg">
      <svg class="wave">
        <use xlink:href="/images/saas2/deco-bg2.svg#main" />
      </svg>
    </div>
    <v-container>
      <v-row class="spacing6" justify="center">
        <v-col lg="9" cols="12" class="py-0 py-sm-6 px-6">
          <title-main align="center">
            <span>
              {{ $t('saas2.feature_title1') }}
              <strong>
                {{ $t('saas2.feature_titlestrong1') }}
              </strong>
            </span>
          </title-main>
          <h6 class="text-center use-text-subtitle2">
            {{ $t('saas2.feature_desc3') }}
          </h6>
          <div class="list">
            <div>
              <v-row class="mb-sm-15">
                <v-col
                  sm="6"
                  cols="12"
                  class="px-sm-8"
                >
                  <div
                    data-aos-offset="-100"
                    data-aos="fade-up"
                    data-aos-delay="500"
                    data-aos-duration="500"
                  >
                    <div class="text-sm-end text-center">
                      <figure class="illustration left">
                        <img
                          class="img-2d3d"
                          :src="imgAPI.saas2[16]"
                          :data-2d="imgAPI.saas2[15]"
                          :data-3d="imgAPI.saas2[16]"
                          alt="background"
                        >
                      </figure>
                      <h3 class="use-text-primary use-text-subtitle">
                        Ut sed eros finibus
                      </h3>
                      <p class="use-text-subtitle2">
                        Quisque a consequat ante, at volutpat enim. Aenean sit amet magna vel magna fringilla fermentum.
                      </p>
                    </div>
                  </div>
                </v-col>
                <v-col
                  sm="6"
                  cols="12"
                  class="px-sm-8"
                >
                  <div
                    data-aos="fade-in"
                    data-aos-offset="-100"
                    data-aos-delay="800"
                    data-aos-duration="500"
                  >
                    <div>
                      <ul class="list-primary">
                        <li v-for="(item, index) in integration1" :key="index">
                          <v-icon>{{ item.icon }}</v-icon>
                          {{ item.title }}
                        </li>
                      </ul>
                    </div>
                  </div>
                </v-col>
              </v-row>
              <v-row :class="[isMobile ? 'column-reverse' : 'row']">
                <v-col
                  sm="6"
                  cols="12"
                  class="px-sm-8"
                >
                  <div
                    data-aos="fade-in"
                    data-aos-offset="-100"
                    data-aos-delay="800"
                    data-aos-duration="500"
                  >
                    <div>
                      <ul class="list-secondary">
                        <li v-for="(item, index) in integration2" :key="index">
                          {{ item.title }}
                          <v-icon>{{ item.icon }}</v-icon>
                        </li>
                      </ul>
                    </div>
                  </div>
                </v-col>
                <v-col
                  sm="6"
                  cols="12"
                  class="px-sm-8"
                >
                  <div
                    data-aos="fade-up"
                    data-aos-offset="-100"
                    data-aos-delay="500"
                    data-aos-duration="500"
                  >
                    <div class="text-sm-start text-center">
                      <figure class="illustration">
                        <img
                          class="img-2d3d"
                          :src="imgAPI.saas2[18]"
                          :data-2d="imgAPI.saas2[17]"
                          :data-3d="imgAPI.saas2[18]"
                          alt="background"
                        >
                      </figure>
                      <h3 class="use-text-secondary use-text-subtitle">
                        Ut sed eros finibus
                      </h3>
                      <p class="use-text-subtitle2">
                        Quisque a consequat ante, at volutpat enim. Aenean sit amet magna vel magna fringilla fermentum.
                      </p>
                    </div>
                  </div>
                </v-col>
              </v-row>
            </div>
          </div>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import 'integration-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';

export default {
  components: {
    'title-main': Title,
  },
  data() {
    return {
      imgAPI,
      integration1: [
        {
          icon: 'mdi-magnify',
          title: 'Vestibulum a massa',
        },
        {
          icon: 'mdi-shuffle-variant',
          title: 'Interdum et malesuada',
        },
        {
          icon: 'mdi-layers',
          title: 'Cras convallis lacus orci',
        },
        {
          icon: 'mdi-rss',
          title: 'Nulla vehicula',
        },
        {
          icon: 'mdi-speedometer',
          title: 'Interdum et malesuada',
        },
        {
          icon: 'mdi-thumb-up',
          title: 'Cras convallis lacus orci',
        },
        {
          icon: 'mdi-cloud-upload',
          title: 'Donec sit amet nulla',
        },
        {
          icon: 'mdi-wrench',
          title: 'Donec sit amet nulla',
        },
      ],
      integration2: [
        {
          icon: 'mdi-access-point',
          title: 'Vestibulum a massa',
        },
        {
          icon: 'mdi-shuffle-variant',
          title: 'Interdum et malesuada',
        },
        {
          icon: 'mdi-poll',
          title: 'Cras convallis lacus orci',
        },
        {
          icon: 'mdi-plus-circle',
          title: 'Nulla vehicula',
        },
        {
          icon: 'mdi-chart-pie',
          title: 'Interdum et malesuada',
        },
        {
          icon: 'mdi-account-multiple',
          title: 'Cras convallis lacus orci',
        },
        {
          icon: 'mdi-source-merge',
          title: 'Donec sit amet nulla',
        },
        {
          icon: 'mdi-sync',
          title: 'Donec sit amet nulla',
        },
      ],
    };
  },
  computed: {
    isMobile() {
      const xsDown = this.$vuetify.display.xs;
      return xsDown;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>
