// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Cards/CoinCard.js
import React from 'react';
import PropTypes from 'prop-types';
import Avatar from '@mui/material/Avatar';
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import { useText } from '~/theme/common';
import useStyles from './coin-card-style';

function CoinCard(props) {
  const { classes } = useStyles();
  const { classes: text } = useText();
  const {
    logo,
    name,
    price,
    status,
    volume,
    percent,
  } = props;

  return (
    <Card className={classes.coin}>
      <div className={classes.header}>
        <Avatar className={classes.logo} src={logo} alt={name} />
        <div className={classes.name}>
          <h4>
            {name}
            &nbsp;
            <span>USD</span>
          </h4>
          <p>
            <i className="ion-flame" />
            Top Volume
          </p>
        </div>
      </div>
      <div className={classes.price}>
        <h3 className={text.title2}>
          $&nbsp;
          {price}
        </h3>
      </div>
      <div className={classes.property}>
        <Grid container>
          <Grid item xs={6}>
            {status === 'down' && (
              <span className={classes.down}>
                <i>▼</i>
                { percent}
                %
              </span>
            )}
            {status === 'up' && (
              <span className={classes.up}>
                <i>▲</i>
                { percent}
                %
              </span>
            )}
            {status === 'stay' && (
              <span className={classes.stay}>
                <i>▲</i>
                { percent}
                %
              </span>
            )}
            <p className={text.caption}>24h Change</p>
          </Grid>
          <Grid item xs={6}>
            {volume}
            <p className={text.caption}>24h Volume</p>
          </Grid>
        </Grid>
      </div>
    </Card>
  );
}

CoinCard.propTypes = {
  logo: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  price: PropTypes.number.isRequired,
  status: PropTypes.string.isRequired,
  volume: PropTypes.number.isRequired,
  percent: PropTypes.number.isRequired,
};

export default CoinCard;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Cards/CoinCard.vue
<template>
  <v-card class="coin">
    <div class="header">
      <v-avatar class="logo" height="70" width="70" min-width="70">
        <img :src="logo" :alt="name">
      </v-avatar>
      <div class="name">
        <h4>
          {{ name }}
          <span>USD</span>
        </h4>
        <p>
          <i class="ion-flame" />
          Top Volume
        </p>
      </div>
    </div>
    <div class="price">
      <h3 class="use-text-title2">
        $ {{ price }}
      </h3>
    </div>
    <div class="property">
      <v-row>
        <v-col xs="6" class="px-3 pb-3">
          <span v-if="status === 'down'" class="down">
            <i>▼</i>{{ percent }}%
          </span>
          <span v-if="status === 'up'" class="up">
            <i>▲</i>{{ percent }}%
          </span>
          <span v-if="status === 'stay'" class="stay">
            <i>-</i>{{ percent }}%
          </span>
          <p class="use-text-caption">
            24h Change
          </p>
        </v-col>
        <v-col xs="6" class="px-3 pb-3">
          {{ volume }}
          <p class="use-text-caption">
            24h Volume
          </p>
        </v-col>
      </v-row>
    </div>
  </v-card>
</template>

<style lang="scss" scoped>
@import './coin-card.scss';
</style>

<script>
export default {
  props: {
    logo: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      required: true,
    },
    volume: {
      type: Number,
      required: true,
    },
    percent: {
      type: Number,
      required: true,
    },
  },
};
</script>
