// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/components/Cards/NewsEventCard.js
import React from 'react';
import PropTypes from 'prop-types';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { useTranslation } from 'next-i18next';
import useStyles from './news-event-style';

function News(props) {
  const { classes } = useStyles();
  const { t } = useTranslation('common');
  const {
    text,
    img,
    type,
  } = props;

  return (
    <div className={classes.news}>
      <figure>
        <img src={img} alt="thumb" />
      </figure>
      <div className={classes.desc}>
        <div className={classes.text}>
          <Typography variant="caption" className={classes.type}>
            {t('crypto-landing.' + type)}
          </Typography>
          <Typography display="block" component="p">{text}</Typography>
        </div>
        <Button size="small" className={classes.btn}>
          {t('crypto-landing.news_readmore')}
        </Button>
      </div>
    </div>
  );
}

News.propTypes = {
  text: PropTypes.string.isRequired,
  img: PropTypes.string.isRequired,
  type: PropTypes.string.isRequired,

};

export default News;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Cards/NewsEventCard.vue
<template>
  <div class="news">
    <figure>
      <img :src="img" alt="thumb">
    </figure>
    <div class="desc">
      <div class="text">
        <p class="type caption">
          {{ $t('crypto.' + type) }}
        </p>
        <p>{{ text }}</p>
      </div>
      <v-btn size="small" variant="text" class="btn">
        {{ $t('crypto.news_readmore') }}
      </v-btn>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './news-event.scss';
</style>

<script>
export default {
  props: {
    text: {
      type: String,
      required: true,
    },
    img: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      required: true,
    },
  },
};
</script>
