// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/medical-theme/components/Home/BannerSlider/BannerSlider.js
import React, { useState, useEffect, useRef } from 'react';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Hidden from '@mui/material/Hidden';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import ButtonBase from '@mui/material/ButtonBase';
import Divider from '@mui/material/Divider';
import Carousel from 'react-slick';
import { useTranslation } from 'next-i18next';
import link from '~/public/text/link';
import imgAPI from '~/public/images/imgAPI';
import { useText, useTextAlign } from '~/theme/common';
import useStyles from './slider-style';

function BannerSlider() {
  // Theme breakpoints
  const theme = useTheme();
  const isTablet = useMediaQuery(theme.breakpoints.down('md'));

  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const { t } = useTranslation('common');
  const slider = useRef(null);
  const sliderDeco = useRef(null);
  const [deco, setDeco] = useState(null);

  const [curSlide, setCurSlide] = useState(0);

  const slickOptionsDeco = {
    dots: false,
    arrows: false,
    slidesToShow: 1,
    infinite: true,
    fade: true,
    cssEase: 'ease-out',
    autoplay: false
  };

  const slickOptions = {
    dots: false,
    arrows: false,
    speed: 800,
    slidesToShow: 1,
    infinite: true,
    autoplay: false,
    cssEase: 'ease-out',
    fade: isTablet,
    responsive: [
      {
        breakpoint: 960,
        settings: {
          dots: true,
        }
      }
    ]
  };

  const handleAfterChange = currentSlide => {
    setCurSlide(currentSlide);
  };

  const gotoSlide = slide => {
    slider.current.slickGoTo(slide);
  };

  useEffect(() => {
    setDeco(sliderDeco.current);
  }, []);

  return (
    <div className={classes.bannerWrap}>
      <div className={classes.carousel}>
        <Carousel
          className={classes.sliderDeco}
          {...slickOptionsDeco}
          ref={sliderDeco}
        >
          <div className={cx(classes.slide, curSlide === 0 ? classes.cur : '')}>
            <div className={classes.inner}>
              <div className={classes.decoWrap}>
                <div className={cx(classes.deco, classes.bottom, classes.s1)}>&nbsp;</div>
                <div className={cx(classes.deco, classes.top, classes.s1)}>&nbsp;</div>
              </div>
            </div>
          </div>
          <div className={cx(classes.slide, curSlide === 1 ? classes.cur : '')}>
            <div className={classes.inner}>
              <div className={classes.decoWrap}>
                <div className={cx(classes.deco, classes.bottom, classes.s2)}>&nbsp;</div>
                <div className={cx(classes.deco, classes.top, classes.s2)}>&nbsp;</div>
              </div>
            </div>
          </div>
          <div className={cx(classes.slide, curSlide === 2 ? classes.cur : '')}>
            <div className={classes.inner}>
              &nbsp;
            </div>
          </div>
        </Carousel>
        <Carousel
          className={classes.slider}
          {...slickOptions}
          ref={slider}
          asNavFor={deco}
          afterChange={handleAfterChange}
        >
          <div className={classes.slide} id="slide1">
            <div className={classes.inner}>
              <div className={cx(classes.img, classes.backgroundBanner)}>
                <img
                  className="img-2d3d"
                  src={imgAPI.medical[3]}
                  data-2d={imgAPI.medical[2]}
                  data-3d={imgAPI.medical[3]}
                  alt="background"
                />
              </div>
              <Container>
                <Grid container spacing={2} alignItems="center">
                  <Grid item md={7} lg={6} xs={12}>
                    <Box px={{ sm: 6 }} alignItems="center">
                      <div className={classes.text}>
                        <h4 className={text.title}>
                          {t('medical-landing.banner_title')}
                        </h4>
                        <h5 className={text.subtitle}>
                          {t('medical-landing.banner_subtitle')}
                        </h5>
                        <div className={classes.btnArea}>
                          <Button size="large" href="#" className={classes.btnText}>
                            {t('btn_detail')}
                          </Button>
                          <Button size="large" variant="contained" color="primary" href={link.medical.register} className={classes.button}>
                            {t('btn_get')}
                          </Button>
                        </div>
                      </div>
                    </Box>
                  </Grid>
                  <Grid item md={5} lg={6} xs={12}>
                    <div className={classes.img}>
                      <img
                        src={imgAPI.medical[5]}
                        className="img-2d3d"
                        data-2d={imgAPI.medical[4]}
                        data-3d={imgAPI.medical[5]}
                        alt="banner 1 3D"
                      />
                    </div>
                  </Grid>
                </Grid>
              </Container>
            </div>
          </div>
          <div className={classes.slide} id="slide2">
            <div className={classes.inner}>
              <Container>
                <Grid container spacing={2} justifyContent="flex-end" alignItems="center" direction={isTablet ? 'column-reverse' : 'row'}>
                  <Grid item md={5} xs={12}>
                    <div className={classes.img}>
                      <img
                        src={imgAPI.medical[7]}
                        className="img-2d3d"
                        data-2d={imgAPI.medical[6]}
                        data-3d={imgAPI.medical[7]}
                        alt="banner 2 3D"
                      />
                    </div>
                  </Grid>
                  <Grid item md={7} xs={12}>
                    <Box px={3} alignItems="center">
                      <div className={classes.text}>
                        <h4 className={text.title}>
                          {t('medical-landing.banner_title')}
                        </h4>
                        <h5 className={text.subtitle}>
                          {t('medical-landing.banner_subtitle')}
                        </h5>
                        <div className={classes.btnArea}>
                          <Button size="large" href="#" className={classes.btnText}>
                            {t('btn_detail')}
                          </Button>
                          <Button size="large" variant="contained" color="primary" href={link.medical.register} className={classes.button}>
                            {t('btn_get')}
                          </Button>
                        </div>
                      </div>
                    </Box>
                  </Grid>
                </Grid>
              </Container>
            </div>
          </div>
          <div className={cx(classes.slide, classes.centerContent)} id="slide3">
            <div className={classes.inner}>
              <Container>
                <Grid container spacing={2} justifyContent="flex-end">
                  <Grid item md={12} xs={12}>
                    <Box px={{ sm: 12 }}>
                      <div className={cx(classes.text, align.textCenter)}>
                        <h4 className={text.title}>
                          {t('medical-landing.banner_title')}
                        </h4>
                        <h5 className={text.subtitle}>
                          {t('medical-landing.banner_subtitle')}
                        </h5>
                        <div className={classes.btnArea}>
                          <Button size="large" href="#" className={classes.btnText}>
                            {t('btn_detail')}
                          </Button>
                          <Button size="large" variant="contained" color="primary" href={link.medical.register} className={classes.button}>
                            {t('btn_get')}
                          </Button>
                        </div>
                      </div>
                    </Box>
                  </Grid>
                  <Grid item md={12} xs={12}>
                    <div className={cx(classes.img, classes.hBanner)}>
                      <img
                        src={imgAPI.medical[9]}
                        className="img-2d3d"
                        data-2d={imgAPI.medical[8]}
                        data-3d={imgAPI.medical[9]}
                        alt="banner 3 3D"
                      />
                    </div>
                  </Grid>
                </Grid>
              </Container>
            </div>
          </div>
        </Carousel>
      </div>
      <Hidden mdDown>
        <Container maxWidth="md">
          <nav className={classes.slideNav}>
            <ButtonBase
              className={cx(classes.btnNav, curSlide === 0 ? classes.active : '')}
              onClick={() => gotoSlide(0)}
            >
              <strong>First Slide</strong>
              Interdum et malesuada fames ac ante
            </ButtonBase>
            <Divider className={classes.divider} orientation="vertical" flexItem />
            <ButtonBase
              className={cx(classes.btnNav, curSlide === 1 ? classes.active : '')}
              onClick={() => gotoSlide(1)}
            >
              <strong>Second Slide</strong>
              Interdum et malesuada fames ac ante
            </ButtonBase>
            <Divider className={classes.divider} orientation="vertical" flexItem />
            <ButtonBase
              className={cx(classes.btnNav, curSlide === 2 ? classes.active : '')}
              onClick={() => gotoSlide(2)}
            >
              <strong>Third Slide</strong>
              Interdum et malesuada fames ac ante
            </ButtonBase>
          </nav>
        </Container>
      </Hidden>
    </div>
  );
}

export default BannerSlider;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/social-apps-theme/components/Home/BannerSlider/BannerSlider.vue
<template>
  <div class="banner-wrap">
    <div v-if="loaded" class="carousel">
      <splide
        ref="sliderDeco"
        class="slider-deco"
        :options="slickOptionsDeco"
        @splide:move="handleSyncDeco"
      >
        <splide-slide>
          <div class="slide" :class="{ cur: currentSlide === 0 }">
            <div class="inner">
              <div class="deco-wrap">
                <div class="deco s1">
&nbsp;
                </div>
              </div>
            </div>
          </div>
        </splide-slide>
        <splide-slide>
          <div class="slide" :class="{ cur: currentSlide === 1 }">
            <div class="inner">
              <div class="deco-wrap">
                <div class="deco s2">
&nbsp;
                </div>
              </div>
            </div>
          </div>
        </splide-slide>
        <splide-slide>
          <div class="slide" :class="{ cur: currentSlide === 2 }">
            <div class="inner">
              &nbsp;
            </div>
          </div>
        </splide-slide>
      </splide>
    </div>
    <div v-if="loaded" class="carousel">
      <splide
        ref="sliderBanner"
        class="slider"
        :options="slickOptions"
        @splide:active="handleAfterChange"
        @splide:move="handleSyncBanner"
      >
        <splide-slide>
          <div id="slide1" class="slide">
            <div class="inner">
              <div class="img background-banner">
                <img
                  class="img-2d3d"
                  :src="imgAPI.social[5]"
                  :data-2d="imgAPI.social[4]"
                  :data-3d="imgAPI.social[5]"
                  alt="background"
                >
              </div>
              <v-container>
                <v-row>
                  <v-col lg="6" md="7" cols="12" class="px-sm-6 d-flex align-center">
                    <div class="text">
                      <h4 class="use-text-title">
                        {{ $t('social.banner_title') }}
                      </h4>
                      <h5 class="use-text-subtitle">
                        {{ $t('social.banner_desc') }}
                      </h5>
                      <div class="btn-area download">
                        <nuxt-link to="/">
                          <img src="/images/social/app-store.png" alt="app store">
                        </nuxt-link>
                        <nuxt-link to="/">
                          <img src="/images/social/play-store.png" alt="play store">
                        </nuxt-link>
                      </div>
                    </div>
                  </v-col>
                  <v-col lg="6" md="5" cols="12" class="px-lg-6">
                    <div class="img">
                      <img
                        class="img-2d3d img-slide1"
                        :src="imgAPI.social[1]"
                        :data-2d="imgAPI.social[0]"
                        :data-3d="imgAPI.social[1]"
                        alt="banner 1 3D"
                      >
                    </div>
                  </v-col>
                </v-row>
              </v-container>
            </div>
          </div>
        </splide-slide>
        <splide-slide>
          <div id="slide2" class="slide">
            <div class="inner">
              <v-container>
                <v-row justify="end" :class="[isMobile ? 'column-reverse' : 'row']">
                  <v-col lg="6" md="5" cols="12" class="px-lg-6">
                    <div class="img">
                      <img
                        class="img-2d3d img-slide2"
                        :src="imgAPI.social[3]"
                        :data-2d="imgAPI.social[2]"
                        :data-3d="imgAPI.social[3]"
                        alt="banner 2 3D"
                      >
                    </div>
                  </v-col>
                  <v-col lg="6" md="7" cols="12" class="px-sm-6 d-flex align-center">
                    <div class="text">
                      <h4 class="use-text-title">
                        {{ $t('social.banner_title') }}
                      </h4>
                      <h5 class="use-text-subtitle">
                        {{ $t('social.banner_desc') }}
                      </h5>
                      <div class="btn-area">
                        <v-btn
                          variant="text"
                          size="large"
                          color="primary"
                          href="#"
                          class="button"
                        >
                          {{ $t('common.btn_detail') }}
                        </v-btn>
                        <v-btn
                          size="large"
                          color="secondary"
                          :href="link.social.contact"
                          class="button"
                        >
                          {{ $t('common.btn_get') }}
                        </v-btn>
                      </div>
                    </div>
                  </v-col>
                </v-row>
              </v-container>
            </div>
          </div>
        </splide-slide>
        <splide-slide>
          <div id="slide3" class="slide center-content">
            <div class="inner">
              <v-container>
                <v-row justify="end">
                  <v-col cols="12" class="px-sm-12">
                    <div class="text text-center">
                      <h4 class="use-text-title">
                        {{ $t('social.banner_title') }}
                      </h4>
                      <h5 class="use-text-subtitle">
                        {{ $t('social.banner_desc') }}
                      </h5>
                      <div class="btn-area justify-center">
                        <v-btn
                          variant="text"
                          size="large"
                          color="primary"
                          href="#"
                          class="button"
                        >
                          {{ $t('common.btn_detail') }}
                        </v-btn>
                        <v-btn
                          size="large"
                          color="secondary"
                          :href="link.social.contact"
                          class="button"
                        >
                          {{ $t('common.btn_get') }}
                        </v-btn>
                      </div>
                    </div>
                  </v-col>
                  <v-col cols="12">
                    <div class="img h-banner">
                      <img
                        class="img-2d3d"
                        :src="imgAPI.social[7]"
                        :data-2d="imgAPI.social[6]"
                        :data-3d="imgAPI.social[7]"
                        alt="banner 3 3D"
                      >
                    </div>
                  </v-col>
                </v-row>
              </v-container>
            </div>
          </div>
        </splide-slide>
      </splide>
    </div>
    <div class="slide-nav-group">
      <hidden point="smDown">
        <v-container>
          <nav class="slide-nav">
            <v-btn
              :class="{ active: currentSlide === 0 }"
              variant="text"
              @click="gotoSlide(0)"
            >
              <strong>First Slide</strong>
              Interdum et malesuada fames ac ante
            </v-btn>
            <v-divider class="divider" vertical inset />
            <v-btn
              :class="{ active: currentSlide === 1 }"
              variant="text"
              @click="gotoSlide(1)"
            >
              <strong>Second Slide</strong>
              Interdum et malesuada fames ac ante
            </v-btn>
            <v-divider class="divider" vertical inset />
            <v-btn
              :class="{ active: currentSlide === 2 }"
              variant="text"
              @click="gotoSlide(2)"
            >
              <strong>Third Slide</strong>
              Interdum et malesuada fames ac ante
            </v-btn>
          </nav>
        </v-container>
      </hidden>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './banner-styles';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import Hidden from '../../Hidden';
import link from '@/assets/text/link';
import imgAPI from '@/assets/images/imgAPI';

export default {
  components: {
    Hidden,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      currentSlide: 0,
      link,
      imgAPI,
      slickOptions: {
        pagination: false,
        arrows: false,
        perPage: 1,
        type: 'loop',
        speed: 1000,
        easing: 'ease',
        direction: 'ltr',
        reducedMotion: {
          speed: 1000,
          rewindSpeed: 1000,
        },
        breakpoints: {
          800: {
            pagination: true,
          },
        },
      },
      slickOptionsDeco: {
        pagination: false,
        arrows: false,
        speed: 1000,
        type: 'fade',
        easing: 'ease',
        direction: 'ltr',
        reducedMotion: {
          speed: 1000,
          rewindSpeed: 1000,
        },
      },
    };
  },
  computed: {
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
        this.slickOptionsDeco.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
        this.slickOptionsDeco.direction = 'ltr';
      }
    }, 100);
  },
  methods: {
    handleAfterChange(slide) {
      this.currentSlide = slide.index;
    },
    gotoSlide(index) {
      this.$refs.sliderBanner.go(index);
    },
    handleSyncDeco(slide) {
      this.$refs.sliderBanner.go(slide.index);
    },
    handleSyncBanner(slide) {
      this.$refs.sliderDeco.go(slide.index);
    },
  },
};
</script>
