// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/medical-theme/components/Cards/TestiCard.js
import React from 'react';
import PropTypes from 'prop-types';
import Paper from '@mui/material/Paper';
import Avatar from '@mui/material/Avatar';
import Typography from '@mui/material/Typography';
import StarIcon from '@mui/icons-material/Star';
import useStyles from './testi-card-style';

function TestiCard(props) {
  const { classes } = useStyles();
  const {
    avatar,
    title,
    name,
    text,
    star,
  } = props;
  return (
    <div className={classes.testiCard}>
      <Paper className={classes.paper}>
        <Typography display="block" component="p">
          {text}
        </Typography>
        <div className={classes.rating}>
          {[...Array(star)].map((e, index) => (
            <StarIcon className={classes.starIcon} key={index.toString()} />
          ))}
          {[...Array(5 - star)].map((e, index) => (
            <StarIcon className={classes.starIconDisable} key={index.toString()} />
          ))}
        </div>
      </Paper>
      <div className={classes.person}>
        <div className={classes.name}>
          <Typography display="block" variant="h6">
            {name}
          </Typography>
          <Typography variant="caption" className={classes.title}>
            {title}
          </Typography>
        </div>
        <Avatar alt={name} src={avatar} className={classes.avatar} />
      </div>
    </div>
  );
}

TestiCard.propTypes = {
  avatar: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired,
  star: PropTypes.number.isRequired,
};

export default TestiCard;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/marketing-theme/components/Cards/TestiCard.vue
<template>
  <div class="testi-card">
    <v-card class="paper">
      <p>
        {{ text }}
      </p>
      <div class="rating">
        <v-icon
          v-for="index in star"
          :key="'active' + index"
          class="star-icon"
        >
          mdi-star
        </v-icon>
        <v-icon
          v-for="index in 5 - star"
          :key="'inactive' + index"
          class="star-icon-disable"
        >
          mdi-star
        </v-icon>
      </div>
      <div class="person">
        <v-avatar class="avatar" width="70" height="70">
          <img
            :alt="name"
            :src="avatar"
          >
        </v-avatar>
        <div class="name">
          <h6>
            {{ name }}
          </h6>
          <span class="caption">
            {{ title }}
          </span>
        </div>
      </div>
    </v-card>
  </div>
</template>

<style lang="scss" scoped>
@import './testi-card';
</style>

<script>
export default {
  props: {
    avatar: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    text: {
      type: String,
      required: true,
    },
    star: {
      type: Number,
      required: true,
    },
  },
};
</script>
