// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas2-theme/components/Forms/ContactMap.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import FormControlLabel from '@mui/material/FormControlLabel';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import EmailIcon from '@mui/icons-material/Email';
import PhoneIcon from '@mui/icons-material/LocalPhone';
import LocationIcon from '@mui/icons-material/LocationOn';
import Snackbar from '@mui/material/Snackbar';
import { useTranslation } from 'next-i18next';
import { ValidatorForm, TextValidator } from 'react-material-ui-form-validator';
import {
  Map,
  Marker,
  GoogleApiWrapper,
  InfoWindow
} from 'google-maps-react18';
import { useText, useTextAlign } from '~/theme/common';
import useStyles from './form-style';
import Checkbox from './Checkbox';

function BubleMark() {
  const { classes } = useStyles();
  return (
    <div className={classes.bubelWrap}>
      <div className={classes.buble}>
        <Typography variant="h6" gutterBottom>
          Head Quarter
        </Typography>
        <Grid container>
          <Grid item sm={6} xs={12}>
            <Typography>
              <PhoneIcon className={classes.icon} />
              +98 765 432 10
            </Typography>
          </Grid>
          <Grid item sm={6} xs={12}>
            <Typography>
              <EmailIcon className={classes.icon} />
              hello@luxi.com
            </Typography>
          </Grid>
          <Grid item xs={12}>
            <Typography>
              <LocationIcon className={classes.icon} />
              Lorem ipsum street Block C - Vestibullum Building
            </Typography>
          </Grid>
        </Grid>
      </div>
    </div>
  );
}

function MapContainer(props) {
  const [activeMarker, setActive] = useState({});
  const [showingInfoWindow, setShow] = useState(false);
  const { google } = props;
  // eslint-disable-next-line
  const onMarkerClick = (props, marker) => {
    setActive(marker);
    setShow(true);
  };

  const onMapClicked = () => {
    if (showingInfoWindow) {
      setShow(false);
      setActive(null);
    }
  };

  return (
    <Map
      google={google}
      onClick={onMapClicked}
      style={{ width: '100%', height: '915px', position: 'relative' }}
      initialCenter={{
        lat: 37.759703,
        lng: -122.428093
      }}
      zoom={14}
    >
      <Marker
        onClick={onMarkerClick}
        position={{ lat: 37.759703, lng: -122.428093 }}
      />
      <InfoWindow
        marker={activeMarker}
        visible={showingInfoWindow}
      >
        <div>
          <BubleMark />
        </div>
      </InfoWindow>
    </Map>
  );
}

MapContainer.propTypes = {
  google: PropTypes.object.isRequired
};

const MapWithAMarker = GoogleApiWrapper({ apiKey: null })(MapContainer);

function ContactMap(props) {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const { classes: align } = useTextAlign();
  const { full } = props;
  const { t } = useTranslation('common');
  const [values, setValues] = useState({
    name: '',
    email: '',
    phone: '',
    company: '',
    message: ''
  });

  useEffect(() => {
    ValidatorForm.addValidationRule('isTruthy', value => value);
  });

  const [openNotif, setNotif] = useState(false);

  const [check, setCheck] = useState(false);

  const handleChange = name => event => {
    setValues({ ...values, [name]: event.target.value });
  };

  const handleCheck = event => {
    setCheck(event.target.checked);
  };

  const handleSubmit = () => {
    setNotif(true);
  };

  const handleClose = () => {
    setNotif(false);
  };

  return (
    <div className={classes.pageWrap}>
      <Snackbar
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        key="top right"
        open={openNotif}
        autoHideDuration={4000}
        onClose={handleClose}
        ContentProps={{
          'aria-describedby': 'message-id',
        }}
        message={<span id="message-id">Message Sent</span>}
      />
      <Grid container alignItems="center">
        <Grid item md={6} xs={12} className={classes.wrapDeco}>
          <Paper className={cx(classes.formBox, full ? classes.mapForm : '')}>
            <div className={classes.fullFromWrap}>
              <div className={classes.form}>
                <h4 className={cx(align.textCenter, text.textPrimary, text.title2)}>
                  {t('contact_title2')}
                </h4>
                <p className={cx(align.textCenter, text.paragraph)}>
                  {t('contact_subtitle')}
                </p>
                <ValidatorForm
                  onSubmit={handleSubmit}
                  onError={errors => console.log(errors)}
                >
                  <Box py={3}>
                    <Grid container spacing={3}>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          fullWidth
                          label={t('form_name')}
                          onChange={handleChange('name')}
                          name="Name"
                          variant="filled"
                          value={values.name}
                          validators={['required']}
                          errorMessages={['This field is required']}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          fullWidth
                          label={t('form_email')}
                          onChange={handleChange('email')}
                          name="Email"
                          variant="filled"
                          value={values.email}
                          validators={['required', 'isEmail']}
                          errorMessages={['This field is required', 'email is not valid']}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          fullWidth
                          label={t('form_phone')}
                          onChange={handleChange('phone')}
                          name="Phone"
                          variant="filled"
                          value={values.phone}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          multiline
                          rows="6"
                          fullWidth
                          className={classes.input}
                          label={t('form_message')}
                          onChange={handleChange('message')}
                          name="Message"
                          variant="filled"
                          value={values.message}
                        />
                      </Grid>
                    </Grid>
                  </Box>
                  <FormControlLabel
                    className={classes.checkArea}
                    control={(
                      <Checkbox
                        validators={['isTruthy']}
                        errorMessages="This field is required"
                        checked={check}
                        value={check}
                        onChange={(e) => handleCheck(e)}
                        color="primary"
                      />
                    )}
                    label={(
                      <span className={text.paragraph}>
                        {t('form_terms')}
                        <br />
                        <a href="#">
                          {t('form_privacy')}
                        </a>
                      </span>
                    )}
                  />
                  <div className={classes.btnArea}>
                    <Button
                      variant="contained"
                      fullWidth
                      type="submit"
                      color="primary"
                      className={classes.buttonLarge}
                      size="large"
                    >
                      {t('form_send')}
                      &nbsp;
                    </Button>
                  </div>
                </ValidatorForm>
              </div>
            </div>
          </Paper>
        </Grid>
        <Grid item md={6} xs={12}>
          <Paper className={cx(classes.map, full ? classes.full : '')} elevation={0}>
            <MapWithAMarker />
          </Paper>
        </Grid>
      </Grid>
    </div>
  );
}

ContactMap.propTypes = {

  full: PropTypes.bool
};

ContactMap.defaultProps = {
  full: false
};

export default ContactMap;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/Forms/ContactMap.vue
<template>
  <div class="page-wrap">
    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
      top
      right
      class="notification"
    >
      <div class="action">
        Message Sent
      </div>
      <v-btn
        text
        icon
        @click="snackbar = false"
      >
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-snackbar>
    <v-container class="inner-wrap">
      <v-row align="center">
        <v-col md="6" cols="12" class="pe-md-0 wrap-deco">
          <v-card :class="{ 'map-form': full }" class="form-box">
            <div class="form">
              <div class="text-center">
                <h4 class="use-text-title2 use-text-primary mb-3">
                  {{ $t('common.contact_title2') }}
                </h4>
                <p>Aenean sit amet magna vel magna fringilla fermentum. Donec sit amet nulla sed arcu pulvinar ultricies commodo id ligula.</p>
              </div>
              <v-form
                ref="form"
                v-model="valid"
              >
                <v-row class="spacing6">
                  <v-col cols="12" sm="12" class="px-6">
                    <v-text-field
                      v-model="name"
                      :rules="nameRules"
                      :label="$t('common.form_name')"
                      required
                      color="secondary"
                      variant="filled"
                    />
                  </v-col>
                  <v-col cols="12" sm="12" class="px-6">
                    <v-text-field
                      v-model="email"
                      :rules="emailRules"
                      :label="$t('common.form_email')"
                      required
                      color="secondary"
                      variant="filled"
                    />
                  </v-col>
                  <v-col cols="12" sm="12" class="px-6">
                    <v-text-field
                      v-model="phone"
                      variant="filled"
                      color="secondary"
                      :label="$t('common.form_phone')"
                    />
                  </v-col>
                  <v-col cols="12" class="px-6">
                    <v-textarea
                      v-model="message"
                      rows="6"
                      variant="filled"
                      color="secondary"
                      :label="$t('common.form_message')"
                    />
                  </v-col>
                </v-row>
                <div class="form-control-label">
                  <v-checkbox
                    v-model="checkbox"
                    class="ms-n2"
                    color="secondary"
                    :rules="[v => !!v || 'You must agree to continue!']"
                    :label="$t('common.form_terms')"
                    required
                  />
                  <span>
                    <a href="#" class="link">
                      {{ $t('common.form_privacy') }}
                    </a>
                  </span>
                </div>
                <div class="btn-area">
                  <v-btn
                    size="large"
                    block
                    color="primary"
                    @click="validate"
                  >
                    {{ $t('common.form_send') }}
                  </v-btn>
                </div>
              </v-form>
            </div>
          </v-card>
        </v-col>
        <v-col md="6" cols="12" class="ps-md-0">
          <v-card :class="{ full: full }" class="map" raised>
            <GoogleMap
              :zoom="5"
              :center="{ lat: locations[0].lat, lng: locations[0].lng }"
              style="width: 100%; height: 100%"
            >
              <InfoWindow :options="{ position: { lat: locations[0].lat + 1, lng: locations[0].lng } }">
                <div class="bubel">
                  <h6 class="use-text-subtitle pb-1 px-3">
                    Head Quarter
                  </h6>
                  <v-row class="ma-3">
                    <v-col item sm="6" cols="12">
                      <p>
                        <v-icon class="icon">
                          mdi-phone
                        </v-icon>
                        +98 765 432 10
                      </p>
                    </v-col>
                    <v-col item sm="6" cols="12">
                      <p>
                        <v-icon class="icon">
                          mdi-email
                        </v-icon>
                        hello@luxi.com
                      </p>
                    </v-col>
                    <v-col item sm="12" cols="12">
                      <p>
                        <v-icon class="icon">
                          mdi-map-marker
                        </v-icon>
                        Lorem ipsum street Block C - Vestibullum Building
                      </p>
                    </v-col>
                  </v-row>
                </div>
              </InfoWindow>
              <MarkerCluster>
                <Marker
                  v-for="(location, i) in locations"
                  :key="i"
                  :options="{ position: location }"
                />
              </MarkerCluster>
            </GoogleMap>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './form-style.scss';
</style>

<script>
import {
  GoogleMap,
  Marker,
  MarkerCluster,
  InfoWindow,
} from 'vue3-google-map';

export default {
  components: {
    GoogleMap,
    Marker,
    MarkerCluster,
    InfoWindow,
  },
  props: {
    full: {
      type: Boolean,
      default: false,
    },
  },
  data: () => ({
    currentLocation: {},
    locations: [
      {
        lat: 44.933076,
        lng: 15.629058,
      },
    ],
    valid: true,
    snackbar: false,
    name: '',
    nameRules: [v => !!v || 'Name is required'],
    email: '',
    emailRules: [
      v => !!v || 'E-mail is required',
      v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
    ],
    phone: '',
    company: '',
    message: '',
    checkbox: false,
  }),
  methods: {
    validate() {
      if (this.$refs.form.validate()) {
        this.snackbar = true;
      }
    },
  },
};
</script>
