// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas2-theme/components/Header/Search.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import AppBar from '@mui/material/AppBar';
import Container from '@mui/material/Container';
import Hidden from '@mui/material/Hidden';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Logo from '../Logo';
import link from '~/public/text/link';
import SearchField from './TopNav/SearchField';
import UserMenu from './TopNav/UserMenu';
import useStyles from './header-style';

function Search(props) {
  const [fixed, setFixed] = useState(false);
  const { classes, cx } = useStyles();
  const theme = useTheme();
  const { onToggleDark, onToggleDir } = props;
  const isDesktop = useMediaQuery(theme.breakpoints.up('sm'));
  let flagFixed = false;

  const handleScroll = () => {
    const doc = document.documentElement;
    const scroll = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);
    const newFlagFixed = (scroll > 80);
    if (flagFixed !== newFlagFixed) {
      setFixed(newFlagFixed);
      flagFixed = newFlagFixed;
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
  }, []);

  return (
    <AppBar
      position="relative"
      id="header"
      className={cx(
        classes.header,
        fixed && classes.fixed,
      )}
    >
      <Container>
        <div className={classes.headerContent}>
          <nav className={cx(classes.navMenu, classes.flex)}>
            <div className={classes.logo}>
              <a href={link.saas2.home}>
                <Logo type="landscape" />
              </a>
            </div>
            {isDesktop && (
              <SearchField />
            )}
          </nav>
          <UserMenu onToggleDark={onToggleDark} onToggleDir={onToggleDir} />
        </div>
        <Hidden smUp>
          <SearchField />
        </Hidden>
      </Container>
    </AppBar>
  );
}

Search.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

export default Search;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Header/Search.vue
<template>
  <v-app-bar
    v-scroll="handleScroll"
    :class="{ fixed: fixed }"
    class="header"
    fixed
    dense
    app
    height="auto"
  >
    <v-container>
      <div class="header-content">
        <nav class="nav-menu">
          <div class="logo start-mobile">
            <a :href="link.saas2.home">
              <logo type="landscape" />
            </a>
          </div>
          <search-field v-if="!isMobile" />
        </nav>
        <user-menu />
      </div>
      <hidden point="smUp">
        <search-field />
      </hidden>
    </v-container>
  </v-app-bar>
</template>

<style lang="scss" scoped>
@import './header-style.scss';
</style>

<script>
import link from '@/assets/text/link';
import Logo from '../Logo';
import UserMenu from './TopNav/UserMenu';
import SearchField from './TopNav/SearchField';
import Hidden from '../Hidden';

export default {
  components: {
    Logo,
    Hidden,
    SearchField,
    UserMenu,
  },
  data() {
    return {
      link,
      fixed: false,
      loaded: false,
      openNavMobile: null,
    };
  },
  computed: {
    isMobile() {
      const xsDown = this.$vuetify.display.xs;
      return xsDown;
    },
  },
  mounted() {
    this.loaded = true;
  },
  methods: {
    handleScroll() {
      if (window.scrollY > 100) {
        this.fixed = true;
      } else {
        this.fixed = false;
      }
    },
    handleToggleOpen() {
      this.openNavMobile = !this.openNavMobile;
    },
  },
};
</script>
