// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/medical-theme/components/Home/Facilities/Facilities.js
import React, { useState, useRef } from 'react';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Button from '@mui/material/Button';
import Fab from '@mui/material/Fab';
import Carousel from 'react-slick';
import PrevIcon from '@mui/icons-material/ArrowBack';
import NextIcon from '@mui/icons-material/ArrowForward';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import link from '~/public/text/link';
import { useText } from '~/theme/common';
import useStyles from './facilities-style';
import SliderArt from '../SliderArt';
import FacilityCard from '../../Cards/FacilityCard';

const servicesList = [
  {
    title: 'Lorem Ipsum',
    desc:
      'Proin ac arcu nisl. Duis eu molestie lectus. Nam quis mauris faucibus, aliquet elit eu, rhoncus ipsum.',
    img: imgAPI.medical[26]
  },
  {
    title: 'Etiam rhoncus',
    desc:
      'Proin quis pellentesque dui. Ut sed leo neque. Nullam aliquet iaculis neque a commodo.',
    img: imgAPI.medical[27]
  },
  {
    title: 'Duis fermentum',
    desc:
      'Quisque consectetur lectus vel orci porttitor gravida ac eu erat. Nullam accumsan nibh tortor.',
    img: imgAPI.medical[28]
  },
  {
    title: 'Lorem Ipsum',
    desc:
      'Proin ac arcu nisl. Duis eu molestie lectus. Nam quis mauris faucibus, aliquet elit eu, rhoncus ipsum.',
    img: imgAPI.medical[29]
  },
  {
    title: 'Etiam rhoncus',
    desc:
      'Proin quis pellentesque dui. Ut sed leo neque. Nullam aliquet iaculis neque a commodo.',
    img: imgAPI.medical[30]
  },
  {
    title: 'Duis fermentum',
    desc:
      'Quisque consectetur lectus vel orci porttitor gravida ac eu erat. Nullam accumsan nibh tortor.',
    img: imgAPI.medical[26]
  }
];

function Facilities() {
  const { t } = useTranslation('common');
  const { classes } = useStyles();
  const slider = useRef(null);
  const [fade, setFade] = useState(false);
  const { classes: text } = useText();
  const settings = {
    dots: false,
    infinite: false,
    speed: 500,
    slidesToShow: 3,
    arrows: false,
    slidesToScroll: 1,
    variableWidth: true,
    afterChange: current => {
      if (current > 0) {
        setFade(true);
      } else {
        setFade(false);
      }
    },
    responsive: [
      {
        breakpoint: 800,
        settings: {
          slidesToShow: 3
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1
        }
      }
    ]
  };

  return (
    <div className={classes.root}>
      <Container className={classes.carouselHeader}>
        <Box flex={1} px={{ xs: 2, sm: 3 }}>
          <h4 className={text.title}>
            {t('medical-landing.services_title')}
          </h4>
          <p className={text.subtitle2}>Nam sollicitudin dignissim nunc, cursus ullamcorper eros vulputate sed.</p>
        </Box>
        <Button
          href={link.medical.product}
          color="primary"
          className={classes.viewAll}
        >
          {t('btn_seeall')}
          <NextIcon className={classes.icon} />
        </Button>
      </Container>
      <div className={classes.carouselHandle}>
        <div className={classes.carouselWrap}>
          <Carousel ref={slider} {...settings}>
            <div className={classes.item}>
              <div className={classes.carouselProp}>
                <div />
              </div>
            </div>
            {servicesList.map((item, index) => (
              <div className={classes.item} key={index.toString()}>
                <FacilityCard
                  title={item.title}
                  desc={item.desc}
                  img={item.img}
                  button={t('btn_detail')}
                />
              </div>
            ))}
          </Carousel>
        </div>
      </div>
      <div className={classes.floatingArtwork}>
        <Container fixed>
          <div className={classes.artwork}>
            <SliderArt fade={fade}>
              <ScrollAnimation animateOnce animateIn="fadeInLeftShort" offset={-60} delay={300} duration={0.5}>
                <div>
                  <img
                    src={imgAPI.medical[13]}
                    data-2d={imgAPI.medical[12]}
                    data-3d={imgAPI.medical[13]}
                    className="img-2d3d"
                    alt="services 3d"
                  />
                </div>
              </ScrollAnimation>
            </SliderArt>
            <nav className={classes.arrow}>
              <Fab size="small" onClick={() => slider.current.slickPrev()} aria-label="prev" className={classes.margin}>
                <PrevIcon />
              </Fab>
              <Fab size="small" onClick={() => slider.current.slickNext()} aria-label="next" className={classes.margin}>
                <NextIcon />
              </Fab>
            </nav>
          </div>
        </Container>
      </div>
    </div>
  );
}

export default Facilities;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/medical-theme/components/Home/Facilities/Facilities.vue
<template>
  <div class="root">
    <div>
      <v-container class="carousel-header">
        <div class="px-3">
          <h4 class="use-text-title">
            {{ $t('medical.services_title') }}
          </h4>
          <p class="use-text-subtitle2">
            Nam sollicitudin dignissim nunc, cursus ullamcorper eros vulputate sed.
          </p>
        </div>
        <v-btn
          :href="link.medical.product"
          text
          class="view-all"
        >
          {{ $t('common.btn_seeall') }}
          <v-icon>mdi-arrow-right</v-icon>
        </v-btn>
      </v-container>
      <div class="carousel-handle">
        <div v-if="loaded" class="carousel-wrap">
          <splide
            ref="splide"
            :options="slickOptions"
            @splide:active="handleAfterChange"
          >
            <splide-slide>
              <div class="item">
                <div class="carousel-prop">
                  <div />
                </div>
              </div>
            </splide-slide>
            <splide-slide
              v-for="(item, index) in servicesList"
              :key="index"
            >
              <div class="item">
                <card
                  :title="item.title"
                  :desc="item.desc"
                  :img="item.img"
                  button="see detail"
                />
              </div>
            </splide-slide>
          </splide>
        </div>
      </div>
      <div class="floating-artwork">
        <v-container class="fixed-width">
          <div class="artwork">
            <slider-art :fade="fade">
              <div
                data-aos-offset="250"
                data-aos="fade-left"
                data-aos-delay="300"
                data-aos-duration="500"
              >
                <div>
                  <img
                    :src="imgAPI.medical[13]"
                    :data-2d="imgAPI.medical[12]"
                    :data-3d="imgAPI.medical[13]"
                    class="img-2d3d"
                    alt="facilities"
                  >
                </div>
              </div>
            </slider-art>
            <nav class="arrow">
              <v-btn
                icon
                size="small"
                aria-label="next"
                class="margin"
                @click="next()"
              >
                <v-icon>mdi-arrow-left</v-icon>
              </v-btn>
              <v-btn
                icon
                size="small"
                aria-label="prev"
                class="margin"
                @click="prev()"
              >
                <v-icon>mdi-arrow-right</v-icon>
              </v-btn>
            </nav>
          </div>
        </v-container>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './facilities-style.scss';
</style>

<script>
import AOS from 'aos';
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import imgAPI from '@/assets/images/imgAPI';
import link from '@/assets/text/link';
import Card from '../../Cards/FacilityCard';
import SliderArt from '../SliderArt';

export default {
  components: {
    Card,
    SliderArt,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      imgAPI,
      link,
      fade: false,
      slickOptions: {
        pagination: false,
        speed: 500,
        perPage: 4,
        perMove: 1,
        arrows: false,
        autoWidth: true,
        direction: 'ltr',
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
        breakpoints: {
          1100: {
            perPage: 4,
          },
          800: {
            perPage: 3,
          },
          600: {
            perPage: 2,
          },
        },
      },
      servicesList: [
        {
          title: 'Lorem Ipsum',
          desc:
            'Proin ac arcu nisl. Duis eu molestie lectus. Nam quis mauris faucibus, aliquet elit eu, rhoncus ipsum.',
          img: imgAPI.medical[26],
        },
        {
          title: 'Etiam rhoncus',
          desc:
            'Proin quis pellentesque dui. Ut sed leo neque. Nullam aliquet iaculis neque a commodo.',
          img: imgAPI.medical[27],
        },
        {
          title: 'Duis fermentum',
          desc:
            'Quisque consectetur lectus vel orci porttitor gravida ac eu erat. Nullam accumsan nibh tortor.',
          img: imgAPI.medical[28],
        },
        {
          title: 'Lorem Ipsum',
          desc:
            'Proin ac arcu nisl. Duis eu molestie lectus. Nam quis mauris faucibus, aliquet elit eu, rhoncus ipsum.',
          img: imgAPI.medical[29],
        },
        {
          title: 'Etiam rhoncus',
          desc:
            'Proin quis pellentesque dui. Ut sed leo neque. Nullam aliquet iaculis neque a commodo.',
          img: imgAPI.medical[30],
        },
        {
          title: 'Duis fermentum',
          desc:
            'Quisque consectetur lectus vel orci porttitor gravida ac eu erat. Nullam accumsan nibh tortor.',
          img: imgAPI.medical[26],
        },
      ],
    };
  },
  mounted() {
    this.loaded = true;
    AOS.init({
      once: true,
    });
  },
  methods: {
    next() {
      this.$refs.splide.go('>');
    },
    prev() {
      this.$refs.splide.go('<');
    },
    handleAfterChange(slide) {
      if (slide.index > 0) {
        this.fade = true;
      } else {
        this.fade = false;
      }
    },
  },
};
</script>
