// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/components/Counter/Counter.js
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import CountUp from 'react-countup';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Typography from '@mui/material/Typography';
import FlagIcon from '@mui/icons-material/Flag';
import PeopleIcon from '@mui/icons-material/People';
import PublicIcon from '@mui/icons-material/Public';
import Grid from '@mui/material/Grid';
import Container from '@mui/material/Container';
import useStyles from './counter-style';
import { useText } from '~/theme/common';

function Counter(props) {
  const { classes, cx } = useStyles();
  const { dark } = props;
  const [play, setPlay] = useState(false);
  const { classes: text } = useText();
  const countup = (val, isPlay) => (
    <span>
      {isPlay ? <CountUp end={val} /> : 0}
    </span>
  );
  const handlePlay = visible => {
    if (visible.inViewport) {
      setTimeout(() => { setPlay(true); }, 500);
    }
  };
  return (
    <div className={cx(classes.counterWrap, dark ? classes.dark : '')}>
      <ScrollAnimation animateOnce animateIn="fadeIn" offset={300} afterAnimatedIn={handlePlay}>
        <Container maxWidth="md">
          <Grid container justifyContent="center" alignItems="center" className={classes.root} spacing={6}>
            <Grid sm={4} xs={12} item>
              <div className={classes.counterItem}>
                <FlagIcon className={classes.primary} />
                <div className={classes.text}>
                  <Typography variant="h4">
                    +&nbsp;
                    {countup(123, play)}
                  </Typography>
                  <h6 className={text.subtitle2}>
                    Lorem Ipsum
                  </h6>
                </div>
              </div>
            </Grid>
            <Grid sm={4} xs={12} item>
              <div className={classes.counterItem}>
                <PeopleIcon className={classes.secondary} />
                <div className={classes.text}>
                  <Typography variant="h4">
                    +&nbsp;
                    {countup(456, play)}
                  </Typography>
                  <h6 className={text.subtitle2}>
                    Ac bibendum
                  </h6>
                </div>
              </div>
            </Grid>
            <Grid sm={4} xs={12} item>
              <div className={classes.counterItem}>
                <PublicIcon className={classes.accent} />
                <div className={classes.text}>
                  <Typography variant="h4">
                    $
                    {countup(789, play)}
                  </Typography>
                  <h6 className={text.subtitle2}>
                    Adipiscing
                  </h6>
                </div>
              </div>
            </Grid>
          </Grid>
        </Container>
      </ScrollAnimation>
    </div>
  );
}

Counter.propTypes = {
  dark: PropTypes.bool,
};

Counter.defaultProps = {
  dark: false,
};

export default Counter;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/fintech-theme/components/Counter/Counter.vue
<template>
  <div
    ref="wrapper"
    v-scroll="runCounter"
    :class="{ dark: dark }"
    class="counter-wrap"
  >
    <v-container class="max-md">
      <v-row
        align="center"
        justify="center"
        class="root"
      >
        <v-col sm="4">
          <div class="counter-item">
            <span class="icon ion-ios-flag text-primary" />
            <div class="text">
              <h4 class="use-text-title2">
                {{ !visible ? 0 : '' }}
                <count-up
                  v-if="visible"
                  :start-val="0"
                  :end-val="123"
                  :options="{ prefix: '+' }"
                />
              </h4>
              <h6 class="use-text-subtitle2">
                Lorem Ipsum
              </h6>
            </div>
          </div>
        </v-col>
        <v-col sm="4">
          <div class="counter-item">
            <span class="icon ion-md-people text-secondary" />
            <div class="text">
              <h4 class="use-text-title2">
                {{ !visible ? 0 : '' }}
                <count-up
                  v-if="visible"
                  :start-val="0"
                  :end-val="456"
                  :options="{ prefix: '+' }"
                />
              </h4>
              <h6 class="use-text-subtitle2">
                Ac bibendum
              </h6>
            </div>
          </div>
        </v-col>
        <v-col sm="4">
          <div class="counter-item">
            <span class="icon ion-md-globe text-accent" />
            <div class="text">
              <h4 class="use-text-title2">
                {{ !visible ? 0 : '' }}
                <count-up
                  v-if="visible"
                  :start-val="0"
                  :end-val="456"
                  :options="{ prefix: '+' }"
                />
              </h4>
              <h6 class="use-text-subtitle2">
                Adipiscing
              </h6>
            </div>
          </div>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped lang="scss">
@import './counter-style';
</style>

<script>
import CountUp from 'vue-countup-v3';
import { ref } from 'vue';

export default {
  components: {
    CountUp,
  },
  props: {
    dark: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const visible = ref(false);
    const wrapper = ref(null);
    const offset = 500;
    function runCounter() {
      const scrollPosition = document.documentElement.scrollTop || document.body.scrollTop;
      const topPosition = scrollPosition + offset;

      if (topPosition > wrapper.value.offsetTop) {
        visible.value = true;
      }
    }

    return {
      visible,
      runCounter,
      wrapper,
    };
  },
  data() {
    return {
      loaded: false,
    };
  },
};
</script>
