// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Feature/MainFeature.vue
<template>
  <div class="main-feature">
    <v-container fixed>
      <div>
        <main-title
          :caption="$t('cloud.mainfeature_headtitle')"
          :text="$t('cloud.mainfeature_title')"
          align="center"
        />
        <v-row class="spacing6 grid">
          <v-col
            v-for="(item, index) in featureList"
            :key="index"
            sm="4"
            cols="12"
            class="pa-6"
          >
            <div
              :data-aos-delay="(200 + (100 * index))"
              data-aos-offset="260"
              data-aos="fade-up"
              data-aos-duration="300"
            >
              <div class="item">
                <figure>
                  <svg class="wave">
                    <use :xlink:href="item.img" />
                  </svg>
                </figure>
                <h6 class="use-text-subtitle2">
                  {{ $t('cloud.mainfeature_' + item.title) }}
                </h6>
                <p class="use-text-paragraph">
                  {{ $t('cloud.mainfeature_' + item.desc) }}
                </p>
              </div>
            </div>
          </v-col>
        </v-row>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './feature-style.scss';
</style>

<script>
import AOS from 'aos';
import Title from '../../Title';

export default {
  components: {
    'main-title': Title,
  },
  data() {
    return {
      featureList: [
        {
          img: '/images/cloud/gear.svg#main',
          title: 'titleitem1',
          desc: 'descitem1',
        },
        {
          img: '/images/cloud/connection.svg#main',
          title: 'titleitem2',
          desc: 'descitem2',
        },
        {
          img: '/images/cloud/support.svg#main',
          title: 'titleitem3',
          desc: 'descitem3',
        },
      ],
    };
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Home/Feature/MainFeature.js
import React from 'react';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import Title from '../../Title';
import useStyles from './feature-style';

const featureList = [
  {
    img: '/images/cloud/gear.svg#main',
    title: 'titleitem1',
    desc: 'descitem1'
  },
  {
    img: '/images/cloud/connection.svg#main',
    title: 'titleitem2',
    desc: 'descitem2'
  },
  {
    img: '/images/cloud/support.svg#main',
    title: 'titleitem3',
    desc: 'descitem3'
  }
];

function MainFeature() {
  const { classes } = useStyles();
  const { classes: text } = useText();
  const { t } = useTranslation('common');
  return (
    <div className={classes.mainFeature}>
      <Container>
        <Title caption={t('cloud-landing.mainfeature_headtitle')} text={t('cloud-landing.mainfeature_title')} align="center" />
        <Grid container spacing={6} className={classes.grid}>
          {featureList.map((item, index) => (
            <Grid item sm={4} key={index.toString()}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInUpShort"
                offset={-260}
                delay={(200 + (100 * index))}
                duration={0.3}
              >
                <div className={classes.item}>
                  <figure>
                    <svg className={classes.wave}>
                      <use xlinkHref={item.img} />
                    </svg>
                  </figure>
                  <Typography variant="h6" className={text.subtitle2}>
                    {t('cloud-landing.mainfeature_' + item.title)}
                  </Typography>
                  <Typography component="p" className={text.paragraph}>
                    {t('cloud-landing.mainfeature_' + item.desc)}
                  </Typography>
                </div>
              </ScrollAnimation>
            </Grid>
          ))}
        </Grid>
      </Container>
    </div>
  );
}

MainFeature.propTypes = {

};

export default MainFeature;
