// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Feature/MoreFeature.vue
<template>
  <div class="more-feature">
    <v-container :class="{ fixed: isDesktop }">
      <div class="item">
        <div>
          <v-row
            :class="[isMobile ? 'column-reverse' : 'row']"
            class="spacing6"
          >
            <v-col md="6" cols="12" class="pa-sm-6">
              <div
                data-aos="fade-right"
                data-aos-offset="100"
                data-aos-delay="400"
                data-aos-duration="300"
              >
                <figure class="illustration">
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[17]"
                    :data-2d="imgAPI.cloud[16]"
                    :data-3d="imgAPI.cloud[17]"
                    alt="feature"
                  >
                </figure>
              </div>
            </v-col>
            <v-col md="6" cols="12" class="pa-sm-6">
              <div class="text">
                <main-title
                  :caption="$t('cloud.morefeature_headtitle1')"
                  :text="$t('cloud.morefeature_title1')"
                  :align="isMobile ? 'center' : 'left'"
                />
                <div :class="{ 'text-center': isMobile }">
                  <p class="use-text-subtitle2" :class="isMobile ? 'text-center' : 'text-start'">
                    {{ $t('cloud.morefeature_desc1') }}
                  </p>
                  <v-btn size="large" color="primary">
                    {{ $t('cloud.learnmore') }}
                  </v-btn>
                </div>
              </div>
            </v-col>
          </v-row>
        </div>
      </div>
      <v-divider class="divider" />
      <div class="item">
        <div>
          <v-row class="spacing6">
            <v-col md="6" cols="12">
              <div class="text text-end">
                <main-title
                  :caption="$t('cloud.morefeature_headtitle2')"
                  :text="$t('cloud.morefeature_title2')"
                  :align="isMobile ? 'center' : 'right'"
                />
                <div :class="{ 'text-center': isMobile }">
                  <p
                    :class="isMobile ? 'text-center' : 'text-end'"
                    class="use-text-subtitle2"
                  >
                    {{ $t('cloud.morefeature_desc2') }}
                  </p>
                  <v-btn size="large" color="primary">
                    {{ $t('cloud.learnmore') }}
                  </v-btn>
                </div>
              </div>
            </v-col>
            <v-col md="6" cols="12">
              <div
                data-aos="fade-left"
                data-aos-delay="400"
                data-aos-duration="300"
              >
                <figure class="illustration">
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[19]"
                    :data-2d="imgAPI.cloud[18]"
                    :data-3d="imgAPI.cloud[19]"
                    alt="feature"
                  >
                </figure>
              </div>
            </v-col>
          </v-row>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './feature-style.scss';
</style>

<script>
import AOS from 'aos';
import Title from '../../Title';
import imgAPI from '@/assets/images/imgAPI';

export default {
  components: {
    'main-title': Title,
  },
  data() {
    return {
      imgAPI,
    };
  },
  computed: {
    isDesktop() {
      const lgUp = this.$vuetify.display.lgAndUp;
      return lgUp;
    },
    isMobile() {
      const smDown = this.$vuetify.display.smAndDown;
      return smDown;
    },
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Home/Feature/MoreFeature.js
import React from 'react';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Container from '@mui/material/Container';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import Divider from '@mui/material/Divider';
import { useTranslation } from 'next-i18next';
import { useTextAlign, useText } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Title from '../../Title';
import useStyles from './feature-style';

function MoreFeature() {
  // Theme breakpoints
  const theme = useTheme();
  const { classes: text } = useText();
  const isDesktop = useMediaQuery(theme.breakpoints.up('lg'));
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  // Translation Function
  const { t } = useTranslation('common');

  const { classes, cx } = useStyles();
  const { classes: align } = useTextAlign();
  return (
    <div className={classes.moreFeature}>
      <Container fixed={isDesktop}>
        <div className={classes.item}>
          <Grid
            direction={isMobile ? 'column-reverse' : 'row'}
            container
            spacing={6}
          >
            <Grid item md={6} xs={12}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInRightShort"
                offset={-160}
                delay={400}
                duration={0.3}
              >
                <figure className={classes.illustration}>
                  <img
                    className="img-2d3d"
                    src={imgAPI.cloud[17]}
                    data-2d={imgAPI.cloud[16]}
                    data-3d={imgAPI.cloud[17]}
                    alt="feature"
                  />
                </figure>
              </ScrollAnimation>
            </Grid>
            <Grid item md={6} xs={12}>
              <div className={classes.text}>
                <div>
                  <Title
                    caption={t('cloud-landing.morefeature_headtitle1')}
                    text={t('cloud-landing.morefeature_title1')}
                    align={isMobile ? 'center' : 'left'}
                  />
                  <div className={isMobile ? align.textCenter : ''}>
                    <p className={text.subtitle2} align={isMobile ? 'center' : 'left'}>
                      {t('cloud-landing.morefeature_desc1')}
                    </p>
                    <Button variant="contained" color="primary">
                      {t('cloud-landing.learnmore')}
                    </Button>
                  </div>
                </div>
              </div>
            </Grid>
          </Grid>
        </div>
        <Divider className={classes.divider} />
        <div className={classes.item}>
          <Grid container spacing={6}>
            <Grid item md={6} xs={12}>
              <div className={cx(classes.text, align.textRight)}>
                <div>
                  <Title
                    caption={t('cloud-landing.morefeature_headtitle2')}
                    text={t('cloud-landing.morefeature_title2')}
                    align={isMobile ? 'center' : 'right'}
                  />
                  <div className={isMobile ? align.textCenter : ''}>
                    <p className={text.subtitle2} align={isMobile ? 'center' : 'right'}>
                      {t('cloud-landing.morefeature_desc2')}
                    </p>
                    <Button variant="contained" color="primary">
                      {t('cloud-landing.learnmore')}
                    </Button>
                  </div>
                </div>
              </div>
            </Grid>
            <Grid item md={6} xs={12}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInLeftShort"
                delay={400}
                duration={0.3}
              >
                <figure className={classes.illustration}>
                  <img
                    className="img-2d3d"
                    src={imgAPI.cloud[19]}
                    data-2d={imgAPI.cloud[18]}
                    data-3d={imgAPI.cloud[19]}
                    alt="feature"
                  />
                </figure>
              </ScrollAnimation>
            </Grid>
          </Grid>
        </div>
      </Container>
    </div>
  );
}

MoreFeature.propTypes = {

};

export default MoreFeature;
