// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/retail-theme/components/Cards/PricingCard.js
import React from 'react';
import PropTypes from 'prop-types';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardHeader from '@mui/material/CardHeader';
import StarIcon from '@mui/icons-material/StarBorder';
import { useText } from '~/theme/common';
import useStyles from './pricing-card-style';

function PricingCard(props) {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  const {
    title, subheader, price, info,
    description, buttonText
  } = props;

  return (
    <Card className={cx(classes.priceCard, title === 'Pro' ? classes.bordered : '')}>
      <div className={cx(classes.priceHeader, title === 'Pro' ? classes.hasBg : '')}>
        <CardHeader
          title={title}
          subheader={subheader}
          titleTypographyProps={{ align: 'center' }}
          subheaderTypographyProps={{ align: 'center' }}
          action={title === 'Pro' ? <StarIcon /> : null}
          className={cx(classes.cardHeader, title === 'Free' ? text.secondaryColor : text.primaryColor)}
        />
        <div className={classes.cardPricing}>
          <h2 className={cx(title === 'Free' ? text.textSecondary : text.textPrimary, text.title)}>
            $
            {price}
          </h2>
          <Typography variant="h6">
            &nbsp;/ mo
          </Typography>
        </div>
      </div>
      <CardContent className={classes.cardContent}>
        <ul>
          {description.map(line => (
            <Typography component="li" variant="subtitle1" align="center" key={line}>
              {line}
            </Typography>
          ))}
        </ul>
      </CardContent>
      <CardActions className={cx(classes.btnArea, title === 'Free' ? classes.secondaryColor : classes.primaryColor)}>
        <p>{ info }</p>
        <Button fullWidth variant="contained" color={title === 'Free' ? 'secondary' : 'primary'}>
          {buttonText}
        </Button>
      </CardActions>
    </Card>
  );
}

PricingCard.propTypes = {
  subheader: PropTypes.string,
  title: PropTypes.string.isRequired,
  price: PropTypes.number.isRequired,
  description: PropTypes.array.isRequired,
  buttonText: PropTypes.string.isRequired,
  info: PropTypes.string,
};

PricingCard.defaultProps = {
  subheader: '',
  info: '',
};

export default PricingCard;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/Cards/PricingCard.vue
<template>
  <v-card
    :class="{ bg: title === 'Pro'}"
    class="center-box price-card"
  >
    <v-card-title class="price-header justify-center">
      <h5
        :class="title === 'Free' ? 'use-text-secondary' : 'use-text-primary'"
        class="text-xs-center"
      >
        {{ title }}
      </h5>
      <v-icon
        v-if="title === 'Pro'"
        class="icon"
      >
        mdi-star-outline
      </v-icon>
      <div class="card-pricing">
        <h2 class="use-text-title text-xs-center">
          ${{ price }}
        </h2>
        <h6 class="title">
          &nbsp;/ mo
        </h6>
      </div>
    </v-card-title>
    <v-card-text class="pa-4">
      <ul>
        <li
          v-for="(line, index) in description"
          :key="index"
          class="text-center subtitle-1"
        >
          {{ line }}
        </li>
      </ul>
    </v-card-text>
    <div class="btn-area" :class="title === 'Free' ? 'secondary-color' : 'primary-color'">
      <p>{{ info }}</p>
      <v-btn
        :color="title === 'Free' ? 'secondary' : 'primary'"
        block
      >
        {{ $t('common.' + buttonText) }}
      </v-btn>
    </div>
  </v-card>
</template>

<style scoped lang="scss">
@import './pricing-card';
</style>

<script>
export default {
  props: {
    title: {
      type: String,
      required: true,
    },
    subheader: {
      type: String,
      default: '',
    },
    price: {
      type: String,
      required: true,
    },
    description: {
      type: Array,
      required: true,
    },
    info: {
      type: String,
      default: '',
    },
    buttonText: {
      type: String,
      required: true,
    },
    buttonVariant: {
      type: String,
      default: 'outlined',
    },
  },
};
</script>
