// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/pages/blog/index.vue
<template>
  <div class="main-wrap">
    <main-header />
    <div class="container-general">
      <v-container class="mt-10 mt-sm-0">
        <v-row>
          <v-col cols="12">
            <headline />
          </v-col>
        </v-row>
        <v-row class="mt-8">
          <v-col md="6" cols="12" class="px-3">
            <post-card
              :href="link.saas2.blogDetail"
              :img="imgAPI.photo[37]"
              title="Maecenas rutrum dolor sed nisi"
              desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
              date="12 Nov 2020"
              orientation="landscape"
              type="oval"
            />
          </v-col>
          <v-col md="6" cols="12" class="px-4">
            <post-card
              :href="link.saas2.blogDetail"
              :img="imgAPI.photo[36]"
              title="Maecenas rutrum dolor sed nisi"
              desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
              date="12 Nov 2020"
              orientation="landscape"
              type="oval"
            />
          </v-col>
        </v-row>
        <v-row class="mt-6">
          <v-col md="8">
            <div
              v-for="index in 6"
              :key="index"
              :class="{ 'mt-15': index > 1 }"
            >
              <post-card
                :href="link.saas2.blogDetail"
                :img="imgAPI.photo[30+index]"
                title="Maecenas rutrum dolor sed nisi"
                desc="Maecenas rutrum dolor sed nisi maximus rhoncus. Nunc vel dignissim enim. Proin pretium arcu eget"
                date="12 Nov 2020"
                orientation="portrait"
                type="oval"
              />
            </div>
            <div class="arrow">
              <v-row justify="space-between" class="mt-5">
                <v-btn variant="text">
                  <v-icon class="use-rtl-flip">
                    mdi-arrow-left
                  </v-icon>
                  {{ $t('common.btn_prev') }}
                </v-btn>
                <v-btn variant="text">
                  {{ $t('common.btn_next') }}
                  <v-icon class="use-rtl-flip">
                    mdi-arrow-right
                  </v-icon>
                </v-btn>
              </v-row>
            </div>
          </v-col>
          <v-col md="4" cols="12">
            <sidebar />
          </v-col>
        </v-row>
      </v-container>
    </div>
    <div id="footer">
      <main-footer />
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import '@/assets/scss/pages';
</style>

<script>
import brand from '@/assets/text/brand';
import BlogHeader from '@/components/Header/BlogHeader';
import Headline from '@/components/Blog/Headline';
import PostCard from '@/components/Cards/PostCard';
import Sidebar from '@/components/Blog/Sidebar';
import Footer from '@/components/Footer';
import imgAPI from '@/assets/images/imgAPI';
import link from '@/assets/text/link';
import { defineNuxtComponent } from '#app';

export default defineNuxtComponent({
  components: {
    'main-header': BlogHeader,
    'main-footer': Footer,
    Headline,
    Sidebar,
    PostCard,
  },
  data() {
    return {
      imgAPI,
      link,
    };
  },
  head() {
    return {
      title: 'Blog Home | ' + brand.saas2.desc,
    };
  },
});
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas-theme/pages/blog/index.js
import React, { Fragment } from 'react';
import PropTypes from 'prop-types';
import CssBaseline from '@mui/material/CssBaseline';
import Head from 'next/head';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { useTranslation } from 'next-i18next';
// Use this below for Server Side Render/Translation (SSR)
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// Use this below for Static Site Generation (SSG)
// import { getStaticPaths, makeStaticProps } from '~/lib/getStatic';
import { useSpacing } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import Header from '~/components/Header/BlogHeader';
import Headline from '~/components/Blog/Headline';
import PostCard from '~/components/Cards/PostCard';
import Sidebar from '~/components/Blog/Sidebar';
import Footer from '~/components/Footer';
import brand from '~/public/text/brand';
import link from '~/public/text/link';

function BlogHome(props) {
  const { classes } = useSpacing();
  const { onToggleDark, onToggleDir } = props;
  const { t } = useTranslation('common');
  return (
    <Fragment>
      <Head>
        <title>
          { brand.saas.name + ' - Blog' }
        </title>
      </Head>
      <CssBaseline />
      <section id="home" />
      <div className={classes.mainWrap}>
        <Header
          onToggleDark={onToggleDark}
          onToggleDir={onToggleDir}
        />
        <div className={classes.containerGeneral}>
          <Box pt={{ xs: 7, sm: 0 }}>
            <Container>
              <Grid container spacing={3}>
                <Grid item sm={12}>
                  <Headline />
                </Grid>
              </Grid>
              <Box mt={{ xs: 5, sm: 8 }}>
                <Grid container spacing={3}>
                  <Grid item md={6} xs={12}>
                    <PostCard
                      href={link.saas.blogDetail}
                      img={imgAPI.photo[37]}
                      title="Maecenas rutrum dolor sed nisi"
                      desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                      date="12 Nov 2020"
                      orientation="landscape"
                      type="oval"
                    />
                  </Grid>
                  <Grid item md={6} xs={12}>
                    <PostCard
                      href={link.saas.blogDetail}
                      img={imgAPI.photo[36]}
                      title="Maecenas rutrum dolor sed nisi"
                      desc="Proin pretium arcu eget metus porta consectetur Pellentesque habitant"
                      date="12 Nov 2020"
                      orientation="landscape"
                      type="oval"
                    />
                  </Grid>
                </Grid>
              </Box>
              <Box mt={2}>
                <Grid spacing={4} container>
                  <Grid item md={8} xs={12}>
                    {[...Array(6)].map((e, index) => (
                      <Box
                        key={index.toString()}
                        mt={index > 0 ? 8 : 0}
                      >
                        <PostCard
                          href={link.saas.blogDetail}
                          img={imgAPI.photo[30 + index]}
                          title="Maecenas rutrum dolor sed nisi"
                          desc="Maecenas rutrum dolor sed nisi maximus rhoncus. Nunc vel dignissim enim. Proin pretium arcu eget"
                          date="12 Nov 2020"
                          orientation="portrait"
                          type="oval"
                        />
                      </Box>
                    ))}
                    <Box mt={5} className={classes.arrow}>
                      <Grid container justifyContent="space-between">
                        <Button>
                          <ArrowBackIcon />
                          {t('btn_prev')}
                        </Button>
                        <Button>
                          {t('btn_next')}
                          <ArrowForwardIcon />
                        </Button>
                      </Grid>
                    </Box>
                  </Grid>
                  <Grid item md={4} xs={12}>
                    <Sidebar />
                  </Grid>
                </Grid>
              </Box>
            </Container>
          </Box>
        </div>
        <div id="footer" className={classes.spaceTopShort}>
          <Footer toggleDir={onToggleDir} />
        </div>
      </div>
    </Fragment>
  );
}

BlogHome.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

// Use this below for Server Side Render/Translation (SSR)
export const getStaticProps = async ({ locale }) => ({ props: { ...await serverSideTranslations(locale, ['common']) } });

// Use this below for Static Site Generation (SSG)
// const getStaticProps = makeStaticProps(['common']);
// export { getStaticPaths, getStaticProps };

export default BlogHome;
