// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Blog/Headline.js
import React from 'react';
import Card from '@mui/material/Card';
import CardActionArea from '@mui/material/CardActionArea';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';
import link from '~/public/text/link';
import { useText } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import useStyles from './blog-style';

function Headline() {
  const { classes, cx } = useStyles();
  const { classes: text } = useText();
  return (
    <Card className={classes.blogHeadline}>
      <CardMedia className={classes.media} image={imgAPI.photo[0]} />
      <CardActionArea href={link.crypto.blogDetail}>
        <CardContent>
          <span className={classes.anchorContent}>
            <span className={cx(classes.headlineTitle, text.title)}>
              Pellentesque habitant morbi tristique senectus Proin pretium arcu eget.
            </span>
            <span className={cx(classes.subtitle, text.subtitle)}>
              Multiple lines of text that form the lede, informing new readers quickly and efficiently about what&apos;s most interesting in this posts contents.
            </span>
          </span>
        </CardContent>
      </CardActionArea>
    </Card>
  );
}

export default Headline;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Blog/Headline.vue
<template>
  <v-card :href="link.crypto.blogDetail" class="blog-headline" dark>
    <v-img
      :src="imgAPI.photo[0]"
      class="text-white align-end"
      gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.8)"
      max-height="460px"
      width="100%"
      cover
    >
      <span class="content">
        <v-card-title class="headline-title use-text-title">Pellentesque habitant morbi tristique senectus </v-card-title>
        <v-card-subtitle class="text-h6 use-text-subtitle">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents. </v-card-subtitle>
      </span>
    </v-img>
  </v-card>
</template>

<style scoped lang="scss">
@import './blog-style.scss';
</style>

<script>
import link from '@/assets/text/link';
import imgAPI from '@/assets/images/imgAPI';

export default {
  data() {
    return {
      imgAPI,
      link,
    };
  },
};
</script>
