// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Decoration/HexaDeco.js
import React from 'react';
import PropTypes from 'prop-types';
import useStyles from './decoration-style';

export default function HexaDeco(props) {
  const { classes, cx } = useStyles();
  const { extend } = props;
  return (
    <div className={classes.hexaDeco}>
      {extend && (
        <div className={classes.extendDeco}>
          <svg className={cx(classes.hexa, classes.top)}>
            <use xlinkHref="/images/crypto/deco-hexa.svg#main" />
          </svg>
        </div>
      )}
      <div className={classes.decoBg} />
    </div>
  );
}

HexaDeco.propTypes = {
  extend: PropTypes.bool,
};

HexaDeco.defaultProps = {
  extend: false
};

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Decoration/HexaDeco.vue
<template>
  <div class="hexa-deco">
    <div v-if="extend" class="extend-deco">
      <svg class="hexa top">
        <use xlink:href="/images/crypto/deco-hexa.svg#main" />
      </svg>
      <svg class="hexa bottom">
        <use xlink:href="/images/crypto/deco-hexa.svg#main" />
      </svg>
    </div>
    <div class="deco-bg" />
  </div>
</template>

<style scoped lang="scss">
@import './decoration-style.scss';
</style>

<script>
export default {
  props: {
    extend: {
      type: Boolean,
      default: false,
    },
  },
};
</script>
