// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Decoration/BuildingDeco.js
import React from 'react';
import useStyles from './decoration-style';
import imgAPI from '~/public/images/imgAPI';

export default function FormDeco() {
  const { classes, cx } = useStyles();
  return (
    <div className={classes.buildingDeco}>
      <img
        className={cx(classes.imgLeft, 'img-2d3d')}
        src={imgAPI.cloud[29]}
        data-2d={imgAPI.cloud[28]}
        data-3d={imgAPI.cloud[29]}
        alt="building"
      />
      <img
        className={cx(classes.imgCenter, 'img-2d3d')}
        src={imgAPI.cloud[31]}
        data-2d={imgAPI.cloud[30]}
        data-3d={imgAPI.cloud[31]}
        alt="building"
      />
      <img
        className={cx(classes.imgLeft, 'img-2d3d')}
        src={imgAPI.cloud[29]}
        data-2d={imgAPI.cloud[28]}
        data-3d={imgAPI.cloud[29]}
        alt="building"
      />
    </div>
  );
}

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Decoration/BuildingDeco.vue
<template>
  <div class="building-deco">
    <img
      class="img-2d3d img-left"
      :src="imgAPI.cloud[29]"
      :data-2d="imgAPI.cloud[28]"
      :data-3d="imgAPI.cloud[29]"
      alt="building"
    >
    <img
      class="img-2d3d img-center"
      :src="imgAPI.cloud[31]"
      :data-2d="imgAPI.cloud[30]"
      :data-3d="imgAPI.cloud[31]"
      alt="building"
    >
    <img
      class="img-2d3d img-left"
      :src="imgAPI.cloud[29]"
      :data-2d="imgAPI.cloud[28]"
      :data-3d="imgAPI.cloud[29]"
      alt="building"
    >
  </div>
</template>

<style scoped lang="scss">
@import './decoration-style.scss';
</style>

<script>
import imgAPI from '@/assets/images/imgAPI';

export default {
  data() {
    return {
      imgAPI,
    };
  },
};
</script>
