// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Footer/Decoration.vue
<template>
  <div class="footer-deco" :class="{ bg: bg }">
    <div class="deco-wrap">
      <div class="deco bottom">
        <svg class="wave">
          <use xlink:href="/images.crypto/deco-wave.svg#main" />
        </svg>
      </div>
      <div class="deco top">
        <svg class="wave">
          <use xlink:href="/images.crypto/deco-wave.svg#main" />
        </svg>
      </div>
    </div>
    <div class="wave wave-cover" />
  </div>
</template>

<style scoped lang="scss">
@import './footer-deco.scss';
</style>

<script>
export default {
  props: {
    bg: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas2-theme/components/Footer/Decoration.js
import React from 'react';
import useStyles from './deco-style';

function Decoration() {
  const { classes, cx } = useStyles();
  return (
    <div className={classes.footerDeco}>
      <div className={classes.decoWrap}>
        <div className={cx(classes.deco, classes.bottom)}>
          <svg className={classes.wave}>
            <use xlinkHref="/images/saas2/deco-wave.svg#main" />
          </svg>
        </div>
        <div className={cx(classes.deco, classes.top)}>
          <div className={cx(classes.wave, classes.waveCover)} />
        </div>
      </div>
      <div className={cx(classes.wave, classes.waveCover)} />
    </div>
  );
}

export default Decoration;
