// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/saas2-theme/components/Error/Error.js
import React from 'react';
import PropTypes from 'prop-types';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import { useTranslation } from 'next-i18next';
import imgAPI from '~/public/images/imgAPI';
import { useText } from '~/theme/common';
import link from '~/public/text/link';
import useStyles from './error-style';

function Error(props) {
  const { classes } = useStyles();
  const { classes:  txt } = useText();
  const { errCode, text } = props;
  const { t } = useTranslation('common');

  return (
    <div className={classes.errorWrap}>
      <Container>
        <Grid container>
          <Grid item md={5} xs={12}>
            <div className={classes.flex}>
              <div className={classes.illustration}>
                <img
                  src={imgAPI.saas2Inner[9]}
                  data-2d={imgAPI.saas2Inner[8]}
                  data-3d={imgAPI.saas2Inner[9]}
                  className="img-2d3d"
                  alt="error"
                />
              </div>
            </div>
          </Grid>
          <Grid item md={7} xs={12}>
            <div className={classes.text}>
              <Typography variant="h1" className={txt.textPrimary}>
                <strong>
                  {errCode}
                </strong>
              </Typography>
              <Typography variant="h4">{text}</Typography>
              <Typography>
                {t('404_subtitle')}
              </Typography>
              <Button color="primary" variant="contained" href={link.saas2.home} size="large" className={classes.button}>
                {t('back')}
              </Button>
            </div>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

Error.propTypes = {
  errCode: PropTypes.string,
  text: PropTypes.string,

};

Error.defaultProps = {
  errCode: '404',
  text: '',
};

export default Error;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/saas2-theme/components/Error/Error.vue
<template>
  <div class="error-wrap mint">
    <v-container class="max-md">
      <v-row align="center">
        <v-col cols="12" md="5">
          <div class="flex">
            <div class="illustration">
              <img
                :src="imgAPI.saas2Inner[9]"
                :data-2d="imgAPI.saas2Inner[8]"
                :data-3d="imgAPI.saas2Inner[9]"
                class="img-2d3d"
                alt="error"
              >
            </div>
          </div>
        </v-col>
        <v-col cols="12" md="7">
          <div class="text">
            <h3 class="use-text-primary font-weight-bold">
              {{ errCode }}
            </h3>
            <h4 class="use-text-title2">
              {{ text }}
            </h4>
            <p>
              {{ $t('common.404_subtitle') }}
            </p>
            <v-btn
              :href="link.saas2.home"
              variant="outlined"
              color="primary"
              size="large"
              class="button"
            >
              {{ $t('common.back') }}
            </v-btn>
          </div>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './error-style.scss';
</style>

<script>
import link from '@/assets/text/link';
import imgAPI from '@/assets/images/imgAPI';

export default {
  props: {
    errCode: {
      type: Number,
      default: 404,
    },
    text: {
      type: String,
      default: '',
    },
  },
  data() {
    return {
      link,
      imgAPI,
    };
  },
};
</script>
