// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/cloud-theme/components/Home/Testimonials/Testimonials.js
import React, { useRef } from 'react';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Container from '@mui/material/Container';
import Carousel from 'react-slick';
import Button from '@mui/material/Button';
import { useTranslation } from 'next-i18next';
import Title from '../../Title';
import TestiCard from '../../Cards/TestiCard';
import useStyle from './testi-style';

const testiContent = [
  {
    text: 'Vivamus sit amet interdum elit. Proin lacinia erat ac velit tempus auctor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam nec ex aliquet, aliquam neque non.',
    name: 'John Doe',
    title: 'Chief Digital Officer',
  },
  {
    text: 'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jean Doe',
    title: 'Chief Digital Officer',
  },
  {
    text: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jena Doe',
    title: 'Graphic Designer',
  },
  {
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel.',
    name: 'Jovelin Doe',
    title: 'Senior Graphic Designer',
  },
  {
    text: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jihan Doe',
    title: 'CEO Software House',
  },
  {
    text: 'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jovelin Doe',
    title: 'Senior Graphic Designer',
  },
];

function Testimonials() {
  // Theme breakpoints
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('lg'));

  // Translation function
  const { t } = useTranslation('common');

  const slider = useRef(null);
  const { classes, cx } = useStyle();
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    autoplay: true,
    autoplaySpeed: 7000,
    slidesToShow: 2,
    arrows: false,
    pauseOnHover: true,
    responsive: [{
      breakpoint: 960,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      }
    }]
  };
  return (
    <div className={classes.root}>
      <Container fixed={isDesktop}>
        <Title
          caption={t('cloud-landing.testi_headtitle')}
          align="center"
          text={t('cloud-landing.testi_title')}
        />
        <div className={classes.sliderWrap}>
          <div className={classes.carousel}>
            <Button
              size="small"
              className={cx(classes.nav, classes.prev)}
              onClick={() => slider.current.slickPrev()}
            >
              <i className="ion-ios-arrow-back" />
            </Button>
            <Carousel ref={slider} {...settings}>
              {testiContent.map((item, index) => (
                <div key={index.toString()} className={classes.item}>
                  <TestiCard
                    text={item.text}
                    name={item.name}
                    title={item.title}
                  />
                </div>
              ))}
            </Carousel>
            <Button
              size="small"
              className={cx(classes.nav, classes.next)}
              onClick={() => slider.current.slickNext()}
            >
              <i className="ion-ios-arrow-forward" />
            </Button>
          </div>
        </div>
      </Container>
    </div>
  );
}

export default Testimonials;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/fintech-theme/components/Home/Testimonials/Testimonials.vue
<template>
  <div class="root">
    <v-container>
      <title-main
        :text="$t('fintech.testi_title')"
        align="center"
      />
      <p class="use-text-subtitle2 text-center">
        {{ $t('fintech.testi_subtitle') }}
      </p>
      <div class="slider-wrap">
        <div v-if="loaded" class="carousel">
          <v-btn
            size="small"
            class="nav prev"
            elevation="0"
            @click="slickPrev()"
          >
            <i class="ion-ios-arrow-back" />
          </v-btn>
          <splide
            ref="slider"
            :options="slickOptions"
          >
            <splide-slide
              v-for="(item, index) in testiContent"
              :key="index"
            >
              <div class="item">
                <testi-card
                  :img="item.img"
                  :text="item.text"
                  :name="item.name"
                  :title="item.title"
                />
              </div>
            </splide-slide>
          </splide>
          <v-btn
            size="small"
            class="nav next"
            elevation="0"
            @click="slickNext()"
          >
            <i class="ion-ios-arrow-forward" />
          </v-btn>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './testi-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';
import Title from '../../Title';
import TestiCard from '../../Cards/TestiCard2';
import imgAPI from '@/assets/images/imgAPI';

const testiData = [
  {
    img: imgAPI.fintech[34],
    text:
      'Vivamus sit amet interdum elit. Proin lacinia erat ac velit tempus auctor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam nec ex aliquet, aliquam neque non.',
    name: 'John Doe',
    title: 'Chief Digital Officer',
  },
  {
    img: imgAPI.fintech[35],
    text:
      'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jean Doe',
    title: 'Chief Digital Officer',
  },
  {
    img: imgAPI.fintech[36],
    text:
      'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'Jena Doe',
    title: 'Graphic Designer',
  },
  {
    img: imgAPI.fintech[37],
    text: 'Sed imperdiet enim ligula, vitae viverra justo porta vel.',
    name: 'Jack Doe',
    title: 'Senior Graphic Designer',
  },
  {
    img: imgAPI.fintech[38],
    text:
      'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero.',
    name: 'James Doe',
    title: 'CEO Software House',
  },
  {
    img: imgAPI.fintech[39],
    text:
      'Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices. Aenean facilisis vitae purus facilisis semper. Nam vitae scelerisque lorem, quis tempus libero.',
    name: 'Jovelin Doe',
    title: 'Senior Graphic Designer',
  },
];

export default {
  components: {
    'title-main': Title,
    TestiCard,
    Splide,
    SplideSlide,
  },
  data() {
    return {
      loaded: false,
      currentSlide: 0,
      testiContent: testiData,
      slickOptions: {
        pagination: false,
        type: 'loop',
        speed: 500,
        autoplay: true,
        interval: 7000,
        perPage: 2,
        perMove: 1,
        arrows: false,
        pauseOnHover: true,
        direction: 'ltr',
        reducedMotion: {
          speed: 500,
          rewindSpeed: 1000,
        },
        breakpoints: {
          960: {
            perPage: 1,
          },
        },
      },
    };
  },
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
      }
    }, 100);
  },
  methods: {
    slickNext() {
      this.$refs.slider.go('>');
    },
    slickPrev() {
      this.$refs.slider.go('<');
    },
  },
};
</script>
