// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/components/Header/Hamburger.js
import React, { useState, useEffect, Fragment } from 'react';
import PropTypes from 'prop-types';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import AppBar from '@mui/material/AppBar';
import Link from 'next/link';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Container from '@mui/material/Container';
import AnchorLink from 'react-anchor-link-smooth-scroll';
import Fade from '@mui/material/Fade';
import { useTranslation } from 'next-i18next';
import routeLink from '~/public/text/link';
import Logo from '../Logo';
import useStyles from './header-style';
import UserMenu from './TopNav/UserMenu';
import navMenu from './data/single';

let counter = 0;
function createData(name, url) {
  counter += 1;
  return {
    id: counter,
    name,
    url
  };
}

const LinkBtn = React.forwardRef(function LinkBtn(props, ref) { // eslint-disable-line
  return <AnchorLink to={props.to} {...props} />; // eslint-disable-line
});

function Hamburger(props) {
  // Theme breakpoints
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('md'));
  const { t } = useTranslation('common');

  const [fixed, setFixed] = useState(false);
  let flagFixed = false;
  const handleScroll = () => {
    const doc = document.documentElement;
    const scroll = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);
    const newFlagFixed = (scroll > 80);
    if (flagFixed !== newFlagFixed) {
      setFixed(newFlagFixed);
      flagFixed = newFlagFixed;
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
  }, []);

  const { classes, cx } = useStyles();
  const {
    onToggleDark,
    onToggleDir,
    home,
  } = props;
  const [menuList] = useState([
    createData(navMenu[0], '#' + navMenu[0]),
    createData(navMenu[1], '#' + navMenu[1]),
    createData(navMenu[2], '#' + navMenu[2]),
    createData(navMenu[3], '#' + navMenu[3]),
  ]);
  const [openDrawer, setOpenDrawer] = useState(false);
  const handleOpenDrawer = () => {
    setOpenDrawer(!openDrawer);
  };

  const handleCloseDrawer = () => {
    setOpenDrawer(false);
  };

  return (
    <Fragment>
      <AppBar
        component="div"
        position="relative"
        id="header"
        className={cx(
          classes.header,
          fixed ? classes.fixed : '',
          openDrawer && classes.openDrawer,
          home && classes.market
        )}
      >
        <Container fixed={isDesktop}>
          <div className={classes.headerContent}>
            <nav className={cx(classes.navLogo, home && classes.invert)}>
              <IconButton
                onClick={handleOpenDrawer}
                className={cx('hamburger hamburger--squeeze', classes.mobileMenu, openDrawer && 'is-active')}
                size="large"
              >
                <span className="hamburger-box">
                  <span className={cx(classes.bar, 'hamburger-inner')} />
                </span>
              </IconButton>
              <div className={cx(classes.logo, classes.flex)}>
                {home ? (
                  <LinkBtn href="#home">
                    <Logo type="only" />
                  </LinkBtn>
                ) : (
                  <Link href={routeLink.crypto.home}>
                    <a>
                      <Logo type="only" size="large" />
                    </a>
                  </Link>
                )}
              </div>
              <UserMenu onToggleDark={onToggleDark} onToggleDir={onToggleDir} />
            </nav>
          </div>
        </Container>
      </AppBar>
      <Fade in={openDrawer}>
        <div className={cx(classes.paperNav, openDrawer && classes.show)}>
          <div className={classes.mobileNav}>
            {openDrawer && (
              <ul className={classes.menu}>
                {menuList.map((item, index) => (
                  <li key={item.id.toString()} style={{ animationDuration: index * 0.15 + 's' }}>
                    {home ? (
                      // eslint-disable-next-line
                      <Button component={LinkBtn} onClick={handleCloseDrawer} offset={item.offset || 0} href={item.url}>
                        {t('crypto-landing.header_' + item.name)}
                      </Button>
                    ) : (
                      // eslint-disable-next-line
                      <Button href={'/' + item.url}>
                        {t('crypto-landing.header_' + item.name)}
                      </Button>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </Fade>
    </Fragment>
  );
}

Hamburger.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
  home: PropTypes.bool,

};

Hamburger.defaultProps = {
  home: false
};

export default Hamburger;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Header/Hamburger.vue
<template>
  <div>
    <v-app-bar
      v-scroll="handleScroll"
      :class="{ fixed: fixed, 'no-shadow': openDrawer, market: home }"
      class="header"
      fixed
      dense
      app
      height="auto"
    >
      <v-container>
        <div class="header-content">
          <nav class="nav-menu">
            <div class="hamburger-logo">
              <v-btn
                :class="{ 'is-active': openDrawer }"
                class="hamburger hamburger--spin mobile-menu"
                size="small"
                icon
                @click.stop="handleToggleOpen"
              >
                <span class="hamburger-box">
                  <span class="bar hamburger-inner" />
                </span>
              </v-btn>
              <div class="logo center">
                <a href="#home">
                  <logo type="only" />
                </a>
              </div>
            </div>
            <user-menu />
          </nav>
        </div>
      </v-container>
    </v-app-bar>
    <transition name="fade">
      <div v-if="openDrawer" class="paper-nav">
        <div class="hamburger-nav">
          <ul class="menu">
            <li
              v-for="(item, index) in menuList"
              :key="index"
              :style="{ 'animation-duration': index * 0.15 + 's' }"
            >
              <v-btn
                variant="text"
                :href="item.link"
                :class="{ active: activeMenu === item.name }"
                @click="scrollToMyEl(item.name)"
              >
                {{ $t('crypto.header_'+item.name) }}
              </v-btn>
            </li>
          </ul>
        </div>
      </div>
    </transition>
  </div>
</template>

<style lang="scss" scoped>
@import './header-style.scss';
</style>

<script>
import { ref, inject } from 'vue';
import { useRouter } from '#app';
import Logo from '../Logo';
import UserMenu from './TopNav/UserMenu';
import navMenu from './data/single';

let counter = 0;
function createData(name, link, offset) {
  counter += 1;
  return {
    id: counter,
    name,
    link,
    offset,
  };
}

export default {
  components: {
    UserMenu,
    Logo,
  },
  props: {
    home: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const openDrawer = ref(false);

    const smoothScroll = inject('smoothScroll');
    function scrollToMyEl(elemId) {
      const myEl = document.getElementById(elemId);
      const router = useRouter();
      openDrawer.value = false;

      router.push(`#${elemId}`);
      smoothScroll({
        scrollTo: myEl, // scrollTo is also allowed to be number
        hash: `#${elemId}`, // required if updateHistory is true
        offset: -50,
      });
    }

    function handleToggleOpen() {
      openDrawer.value = !openDrawer.value;
    }

    return {
      scrollToMyEl,
      openDrawer,
      handleToggleOpen,
    };
  },
  data() {
    return {
      fixed: false,
      navOffset: 20,
      activeMenu: '',
      sections: {},
      menuList: [
        createData(navMenu[0], '#' + navMenu[0]),
        createData(navMenu[1], '#' + navMenu[1]),
        createData(navMenu[2], '#' + navMenu[2]),
        createData(navMenu[3], '#' + navMenu[3], -40),
      ],
    };
  },
  mounted() {
    const id = window.location.hash;
    const content = id.replace('#', '');
    const element = document.getElementById(content);
    if (element) {
      element.scrollIntoView();
    }

    const section = document.querySelectorAll('.scroll-nav-content > *');
    Array.prototype.forEach.call(section, (e) => {
      this.sections[e.id] = e.offsetTop;
    });
  },
  methods: {
    handleScroll() {
      const scrollPosition = document.documentElement.scrollTop || document.body.scrollTop;
      const topPosition = scrollPosition + 200;

      Object.keys(this.sections).forEach((i) => {
        if (this.sections[i] <= topPosition) {
          this.activeMenu = i;
        }
      });

      if (scrollPosition > 70) {
        this.fixed = true;
      } else {
        this.fixed = false;
      }
    },
  },
};
</script>
