// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/crypto-theme/components/Home/MarketPrice/MarketPrice.js
import React from 'react';
import Avatar from '@mui/material/Avatar';
import Carousel from 'react-slick';
import useStyles from './market-price-style';

const marketList = [
  {
    logo: '/images/crypto/btc.png',
    name: 'BTC',
    price: 10200,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/xrp.png',
    name: 'XRP',
    price: 0.003,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/nem.png',
    name: 'NEM',
    price: 0.003,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/iot.png',
    name: 'IOTA',
    price: 0.010,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/mnr.png',
    name: 'MNR',
    price: 1.45,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/byc.png',
    name: 'BYC',
    price: 22.34,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/iot.png',
    name: 'IOTA',
    price: 0.010,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/mnr.png',
    name: 'MNR',
    price: 1.45,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/byc.png',
    name: 'BYC',
    price: 22.34,
    status: 'down',
    percent: 3,
  },
];

export default function MarketPrice() {
  const { classes } = useStyles();
  const settings = {
    dots: false,
    arrows: false,
    infinite: true,
    slidesToShow: 6,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 5000,
    speed: 300,
    cssEase: 'linear',
    pauseOnHover: true
  };
  const renderPercent = (arrow, percent) => {
    switch (arrow) {
      case 'down':
        return (
          <span className={classes.down}>
            <i>▼</i>
            {percent}
            %
          </span>
        );
      case 'up':
        return (
          <span className={classes.up}>
            <i>▲</i>
            {percent}
            %
          </span>
        );
      default:
        return (
          <span className={classes.stay}>
            <i>-</i>
            {percent}
            %
          </span>
        );
    }
  };
  return (
    <div className={classes.market}>
      <Carousel {...settings}>
        {marketList.map((item, index) => (
          <div className={classes.item} key={index.toString()}>
            <div className={classes.coin}>
              <Avatar className={classes.logo} src={item.logo} alt={item.name} />
              {item.name}
              &nbsp;$&nbsp;
              {item.price}
              &nbsp;(
              {renderPercent(item.status, item.percent)}
              )
            </div>
          </div>
        ))}
      </Carousel>
    </div>
  );
}

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/components/Home/MarketPrice/MarketPrice.vue
<template>
  <div v-if="loaded" class="market">
    <splide :options="slickOptions">
      <splide-slide
        v-for="(item, index) in marketList"
        :key="index"
      >
        <div class="item">
          <div class="coin">
            <v-avatar class="logo" height="20" width="20" min-width="20">
              <img :src="item.logo" :alt="item.name">
            </v-avatar>
            {{ item.name }}
            {{ item.price }}
            (<span v-if="item.status === 'down'" class="down">
              <i>▼</i>{{ item.percent }}%
            </span>
            <span v-if="item.status === 'up'" class="up">
              <i>▲</i>{{ item.percent }}%
            </span>
            <span v-if="item.status === 'stay'" class="stay">
              <i>-</i>{{ item.percent }}%
            </span>)
          </div>
        </div>
      </splide-slide>
    </splide>
  </div>
</template>

<style lang="scss" scoped>
@import './market-price-style.scss';
</style>

<script>
import { Splide, SplideSlide } from '@splidejs/vue-splide';

const marketList = [
  {
    logo: '/images/crypto/btc.png',
    name: 'BTC',
    price: 1020,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/xrp.png',
    name: 'XRP',
    price: 0.003,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/nem.png',
    name: 'NEM',
    price: 0.03,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/iot.png',
    name: 'IOTA',
    price: 0.01,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/mnr.png',
    name: 'MNR',
    price: 1.45,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/byc.png',
    name: 'BYC',
    price: 22.34,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/iot.png',
    name: 'IOTA',
    price: 0.01,
    status: 'down',
    percent: 3,
  },
  {
    logo: '/images/crypto/mnr.png',
    name: 'MNR',
    price: 1.45,
    status: 'up',
    percent: 8,
  },
  {
    logo: '/images/crypto/byc.png',
    name: 'BYC',
    price: 22.34,
    status: 'down',
    percent: 3,
  },
];

export default {
  components: {
    Splide,
    SplideSlide,
  },
  data: () => ({
    marketList,
    loaded: false,
    slickOptions: {
      pagination: false,
      arrows: false,
      type: 'loop',
      perPage: 6,
      perMove: 1,
      autoplay: true,
      invterval: 5000,
      speed: 500,
      pauseOnHover: true,
      direction: 'ltr',
      easing: 'ease',
      reducedMotion: {
        autoplay: true,
        speed: 500,
        rewindSpeed: 1000,
      },
    },
  }),
  mounted() {
    this.loaded = true;
    setTimeout(() => {
      if (this.$vuetify.locale.isRtl) {
        this.slickOptions.direction = 'rtl';
      } else {
        this.slickOptions.direction = 'ltr';
      }
    }, 100);
  },
};
</script>
