// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Integration/Integration.vue
<template>
  <div class="root">
    <v-container>
      <div>
        <v-row>
          <div class="dashed-divider" />
          <v-col cols="12" md="6">
            <div
              data-aos="fade-down"
              data-aos-delay="500"
              data-aos-offset="100"
              data-aos-duration="500"
            >
              <div>
                <figure class="illustration">
                  <svg class="droplet secondary-color">
                    <use xlink:href="/images/cloud/droplet.svg#main" />
                  </svg>
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[21]"
                    :data-2d="imgAPI.cloud[20]"
                    :data-3d="imgAPI.cloud[21]"
                    alt="background"
                  >
                </figure>
                <main-title
                  :caption="$t('cloud.mainfeature_titleitem2')"
                  :text="$t('cloud.mainfeature_titleitem1')"
                  align="center"
                />
              </div>
            </div>
          </v-col>
          <v-col cols="12" md="6">
            <div
              data-aos="fade-down"
              data-aos-delay="800"
              data-aos-offset="100"
              data-aos-duration="500"
            >
              <div>
                <figure class="illustration">
                  <svg class="droplet primary-color">
                    <use xlink:href="/images/cloud/droplet.svg#main" />
                  </svg>
                  <img
                    class="img-2d3d"
                    :src="imgAPI.cloud[23]"
                    :data-2d="imgAPI.cloud[22]"
                    :data-3d="imgAPI.cloud[23]"
                    alt="background"
                  >
                </figure>
                <main-title
                  :caption="$t('cloud.morefeature_headtitle2')"
                  :text="$t('cloud.benefit_title')"
                  align="center"
                />
              </div>
            </div>
          </v-col>
        </v-row>
      </div>
      <div class="timeline">
        <div class="solid-divider" />
        <div>
          <v-row>
            <v-col sm="6" cols="12" class="px-lg-10">
              <ul class="left-side">
                <li
                  v-for="(item, index) in integration1"
                  :key="index"
                  :class="'type-' + item.color"
                >
                  <div
                    data-aos="fade-left"
                    :data-aos-delay="(200 + (100 * index))"
                    data-aos-offset="100"
                    data-aos-duration="500"
                  >
                    <div class="item">
                      <div class="text">
                        <strong class="use-text-subtitle2">{{ item.title }}</strong>
                        <p>{{ item.subtitle }}</p>
                      </div>
                      <div class="icon">
                        <i :class="item.icon" />
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </v-col>
            <v-col sm="6" cols="12" class="px-lg-10">
              <ul class="right-side">
                <li
                  v-for="(item, index) in integration2"
                  :key="index"
                  :class="'type-' + item.color"
                >
                  <div
                    data-aos="fade-right"
                    :data-aos-delay="(200 + (200 * index))"
                    data-aos-offset="100"
                    data-aos-duration="500"
                  >
                    <div class="item">
                      <div class="icon">
                        <i :class="item.icon" />
                      </div>
                      <div class="text">
                        <strong class="use-text-subtitle2">{{ item.title }}</strong>
                        <p>{{ item.subtitle }}</p>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </v-col>
          </v-row>
        </div>
      </div>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import 'integration-style.scss';
</style>

<script>
import AOS from 'aos';
import imgAPI from '@/assets/images/imgAPI';
import Title from '../../Title';

export default {
  components: {
    'main-title': Title,
  },
  data() {
    return {
      imgAPI,
      integration1: [
        {
          color: 'secondary',
          icon: 'ion-ios-flash',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'secondary',
          icon: 'ion-ios-folder-open',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'secondary',
          icon: 'ion-ios-lock',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
      ],
      integration2: [
        {
          color: 'primary',
          icon: 'ion-md-git-merge',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'primary',
          icon: 'ion-logo-buffer',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
        {
          color: 'primary',
          icon: 'ion-md-cloud-upload',
          title: 'Nam vitae scelerisque lorem',
          subtitle: 'Quis tempus libero proin varius',
        },
      ],
    };
  },
  mounted() {
    AOS.init({
      once: true,
    });
  },
};
</script>

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/saas-theme/components/Home/Integration/Integration.js
import React from 'react';
import Container from '@mui/material/Container';
import ScrollAnimation from 'react-scroll-animation-wrapper';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'next-i18next';
import { useText, useTextAlign } from '~/theme/common';
import imgAPI from '~/public/images/imgAPI';
import useStyle from './integration-style';
import Title from '../../Title';

const integration1 = [
  {
    color: 'Primary',
    icon: 'ion-android-time',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Accent',
    icon: 'ion-ios-lightbulb-outline',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Secondary',
    icon: 'ion-ios-world-outline',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  }
];

const integration2 = [
  {
    color: 'Secondary',
    icon: 'ion-ios-flask-outline',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Primary',
    icon: 'ion-ios-navigate-outline',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  },
  {
    color: 'Accent',
    icon: 'ion-wand',
    title: 'Nam vitae scelerisque lorem',
    subtitle: 'Quis tempus libero proin varius'
  }
];

function Intergration() {
  const { classes, cx } = useStyle();
  const { t } = useTranslation('common');

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const { classes: text } = useText();
  const { classes: align } = useTextAlign();

  return (
    <div className={classes.root}>
      <div className={classes.decorationBg}>
        <svg className={classes.wave}>
          <use xlinkHref="/images/saas/deco-bg2.svg#main" />
        </svg>
      </div>
      <Container>
        <Grid container className={classes.decoWrap}>
          <div className={classes.dashedDivider} />
          <Grid item md={6} xs={12}>
            <Box mb={isMobile ? 10 : 0} px={{ sm: 5 }}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInUpShort"
                offset={-100}
                delay={500}
                duration={0.5}
              >
                <div>
                  <figure className={classes.illustration}>
                    <img
                      className="img-2d3d"
                      src={imgAPI.saas[16]}
                      data-2d={imgAPI.saas[15]}
                      data-3d={imgAPI.saas[16]}
                      alt="background"
                    />
                  </figure>
                  <Title align="center">
                    <span>
                      {t('saas-landing.feature_title1')}
                    </span>
                  </Title>
                  <h6 className={cx(text.subtitle2, align.textCenter)}>
                    {t('saas-landing.feature_desc1')}
                  </h6>
                </div>
              </ScrollAnimation>
            </Box>
          </Grid>
          <Grid item md={6} xs={12}>
            <Box px={{ sm: 5 }}>
              <ScrollAnimation
                animateOnce
                animateIn="fadeInUpShort"
                offset={-100}
                delay={800}
                duration={0.5}
              >
                <div>
                  <figure className={classes.illustration}>
                    <img
                      className="img-2d3d"
                      src={imgAPI.saas[18]}
                      data-2d={imgAPI.saas[17]}
                      data-3d={imgAPI.saas[18]}
                      alt="background"
                    />
                  </figure>
                  <Title align="center">
                    <span>
                      {t('saas-landing.feature_title3')}
                    </span>
                  </Title>
                  <h6 className={cx(text.subtitle2, align.textCenter)}>
                    {t('saas-landing.feature_desc2')}
                  </h6>
                </div>
              </ScrollAnimation>
            </Box>
          </Grid>
        </Grid>
      </Container>
      <Container>
        <div className={classes.timeline}>
          <div className={classes.solidDivider} />
          <Grid container>
            <Grid item sm={6} xs={12}>
              <Box px={{ md: 5 }}>
                <ul className={classes.leftSide}>
                  {integration1.map((item, index) => (
                    <li
                      key={index.toString()}
                      className={classes['type' + item.color]}
                    >
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInRightShort"
                        offset={-100}
                        delay={(200 + (100 * index))}
                        duration={0.5}
                      >
                        <div className={classes.item}>
                          <div className={classes.text}>
                            <strong>{item.title}</strong>
                            <p>{item.subtitle}</p>
                          </div>
                          <div className={classes.icon}>
                            <i className={item.icon} />
                          </div>
                        </div>
                      </ScrollAnimation>
                    </li>
                  ))}
                </ul>
              </Box>
            </Grid>
            <Grid item sm={6} xs={12}>
              <Box px={{ md: 5 }}>
                <ul className={classes.rightSide}>
                  {integration2.map((item, index) => (
                    <li
                      key={index.toString()}
                      className={classes['type' + item.color]}
                    >
                      <ScrollAnimation
                        animateOnce
                        animateIn="fadeInLeftShort"
                        offset={-100}
                        delay={(200 + (200 * index))}
                        duration={0.5}
                      >
                        <div className={classes.item}>
                          <div className={classes.icon}>
                            <i className={item.icon} />
                          </div>
                          <div className={classes.text}>
                            <strong>{item.title}</strong>
                            <p>{item.subtitle}</p>
                          </div>
                        </div>
                      </ScrollAnimation>
                    </li>
                  ))}
                </ul>
              </Box>
            </Grid>
          </Grid>
        </div>
      </Container>
    </div>
  );
}

export default Intergration;
