// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/retail-theme/components/CallAction/CallAction.js
import React from 'react';
import Button from '@mui/material/Button';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import useStyles from './action-style';

function CallAction() {
  // Translation Function
  const { t } = useTranslation('common');
  const { classes: text } = useText();

  const { classes } = useStyles();
  return (
    <div className={classes.action}>
      <h4 className={text.title2}>
        {t('retail-landing.footer_text')}
      </h4>
      <div className={classes.btnArea}>
        <Button href="#" variant="contained" color="primary">{t('btn_get')}</Button>
      </div>
    </div>
  );
}

export default CallAction;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/CallAction/CallAction.vue
<template>
  <div class="action">
    <h4 class="use-text-title2">
      {{ $t('retail.footer_text') }}
    </h4>
    <div class="btn-area">
      <v-btn color="primary">
        {{ $t('common.btn_get') }}
      </v-btn>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import './action-style.scss';
</style>
