// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/default/packages/crypto-theme/pages/[locale]/utils/coming-soon.js
import React, { useState, Fragment } from 'react';
import CssBaseline from '@mui/material/CssBaseline';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import FilledInput from '@mui/material/FilledInput';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Head from 'next/head';
import FacebookIcon from '@mui/icons-material/Facebook';
import InstagramIcon from '@mui/icons-material/Instagram';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import TwitterIcon from '@mui/icons-material/Twitter';
import { useTranslation } from 'next-i18next';
// Use this below for Server Side Render/Translation (SSR)
// import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// Use this below for Static Site Generation (SSG)
import { getStaticPaths, makeStaticProps } from '~/lib/getStatic';
import Logo from '~/components/Logo';
import HexaDeco from '~/components/Decoration/HexaDeco';
import { useSpacing, useTextAlign, useText } from '~/theme/common';
import brand from '~/public/text/brand';

function ComingSoon() {
  const { classes, cx } = useSpacing();
  const { classes: align } = useTextAlign();
  const { classes: text } = useText();
  const { t } = useTranslation('common');

  // Breakpoints
  const theme = useTheme();
  const isDesktop = useMediaQuery(theme.breakpoints.up('sm'));

  const [email, setEmail] = useState('');

  const handleChange = event => {
    setEmail(event.target.value);
  };

  return (
    <Fragment>
      <Head>
        <title>
          { brand.crypto.name + ' - Coming Soon' }
        </title>
      </Head>
      <CssBaseline />
      <HexaDeco extend />
      <Container maxWidth="sm">
        <div className={classes.fullScreenContainer}>
          <Grid container alignItems="center">
            <Grid item md={12} xs={12} className={align.textCenter}>
              <Box
                className={classes.logo}
                display="flex"
                justifyContent="center"
                alignItems="center"
                mb={5}
              >
                <Logo type="landscape" size="large" />
              </Box>
              <div className={align.textCenter}>
                <h3 className={cx(text.title, text.textPrimary)}>
                  {t('util_soon')}
                </h3>
                <Box mb={5}>
                  <h5 className={text.subtitle2}>
                    {t('util_soon_desc')}
                  </h5>
                </Box>
                <div className={classes.form}>
                  <Box mb={{ sm: 4 }}>
                    <Grid container justifyContent="center">
                      <Grid item sm={10} xs={12}>
                        <FormControl variant="standard" fullWidth>
                          <InputLabel variant="filled" htmlFor="standard-adornment-password">{t('form_email')}</InputLabel>
                          <FilledInput
                            fullWidth
                            id="standard-adornment-password"
                            value={email}
                            onChange={handleChange}
                            endAdornment={isDesktop && (
                              <Button
                                variant="contained"
                                color="primary"
                                type="submit"
                                size="small"
                                className={classes.btnNotify}
                              >
                                {t('util_notif')}
                              </Button>
                            )}
                          />
                        </FormControl>
                        {!isDesktop && (
                          <Box my={3}>
                            <Button
                              variant="contained"
                              color="primary"
                              type="submit"
                              fullWidth
                            >
                              {t('util_notif')}
                            </Button>
                          </Box>
                        )}
                      </Grid>
                    </Grid>
                  </Box>
                </div>
                <div>
                  <IconButton color="primary" href="#" size="large"><FacebookIcon className={classes.fb} /></IconButton>
                  <IconButton color="primary" href="#" size="large"><InstagramIcon className={classes.ig} /></IconButton>
                  <IconButton color="primary" href="#" size="large"><TwitterIcon className={classes.tw} /></IconButton>
                  <IconButton color="primary" href="#" size="large"><LinkedInIcon className={classes.li} /></IconButton>
                </div>
              </div>
            </Grid>
          </Grid>
        </div>
      </Container>
    </Fragment>
  );
}

export default ComingSoon;

// Use this below for Server Side Render/Translation (SSR)
// export const getStaticProps = async ({ locale }) => ({ props: { ...await serverSideTranslations(locale, ['common']) } });

// Use this below for Static Site Generation (SSG)
const getStaticProps = makeStaticProps(['common']);
export { getStaticPaths, getStaticProps };

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/crypto-theme/pages/utils/coming-soon.vue
<template>
  <div class="main-wrap">
    <hexa-deco extend />
    <v-container class="max-md">
      <div class="full-screen-container">
        <v-row align="center">
          <v-col md="12" class="text-center">
            <div class="logo d-flex justify-center align-center mb-10">
              <img
                :src="brand.crypto.img"
                alt="logo"
                width="64"
              >
              <h2 class="ps-3 use-text-subtitle">
                {{ brand.crypto.name }}
              </h2>
            </div>
            <div class="text-center">
              <h3 class="use-text-title use-text-primary">
                {{ $t('common.util_soon') }}
              </h3>
              <h5 class="use-text-subtitle2" :class="{ 'mb-10': isDesktop}">
                {{ $t('common.util_soon_desc') }}
              </h5>
              <div class="form mt-10" :class="{ 'mb-15': isDesktop}">
                <v-row justify="center">
                  <v-col sm="8" cols="12">
                    <v-text-field
                      :label="$t('common.form_email')"
                      :elevation="0"
                      color="secondary"
                      variant="filled"
                      class="input-field"
                    >
                      <template v-if="isDesktop" #append-inner>
                        <v-btn class="my-2" color="primary">
                          {{ $t('common.util_notif') }}
                        </v-btn>
                      </template>
                    </v-text-field>
                    <v-btn v-if="!isDesktop" block class="mb-2" color="primary">
                      {{ $t('common.util_notif') }}
                    </v-btn>
                  </v-col>
                </v-row>
              </div>
              <div class="socmed-btn mt-10">
                <v-btn icon size="large" variant="text" href="#">
                  <v-icon color="indigo">
                    mdi-facebook
                  </v-icon>
                </v-btn>
                <v-btn icon size="large" variant="text" href="#">
                  <v-icon color="blue">
                    mdi-twitter
                  </v-icon>
                </v-btn>
                <v-btn icon size="large" variant="text" href="#">
                  <v-icon color="purple">
                    mdi-instagram
                  </v-icon>
                </v-btn>
                <v-btn icon size="large" variant="text" href="#">
                  <v-icon color="blue">
                    mdi-linkedin
                  </v-icon>
                </v-btn>
              </div>
            </div>
          </v-col>
        </v-row>
      </div>
    </v-container>
  </div>
</template>

<style scoped lang="scss">
@import '@/assets/scss/pages.scss';
</style>

<script>
import brand from '@/assets/text/brand';
import HexaDeco from '@/components/Decoration/HexaDeco';
import { defineNuxtComponent } from '#app';

export default defineNuxtComponent({
  components: {
    HexaDeco,
  },
  data() {
    return {
      brand,
    };
  },
  head() {
    return {
      title: brand.crypto.name + ' - Coming Soon',
    };
  },
  computed: {
    isDesktop() {
      const smUp = this.$vuetify.display.smAndUp;
      return smUp;
    },
  },
});
</script>
