// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/social-apps-theme/components/Footer/Blog.js
import React from 'react';
import PropTypes from 'prop-types';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import ButtonBase from '@mui/material/ButtonBase';
import Link from '@mui/material/Link';
import IconButton from '@mui/material/IconButton';
import { useTranslation } from 'next-i18next';
import Decoration from './Decoration';
import brand from '~/public/text/brand';
import img from '~/public/images/imgAPI';
import Logo from '../Logo';
import SelectLang from '../LangSwitch/Select';
import useStyles from './blog-style';

function Copyright() {
  return (
    <Typography display="block" align="center">
      &copy;&nbsp;
      {brand.social.footerText}
    </Typography>
  );
}

const footer = {
  title: 'Quick Links',
  description: ['Resource', 'Another resource', 'Final resource', 'Privacy policy', 'Terms of use', 'Terms Condition'],
  link: ['#resource', '#another-resource', '#final-resource', '#privacy-policy', '#terms-of-use'],
};

const news = [
  {
    type: 'news',
    text: 'Sed imperdiet enim ligula vitae viverra.',
    img: img.photo[4]
  },
  {
    type: 'news',
    text: 'Sed imperdiet enim ligula vitae viverra.',
    img: img.photo[1]
  },
  {
    type: 'news',
    text: 'Sed imperdiet enim ligula vitae viverra.',
    img: img.photo[3]
  }
];

function Blog(props) {
  const { classes, cx } = useStyles();
  const { toggleDir, bg } = props;
  const { t } = useTranslation('common');

  return (
    <footer className={cx(classes.footer, bg ? classes.hasBg : '')}>
      <Decoration bg={bg} />
      <Container className={classes.root} fixed>
        <Grid container spacing={6}>
          <Grid item xs={12} md={5}>
            <div className={classes.logo}>
              <Logo type="landscape" />
            </div>
            <Typography color="textPrimary" className={classes.footerDesc} gutterBottom>
              {t('social-landing.banner_title')}
              &nbsp;
              {t('social-landing.banner_desc')}
            </Typography>
            <div className={classes.quickLinks}>
              <Typography variant="h6" className={classes.title} color="textPrimary" gutterBottom>
                {t('footer_link')}
              </Typography>
              <ul>
                {footer.description.map((item, index) => (
                  <li key={item}>
                    <Link
                      href={footer.link[index]}
                      variant="subtitle1"
                      color="textSecondary"
                      underline="hover"
                    >
                      {item}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </Grid>
          <Grid item xs={12} md={4}>
            {news.map((item, index) => (
              <ButtonBase className={classes.blogItem} href="#" key={index.toString()}>
                <figure>
                  <img src={item.img} alt="thumb" />
                </figure>
                <div className={classes.listText}>
                  <Typography variant="button" className={classes.category}>
                    {t('footer_news')}
                  </Typography>
                  <Typography display="block" component="p">Sed imperdiet enim ligula vitae viverra. </Typography>
                </div>
              </ButtonBase>
            ))}
          </Grid>
          <Grid item xs={12} md={3}>
            <div className={classes.socmed}>
              <IconButton aria-label="FB" className={classes.margin} size="small">
                <i className="ion-social-twitter" />
              </IconButton>
              <IconButton aria-label="TW" className={classes.margin} size="small">
                <i className="ion-social-facebook" />
              </IconButton>
              <IconButton aria-label="IG" className={classes.margin} size="small">
                <i className="ion-social-instagram" />
              </IconButton>
              <IconButton aria-label="LI" className={classes.margin} size="small">
                <i className="ion-social-linkedin" />
              </IconButton>
            </div>
            <SelectLang toggleDir={toggleDir} />
            <Copyright />
          </Grid>
        </Grid>
      </Container>
    </footer>
  );
}

Blog.propTypes = {
  toggleDir: PropTypes.func,
  bg: PropTypes.bool
};

Blog.defaultProps = {
  toggleDir: () => {},
  bg: false
};

export default Blog;

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/retail-theme/components/Footer/Blog.vue
<template>
  <footer class="footer">
    <v-container class="fixed-width">
      <v-row class="spacing6">
        <v-col
          class="pa-6"
          md="5"
          cols="12"
        >
          <logo type="landscape" />
          <p class="footer-desc">
            {{ $t('retail.banner_desc') }}
          </p>
          <div class="quick-links">
            <h6 class="title-nav mb-2">
              {{ $t('common.footer_link') }}
            </h6>
            <ul>
              <li
                v-for="(item, index) in footer.description"
                :key="item"
              >
                <nuxt-link :to="footer.link[index]">
                  {{ item }}
                </nuxt-link>
              </li>
            </ul>
          </div>
        </v-col>
        <v-col
          class="py-md-0 pa-6"
          md="4"
          cols="12"
        >
          <v-btn
            v-for="(item, index) in news"
            :key="index"
            variant="text"
            class="blog-item"
            href="#"
          >
            <span class="figure">
              <img :src="item.img" alt="thumb">
            </span>
            <span class="list-text">
              <span class="category">
                {{ $t('common.footer_news') }}
              </span>
              <span class="content">
                Sed imperdiet enim ligula vitae viverra.
              </span>
            </span>
          </v-btn>
        </v-col>
        <v-col
          md="3"
          cols="12"
          class="py-md-0 px-8 py-6"
        >
          <div class="socmed">
            <v-btn
              variant="text"
              icon
              size="small"
              class="button"
            >
              <span class="ion-logo-twitter icon" />
            </v-btn>
            <v-btn
              variant="text"
              icon
              size="small"
              class="button"
            >
              <span class="ion-logo-facebook icon" />
            </v-btn>
            <v-btn
              variant="text"
              icon
              size="small"
              class="button"
            >
              <span class="ion-logo-instagram icon" />
            </v-btn>
            <v-btn
              variant="text"
              icon
              size="small"
              class="button"
            >
              <span class="ion-logo-linkedin icon" />
            </v-btn>
          </div>
          <v-select
            v-model="lang"
            :items="langList"
            :value="curLang"
            variant="outlined"
            class="select-lang"
            color="primary"
            prepend-inner-icon="mdi-web"
            @update:model-value="switchLang(lang)"
          />
          <p class="body-2">
            &copy;&nbsp;
            {{ brand.retail.footerText }}
          </p>
        </v-col>
      </v-row>
    </v-container>
  </footer>
</template>

<style scoped lang="scss">
@import './footer-blog';
</style>

<script>
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useSwitchLocalePath } from 'vue-i18n-routing';
import { setRtl } from '@/composables/uiTheme';
import brand from '@/assets/text/brand';
import img from '@/assets/images/imgAPI';
import Logo from '../Logo';
import { navigateTo } from '#app';

export default {
  components: {
    Logo,
  },
  props: {
    extend: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const switchLocalePath = useSwitchLocalePath();

    const i18n = useI18n();
    const curLang = i18n.locale.value;
    const lang = ref(curLang);

    function switchLang(locale) {
      navigateTo(switchLocalePath(locale));
      lang.value = locale;

      // Set RTL and Document attr
      document.documentElement.setAttribute('lang', locale);

      if (locale === 'ar') {
        setRtl(true);
        document.documentElement.setAttribute('dir', 'rtl');
      } else {
        setRtl(false);
        document.documentElement.setAttribute('dir', 'ltr');
      }
    }

    return {
      curLang,
      switchLang,
      lang,
    };
  },
  data: () => ({
    brand,
    footer: {
      title: 'Quick Links',
      description: ['Resource', 'Another resource', 'Final resource', 'Privacy policy', 'Terms of use', 'Terms Condition'], // eslint-disable-line
      link: ['#', '#', '#', '#', '#', '#'] // eslint-disable-line
    },
    news: [
      {
        type: 'news',
        text: 'Sed imperdiet enim ligula vitae viverra.',
        img: img.photo[4],
      },
      {
        type: 'news',
        text: 'Sed imperdiet enim ligula vitae viverra.',
        img: img.photo[1],
      },
      {
        type: 'news',
        text: 'Sed imperdiet enim ligula vitae viverra.',
        img: img.photo[3],
      },
    ],
  }),
  computed: {
    langList() {
      const list = [];
      const i18n = this.$i18n.locales;

      i18n.map((locale) => {
        list.push({ title: this.$t('common.' + locale.code), value: locale.code });
        return false;
      });
      return list;
    },
  },
};
</script>
