// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/react/simple-routing/cloud-theme/components/Home/Feature/Feature.js
import React from 'react';
import MainFeature from './MainFeature';
import MoreFeature from './MoreFeature';
import useStyles from './feature-style';

export default function Feature() {
  const { classes } = useStyles();
  return (
    <div className={classes.root}>
      <MainFeature />
      <MoreFeature />
    </div>
  );
}

// narabotki/themeforest-SudGYk4H-oiron-react-js-landing-page-collection/oiron_v162/vue/packages/cloud-theme/components/Home/Feature/Feature.vue
<template>
  <div class="root">
    <main-feature />
    <more-feature />
  </div>
</template>

<style lang="scss" scoped>
@import './feature-style.scss';
</style>

<script>
import MainFeature from './MainFeature';
import MoreFeature from './MoreFeature';

export default {
  components: {
    MainFeature,
    MoreFeature,
  },
};
</script>
